### ISSUE TITLE
Setting verify depth for X509Store

### ISSUE THREAD

**Issue by Fethbita** [pyca/pyopenssl#1000]
I have a lot of certificates that I add into `X509Store` and when I try to use `X509StoreContext`'s `.verify_certificate()`, I get `path length constraint exceeded` error. I couldn't find the way to set the depth for X509Store which should be possible.
Here's an example:

```
from OpenSSL.crypto import load_crl, FILETYPE_ASN1, X509Store, X509StoreFlags, X509StoreContext, X509StoreContextError

store = X509Store()
store.load_locations("masterList.pem")
CRL = load_crl(FILETYPE_ASN1, crl_file.read())
store.add_crl(CRL)

store.set_flags(X509StoreFlags.CRL_CHECK_ALL)

CDS = load_certificate(FILETYPE_ASN1, to_verify)
store_ctx = X509StoreContext(store, CDS)
# store_ctx.set_verify_depth(999) #doesn't work

store_ctx.verify_certificate()
 # ([25, 2, 'path length constraint exceeded'],)
```

**Comment by tiran** [comment]
``path length constraint exceeded`` is not related to verify depth. The error ``X509_V_ERR_PATH_LENGTH_EXCEEDED`` is caused by a path length constraint in a basic constraint extension of one of your certificates, https://tools.ietf.org/html/rfc5280#section-4.2.1.9

**Comment by Fethbita** [comment]
Ah I understand. I have CSCA certificates and link certificates between those. Each certificate contains 
```
X509v3 Basic Constraints: critical
    CA:TRUE, pathlen:0
```
extension. If I don't include the link certificates, things work smoothly. Here is a little demo I created. (https://github.com/Fethbita/pyopenssl_link_certificate_test) In this case it requires me to remove the link certificates but I have a big bundle of certificates and it might be hard to remove the link certificates. Is there any way to complete the verification even if I have link certificates?
