### ISSUE TITLE
suggestion to enable github discussions

### ISSUE THREAD

**Issue by feenes** [pyca/pyopenssl#1008]
github has a rather new feature which can be enabled on a repository basis. It is called discussions.

Discussions allows to discuss about the project.

This would allow to discuss things, which are not necessarily issues.

If you think this could be a good idea, but you don't find how / where to enable it I can look it up and tell you.

**Comment by reaperhulk** [comment]
The unfortunate reality is that those of us maintaining pyOpenSSL don't have the time or energy to moderate or maintain a forum like this and its presence inside the project namespace would make us feel responsible for the content. StackOverflow is a better venue for questions. Thank you for the suggestion though.
