### ISSUE TITLE
Broken `OpenSSL.SSL.Context` autoclass in Sphinx docs

### ISSUE THREAD

**Issue by webknjaz** [pyca/pyopenssl#1012]
I noticed this once Cheroot strict docs builds started failing. Basically, our site uses
```rst
:py:class:`SSL.Context <pyopenssl:OpenSSL.SSL.Context>`
```
and it now fails to resolve.

Here are all the objects currently exposed via intersphinx: https://webknjaz.github.io/intersphinx-untangled/www.pyopenssl.org/

After not seeing `OpenSSL.SSL.Context` there I went to RTD and noticed that the section is empty at https://www.pyopenssl.org/en/latest/api/ssl.html#context-objects but the rst file (https://github.com/pyca/pyopenssl/blob/main/doc/api/ssl.rst#context-objects) hasn't been changed recently.

Docs for v20.0.1 have `OpenSSL.SSL.Context` documented @ https://www.pyopenssl.org/en/20.0.1/api/ssl.html#context-objects and stable does too (https://www.pyopenssl.org/en/stable/api/ssl.html#context-objects) but `latest` has it missing.

I haven't tracked down what happened but I can say that our builds first started failing on Feb 26: https://github.com/cherrypy/cheroot/runs/1989711721?check_suite_focus=true. So this happened about that time.

P.S. Oh, and I just noticed that `OpenSSL.SSL.Connection` has the same problem.

**Comment by facutuesca** [comment]
This was fixed at some point in the past. The reported sections:
- [`OpenSSL.SSL.Connection`](https://www.pyopenssl.org/en/latest/api/ssl.html#connection-objects)
- [`OpenSSL.SSL.Context`](https://www.pyopenssl.org/en/latest/api/ssl.html#context-objects)

look correct in the latest version of the generated docs.

This can be closed @mhils
