### ISSUE TITLE
merge types-pyopenssl into pyopenssl

### ISSUE THREAD

**Issue by graingert** [pyca/pyopenssl#1032]
It would be useful to merge the types-pyopenssl into pyopenssl.

It could start by just pasting the .pyi files into the repo and running check-stubs, but could also be iteratively improved to use inline type annotations and mypy type checking

See also https://github.com/twisted/twisted/pull/1484#issuecomment-890476456

**Comment by adiroiban** [comment]
Thanks.
I think that an initial .pyi import would help...as is better to have them available by default with the openssl package.

**Comment by graingert** [comment]
And running the stubcheck here found an annotation bug!

**Comment by alex** [comment]
Now that we've dropped py2, we'd rather just integrate types directly into the code, not import the stubs.

**Comment by lovetox** [comment]
Hi, i don’t think merging the pyi files is worth it, the project code base is really small.

Would a PR be appreciated? I could work on that.

**Comment by reaperhulk** [comment]
We'd be happy to take PRs for inline typing. I'd suggest submitting it as incremental PRs: first adding a CI job with mypy + config and then a series of PRs adding types (and updating the config to remove exclusions, etc) until it's complete.
