### ISSUE TITLE
custom oid for signing algorithm

### ISSUE THREAD

**Issue by sinu** [pyca/pyopenssl#1035]
is it possible to use custom OIDs for signing algorithms in openssl , i have uploaded a sample certificate which is using a custom private oid and this oid is mapped with ed25519ph. how this is possible using openssl, is there any other ca which is supporting this custom method?

![image](https://user-images.githubusercontent.com/1231202/128191522-1f384349-5e3b-49ef-bdb2-057ae46e24ea.png)

**Comment by reaperhulk** [comment]
pyOpenSSL and cryptography do not directly support this, no. You can, of course, build your own ASN.1 structures, sign the hash using cryptography, and embed whatever OIDs you want, but that requires a good working understanding of the DER ASN.1 that makes up X509 certificates.
