### ISSUE TITLE
get_shutdown not properly working?

### ISSUE THREAD

**Issue by bortzmeyer** [pyca/pyopenssl#1063]
In a TLS client, I observe that, after a `session.shutdown()`, `session.get_shutdown()` returns 1 (shutdown sent, no shutdown received). But OpenSSL on the command line with the same server show me that the server does send a close_notify:

```
<<< TLS 1.3 [length 0001]
    15
<<< TLS 1.3, Alert [length 0002], warning close_notify
    01 00
closed
```

I see in https://www.openssl.org/docs/man1.1.1/man3/SSL_get_shutdown.html that OpenSSL's `get_shutdown` can return 1 if we do not wait the close_notify from the server but, here, it is sent before my client sends its own shutdown.

The bug (?) comes from https://framagit.org/bortzmeyer/agunua/-/issues/50 Agunua is a Gemini client, available at 
https://framagit.org/bortzmeyer/agunua/ A full test is:

```

% ./agunua gemini://gemini.bortzmeyer.org/doesnotexist
get_shutdown returns: 1
Warning, no TLS shutdown received from the server
Problem, Not found (extra message: "File not found").

% printf "gemini://gemini.bortzmeyer.org/doesnotexist\r\n" |  openssl s_client -ign_eof -msg -connect gemini.bortzmeyer.org:1965
read R BLOCK
<<< ??? [length 0005]
    17 03 03 00 24
<<< TLS 1.3 [length 0001]
    17
51 File not found
<<< ??? [length 0005]
    17 03 03 00 13
<<< TLS 1.3 [length 0001]
    15
<<< TLS 1.3, Alert [length 0002], warning close_notify
    01 00
closed
>>> ??? [length 0005]
    17 03 03 00 13
>>> TLS 1.3 [length 0001]
    15
>>> TLS 1.3, Alert [length 0002], warning close_notify
    01 00
...


```

**Comment by facutuesca** [comment]
I can't reproduce this using a normal TLS client to connect to www.microsoft.com:
```python
from OpenSSL import SSL
import socket
import time

ctx = SSL.Context(SSL.TLS_CLIENT_METHOD)
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

connection = SSL.Connection(ctx, s)
connection.setblocking(True)
connection.set_tlsext_host_name(b"www.microsoft.com")
connection.connect(("www.microsoft.com", 443))
connection.do_handshake()

shutdown_result = connection.shutdown()
while not shutdown_result:
    print("close alert not yet received, waiting 1s")
    time.sleep(1)
    shutdown_result = connection.shutdown()

print(f"get_shutdown result: {bin(connection.get_shutdown())}")
print(f"SSL_RECEIVED_SHUTDOWN | SSL_SENT_SHUTDOWN value: {bin(SSL.RECEIVED_SHUTDOWN | SSL.SENT_SHUTDOWN)}")
```

Results in:
```
$ python test.py
close alert not yet received, waiting 1s
get_shutdown result: 0b11
SSL_RECEIVED_SHUTDOWN | SSL_SENT_SHUTDOWN value: 0b11
```

So `get_shutdown` does return `SSL_RECEIVED_SHUTDOWN | SSL_SENT_SHUTDOWN` after waiting for the server to respond. 

Looking at the [relevant code in the linked project](https://framagit.org/bortzmeyer/agunua/-/blob/42c98ba463d5b7df26e674705e512315af5c5fdb/Agunua/__init__.py#L531-546), it looks like the client is calling `shutdown()` once, without waiting to receive the `close_notify` alert. In that scenario, it is expected that `get_shutdown` will only return `SSL_SENT_SHUTDOWN`. See the [Shutdown Lifecycle](https://www.openssl.org/docs/manmaster/man3/SSL_shutdown.html#:~:text=fully%20standards%20compliant.-,Shutdown%20Lifecycle,-Regardless%20of%20whether) section of the OpenSSL docs:

> (...) a call to SSL_shutdown() will return firstly once a close_notify alert message is written to the peer (returning 0), and upon a second and subsequent call, once a corresponding message is received from the peer
> (...)
> An application can then detect completion of the shutdown process by calling SSL_shutdown() again repeatedly until it returns 1, indicating that the shutdown process is complete (with a close_notify alert having both been sent and received).


@alex @mhils I think this one can be closed

**Comment by mhils** [comment]
Thanks for all the issue triage, @facutuesca! 😃  🍰
