### ISSUE TITLE
Can't create Context using PyOpenSSL 21.0.0 with openssl 3.0.1

### ISSUE THREAD

**Issue by janssen70** [pyca/pyopenssl#1076]
In this setup:
$ python3 -m OpenSSL.debug
pyOpenSSL: 21.0.0
cryptography: 36.0.1
cffi: 1.15.0
cryptography's compiled against OpenSSL: OpenSSL 3.0.1 14 Dec 2021
cryptography's linked OpenSSL: OpenSSL 3.0.1 14 Dec 2021
Python's OpenSSL: OpenSSL 3.0.1 14 Dec 2021
Python executable: /usr/local/bin/python3
Python version: 3.9.10 (main, Jan 18 2022, 13:27:17)
[GCC 4.9.2]
Platform: linux

Which looks reasonable to me but when I do this:
$ python3 -i
>>> from OpenSSL.SSL import TLSv1_METHOD, Context
>>> Context(TLSv1_METHOD)

I get:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/OpenSSL/SSL.py", line 668, in __i
    _openssl_assert(context != _ffi.NULL)
  File "/usr/local/lib/python3.9/site-packages/OpenSSL/_util.py", line 71, in op
    exception_from_error_queue(error)
  File "/usr/local/lib/python3.9/site-packages/OpenSSL/_util.py", line 57, in ex
    raise exception_type(errors)
OpenSSL.SSL.Error: [('', '', '')]

I compiled openssl 3.0.1 and python myself
cryptography was built during pip install, after installing Rust
Is openssl 3.0.1 supported?

Thanks
Erik

**Comment by janssen70** [comment]
Sorry, supported versions are clearly documented: https://www.pyopenssl.org/en/stable/install.html
So that's a no
Can we expect it to come?

**Comment by janssen70** [comment]
Unfortunately when I build against openssl 1.1.1m I get the same error as above.
cryptography 36.0.1 is supposed to work with openssl 1.1.1m
So it must be something platform specific

$  python3 -m OpenSSL.debug
pyOpenSSL: 21.0.0
cryptography: 36.0.1
cffi: 1.15.0
cryptography's compiled against OpenSSL: OpenSSL 1.1.1m  14 Dec 2021
cryptography's linked OpenSSL: OpenSSL 1.1.1m  14 Dec 2021
Python's OpenSSL: OpenSSL 1.1.1m  14 Dec 2021
Python executable: /usr/local/bin/python3
Python version: 3.9.10 (main, Jan 19 2022, 14:33:07)
[GCC 4.9.2]
Platform: linux

**Comment by tiran** [comment]
What Linux distribution are you using?

**Comment by janssen70** [comment]
$ uname -a
Linux EmvloNAS-1 4.4.218.alpine.1 #1 SMP Tue May 25 00:42:02 UTC 2021 armv7l GNU/Linux

**Comment by janssen70** [comment]
forgot:
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian

**Comment by janssen70** [comment]
Fixed multiple things...
The problem on commandline was specific for the commandline tool
strace showed the old openssl is loaded as well when running the python code
Had to build a static wheel for cryptopgraphy as explained here: https://cryptography.io/en/latest/installation/
