### ISSUE TITLE
Inconsistent param type for digest

### ISSUE THREAD

**Issue by lovetox** [pyca/pyopenssl#1077]
Hi,

Not a real big issue but something i found while looking at the code

Seems all digest need to be passed as `str` and get then converted to `bytes`
except for the CRL class, where we need to pass it as `bytes`

Maybe something to consider when there is a major version with other breaking changes?

or to stay backwards compatible something like

```python
if isinstance(digest, str):
    digest = _byte_string(digest)
```

could be added.

**Comment by facutuesca** [comment]
A good point, however the `CRL` class is being [deprecated](https://github.com/pyca/pyopenssl/blob/main/CHANGELOG.rst#deprecations), so it's a moot point at this time.
@mhils I think this one can be closed.
