### ISSUE TITLE
Question regarding X509.__getattr__() 

### ISSUE THREAD

**Issue by lovetox** [pyca/pyopenssl#1085]
Hi,

On my journey to add inline type annotations i came across this code

 `crypto.py`

```python
class X509Name(object):
    ...
    def __getattr__(self, name):
        ...
            try:
                _raise_current_error()
            except Error:
                pass
            return super(X509Name, self).__getattr__(name)
```

`object` does not have a `__getattr__()` method

Is there something going on i don’t see here?

It does not make much sense for me to call this, because `__getattr__()` gets only called if there is no attribute found on the obj or any of its subclasses, so why would some default impl on object suddenly find something.

**Comment by lovetox** [comment]
A minimal example shows this failing at runtime

```python
from OpenSSL.crypto import X509

name = X509().get_subject()
print(name.a)
```
yields

```
Traceback (most recent call last):
  File "/home/lovetox/projects/tests/convert.py", line 15, in <module>
    print(name.a)
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 612, in __getattr__
    return super(X509Name, self).__getattr__(name)
AttributeError: 'super' object has no attribute '__getattr__'
```

I would suggest just calling `raise AttributeError("No such attribute")`

**Comment by alex** [comment]
This makes sense to me.
