### ISSUE TITLE
ARM / Raspberry Pi Compatibility

### ISSUE THREAD

**Issue by infosisio** [pyca/pyopenssl#1106]
I am sorry if this is stated somewhere but I was not able to find it, is pyopenssl compatible with ARM / Raspberry pi when installed from pip?

**Comment by alex** [comment]
Yes. pyOpenSSL is an entirely pure python package, it relies on pyca/cryptography which is tested on arm64 CPUs and we ship official arm64 wheels. We do not currently test on arm32, but it's my understanding that it's known to work there as well.
