### ISSUE TITLE
LICENSE file doesn't specify copyright holder or year

### ISSUE THREAD

**Issue by Hnasar** [pyca/pyopenssl#111]
From LICENSE:
      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.

   Copyright [yyyy] [name of copyright owner]

**Comment by hynek** [comment]
The part doesn’t apply to the LICENSE file itself but to file headers which are impossible to harmonize without the help of a lawyer so we’ll just leave it as it is for now. :(
