### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

### ISSUE THREAD

**Issue by mvellasco** [pyca/pyopenssl#1114]
Importing the `crypto` module from OpenSSL throws an AttributeError. This is happening under version 20.0.1 of the library.

```
File "/usr/local/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
  from OpenSSL import crypto, SSL
File "/usr/local/lib/python3.8/site-packages/OpenSSL/crypto.py", line 1556, in <module>
     class X509StoreFlags(object):
File "/usr/local/lib/python3.8/site-packages/OpenSSL/crypto.py", line 1577, in X509StoreFlags
     CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```

**Comment by alex** [comment]
Can you provide instructinos for reproducing this from a clean environment?

I strongly suspect you are mixing incompatible versions of pyOpenSSL and cryptography and one/both of them should be upgraded.

**Comment by mvellasco** [comment]
Doing `pip install pyopenssl==20.0.1` alone and them going to the terminal and trying the import above gives the error for me. I'll check my version of cryptography as well to see if that's the issue.

**Comment by alex** [comment]
You'll need to use a more recent pyopenssl version, or pin to an older cryptography version.

**Comment by mvellasco** [comment]
Downgrading cryptography worked like a charm. Thank you very much @alex !

**Comment by reaperhulk** [comment]
For those seeing this issue: You can upgrade `pyOpenSSL` to latest to resolve it or downgrade `cryptography`, but the latter is not a good long term solution since you will (of course) not receive security updates.

**Comment by reaperhulk** [comment]
We re-added some symbols in 37.0.1 to minimize breakage. We still encourage users to upgrade to the latest pyOpenSSL as these will be removed again in a future release.
