### ISSUE TITLE
https://pypi.org/project/pyOpenSSL/json infinite redirect loop

### ISSUE THREAD

**Issue by frostyslav** [pyca/pyopenssl#1128]
https://pypi.org/project/pyOpenSSL/json goes to infinite redirect loop.
```
curl -L https://pypi.org/pypi/pyOpenSSL/json
curl: (47) Maximum (50) redirects followed
```

**Comment by maartenvanderhoef** [comment]
same here

**Comment by alex** [comment]
this is a pypi issue, which I assume is caused by https://github.com/pypa/warehouse/commit/f7f48cb7fd58e08c1f8beba3846569e074e0b297

Plesae file a bug on warehouse.
