### ISSUE TITLE
multiple OUs in a X509Name

### ISSUE THREAD

**Issue by calestyo** [pyca/pyopenssl#1135]
Hey.

I need to generate a CSR with multiple `OU` fields, however, it seems on `crypto.X509Req().get_subject()` I could set only one `OU`.

Any ideas?

Thanks,
Chris

**Comment by alex** [comment]
If at all possible we recommend using pyca/cryptography for X.509 CSR generation, as it is considerably more flexible: https://cryptography.io/en/latest/x509/tutorial/#creating-a-certificate-signing-request-csr

**Comment by calestyo** [comment]
Hey Alex.

Not sure what you mean with “at all”… from the X.509 side this should work.

Isn't there any way to get this into pyOpenSSL (e.g. simply interpreting an array value to be multiple `OU`s, etc.)?

Cheers,
Chris.

**Comment by alex** [comment]
pyOpenSSL's APIs are very poorly designed -- even as a maintainer I do not know if multiple values for the same NameAttribute are well supported.

For this reason we strongly recommend using pyca/cryptography instead. If you are using a recent version of pyOpenSSL you will already have pyca/cryptography installed.

**Comment by calestyo** [comment]
Guess
