### ISSUE TITLE
CB_ISSUER_CHECK Error

### ISSUE THREAD

**Issue by sivagopal** [pyca/pyopenssl#1142]
Hi The application was working ok with PyOpenSSL 18.0.0 version so far, however we suddenly went into an issue as module lib has no attribute X509_V_FLAG_GB_ISSUER_CHECK

**Comment by alex** [comment]
Did you upgrade the version of pyca/cryptography you use? If so, did you read the changelog? https://cryptography.io/en/latest/changelog/#v38-0-0

> Removed several legacy symbols from our OpenSSL bindings. Users of pyOpenSSL versions older than 22.0 will need to upgrade.
