### ISSUE TITLE
deprecated() got an unexpected keyword argument 'name' 

### ISSUE THREAD

**Issue by yagodorea** [pyca/pyopenssl#1151]
Started getting this error today after release 22.1.0:

```log
[...]
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/crypto.py", line 3224, in <module>
    utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument 'name'
```

**Comment by alex** [comment]
What version of cryptography do you have installed?

**Comment by yagodorea** [comment]
> cryptography

36.0.2

**Comment by alex** [comment]
I'm not sure how you installed pyOpenSSL, but 22.1.0 has a minimum requirement of cryptography 38.

**Comment by yagodorea** [comment]
My dependency chain is `snowflake-sqlalchemy->snowflake-connector-python->pyopenssl`. It updated to 22.1.0 automatically, without changing criptography version... Will try to understand why, thanks!

**Comment by aisk** [comment]
@yagodorea You can try to run `pip check` to see if there were some dependencies versions conflicts.
