### ISSUE TITLE
AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv2_METHOD'

### ISSUE THREAD

**Issue by Nico-Guyon** [pyca/pyopenssl#1152]
Hi,

I have a strange problem if I use the new version pyOpenSSL 22.1.0.
I keep getting the following error : AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv2_METHOD'

I switched back my Pipfile files to pyopenssl 22.0.0 and it's working correctly again.

Are you aware of such problem ?
What could be the cause and would you have some advices on what to do ?

Thanks for your help !

**Comment by mhils** [comment]
As mentioned in the changelog, support for SSLv2/SSLv3 has been removed.

**Comment by Nico-Guyon** [comment]
Ok, thanks for your fast answer.
