### ISSUE TITLE
22.1.0 UNRELEASED is released

### ISSUE THREAD

**Issue by CalebSchwartz** [pyca/pyopenssl#1153]
Hi - looking at the changelog for 22.1.0 and noticing it says unreleased yet appears to have been released yesterday. 
https://www.pyopenssl.org/en/stable/changelog.html
https://pypi.org/project/pyOpenSSL/#history

**Comment by alex** [comment]
this was fixed in https://github.com/pyca/pyopenssl/commit/7abe40cbff2b30f6b5d59b5a1106b7a6a237df86
