### ISSUE TITLE
unexpected exception thorwn by verify_certificate

### ISSUE THREAD

**Issue by caoyebo** [pyca/pyopenssl#1155]
Hi,

I ran the verify_certificate function against "wrong.host.badssl.com" but it throwed the exception "certificate has expired", which seems to be inconsistent with its actual expiration date (Thursday, November 10, 2022 at 6:57:45 AM)

May I know the reason of this behavior?

Thanks.

**Comment by alex** [comment]
you didn't set SNI, so you got the fallback cert.
