### ISSUE TITLE
Should pyOpenSSL warn/error when callers attempt to use EC keys with OpenSSL 0.9.8?

### ISSUE THREAD

**Issue by posita** [pyca/pyopenssl#116]
This bit me when using MacPorts on OS X, which comes with `OpenSSL` 0.9.8 installed. Here's what I did:

```
% port install openssl pypy virtualenv27
...
% port list openssl
openssl                        @1.0.1g         devel/openssl
% virtualenv-2.7 --python=pypy foo
% ./foo/bin/pip install pyOpenSSL
...
```

SSL connections would die without fuss from [a simple test server](http://paste.pound-python.org/show/7wnTha10BLVrAH7I1tic/) when using an EC key pair (e.g., this self-signed test [key](http://paste.pound-python.org/show/Q3LboiMCm6sN8Ydv37Rc/) and [crt](http://paste.pound-python.org/show/yFBEdKWFlGi12rpfP3D0/)):

```
% ./foo/bin/python test.py &
% curl --verbose -k 'https://127.0.0.1:4443/'
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 4443 (#0)
* successfully set certificate verify locations:
*   CAfile: .../share/curl/curl-ca-bundle.crt
  CApath: none
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS alert, Server hello (2):
* error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
* Closing connection 0
curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

This didn't happen when using RSA key pairs. With the help of kind folks on `#cryptography-dev`, I learned that `cryptography` was linking against the wrong version of `OpenSSL`:

```
% ./foo/bin/python -c 'from OpenSSL.SSL import SSLEAY_VERSION, SSLeay_version ; print(SSLeay_version(SSLEAY_VERSION))'
OpenSSL 0.9.8y 5 Feb 2013
```

There is [a fix](https://cryptography.io/en/latest/installation/#using-your-own-openssl-on-os-x) (i.e., a manual `pip install cryptography` that forces building against the right version). However, what would have been extremely helpful is if `pyOpenSSL` (or perhaps `cryptography`, I don't know the best place) raised an exception to callers who try using EC key pairs with `OpenSSL` 0.9.8 (where EC is apparently broken).

**Comment by alex** [comment]
0.9.8 isn't a thing anymore.
