### ISSUE TITLE
Openssl warns critical security vulnerability

### ISSUE THREAD

**Issue by saurabhlime** [pyca/pyopenssl#1160]
Open SSL will release a patch of a critical vulnerability on Nov 1. How can we update pyopenssl to use this patched version of OpenSSL?
https://www.zdnet.com/article/openssl-warns-of-critical-security-vulnerability-with-upcoming-patch/

**Comment by mhils** [comment]
pyOpenSSL does not include OpenSSL itself. Instead, it depends on the OpenSSL version bundled with the [cryptography package](https://github.com/pyca/cryptography/). Long story short, you likely need to update cryptography tomorrow.

**Comment by alex** [comment]
pyOpenSSL consumes openssl via the cryptography package.

If you install cryptography from a wheel you'll need to update when we
issue a release tomorrow.

If you install from an sdist you'll need to update your openssl from
wherever you get it from.

**Comment by saurabhlime** [comment]
Thanks for the clarification. I will keep an eye out for tomorrow.
