### ISSUE TITLE
Is  this lib can be used to convert pkcs8 key to pkcs1 key?

### ISSUE THREAD

**Issue by w-Bro** [pyca/pyopenssl#1162]
like openssl command
```
openssl rsa -pubin -in public_pkcs8.pem -RSAPublicKey_out -out public_pkcs1.pem
```

**Comment by mhils** [comment]
See the README:

> **Note:** The Python Cryptographic Authority **strongly suggests** the use of `pyca/cryptography`_
where possible. If you are using pyOpenSSL for anything other than making a TLS connection
**you should move to cryptography and drop your pyOpenSSL dependency**.

The cryptography library should be able to do what you want. :)
