### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by pigletfly** [pyca/pyopenssl#117]
distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

I am using ubuntu 13.10

**Comment by hao89** [comment]
thanks a lot!

**Comment by tarasinf** [comment]
thanks

**Comment by critikaster** [comment]
Thanks, fixed similar issue for me on Ubuntu 14.04.3 LTS
