### ISSUE TITLE
how do I do like these 2 commands with pyopenssl?

### ISSUE THREAD

**Issue by ironmantonystark** [pyca/pyopenssl#1183]
openssl rsa -outform der -in privkey.pem -out privkey.key
openssl x509 -outform der -in cert.pem -out cert.crt

ty so much <3 if you answered my question
I tried Google it, there's nothing I wanted, I looked for pretty much every links there

**Comment by alex** [comment]
We strongly recommend using pyca/cryptography, and not pyopenssl for tasks like this.

Key serialization is documented here: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/

X.509 is documented here: https://cryptography.io/en/latest/x509/reference/

**Comment by ironmantonystark** [comment]
ty so much I gonna try cryptography

**Comment by ironmantonystark** [comment]
it's so nice of you

**Comment by ironmantonystark** [comment]
<3 <3 <3
