### ISSUE TITLE
Pip dependency resolver is installing not compatible cryptography versions for pyOpenSSL

### ISSUE THREAD

**Issue by legitYosal** [pyca/pyopenssl#1184]
Hi
Steps to reproduce:
```
sudo apt install python3-pip
python3 -m pip install paramiko # as you can see paramiko is a very common package
pip freeze # => this is returned with error
```
Installing old pyOpenSSL versions has no upper limit on version of cryptography package, so for example it will install pyOpenSSL 19 by default and then installing cryptography version > 30-38 will result in error although paramiko only required `cryptography>=3.3` so if pyOpenSSL version 19 had an upper limit for example `cryptography>2.6<=3.3` it would have no error and would live on harmony or at least would show the uncompatible error.
Is there anyway to update pip dependency resolver on old versions and fix this issue?
and please fix this issue on future releases

related issue on pip: https://github.com/pypa/pip/issues/11795

**Comment by alex** [comment]
Unfortunately there's not much we can do. Recent versions of pyopenssl include version bounds on cryptography to prevent this.

Installing in a virtualenv should prevent this.
