### ISSUE TITLE
Version 23.0.0 required Cryptography x509 but in Cryptography version 39 doesn't have the module

### ISSUE THREAD

**Issue by david2003542** [pyca/pyopenssl#1190]
We currently receiving this error
from requests.packages.urllib3.contrib.pyopenssl import PyOpenSSLContext
No module named 'cryptography.hazmat.backends.openssl.x509

In setup.py cryptography dependency is lower than 40 however in version 39 of cryptography doesn't have x509 support
`install_requires=[
            # Fix cryptographyMinimum in tox.ini when changing this!
            "cryptography>=38.0.0,<40",
        ],`

**Comment by alex** [comment]
What version of requests and urllib3 are you using?

**Comment by david2003542** [comment]
Hi Alex thanks for reply. I am currently using requests 2.28.2

**Comment by david2003542** [comment]
Sorry I just check in more deep the code I pasted was from request_pkcs12.py apparantly the version I have is out of date

**Comment by david2003542** [comment]
I will try thanks @alex
