### ISSUE TITLE
TypeError: deprecated() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by Meghana-Naik-Nice** [pyca/pyopenssl#1195]
Using the following library versions:
snowflake-connector-python==3.0.1
cryptography==39.0.2
pyopenssl==23.0.0
chalice==1.26.4

Getting the below error:
TypeError: deprecated() got an unexpected keyword argument 'name'

**Comment by reaperhulk** [comment]
Please provide a reproducer in a fresh virtual environment and a full stack trace to help us debug.

**Comment by Meghana-Naik-Nice** [comment]
import snowflake.connector", 
from .connection import SnowflakeConnection", 
"  File \"<<Path>>/snowflake/connector/connection.py\", line 27, in <module>", "    from . import errors, proxy", 
"  File \"\<<Path>>/snowflake/connector/errors.py\", line 18, in <module>", "    from .telemetry_oob import TelemetryService", " 
 File \"<<Path>>/snowflake/connector/telemetry_oob.py\", line 21, in <module>", "    from .vendored import requests", " 
 File \"<<Path>>/snowflake/connector/vendored/requests/__init__.py\", line 119, in <module>", "    from ..urllib3.contrib import pyopenssl", " 
 File \"<<Path>>/snowflake/connector/vendored/urllib3/contrib/pyopenssl.py\", line 50, in <module>", "    import OpenSSL.SSL", " 
 File \"<<Path>>/OpenSSL/__init__.py\", line 8, in <module>", "    from OpenSSL import SSL, crypto", " 
 File \"<<Path>>/OpenSSL/SSL.py\", line 19, in <module>", "    from OpenSSL.crypto import (", "  
File \"<<Path>>/OpenSSL/crypto.py\", line 3261, in <module>", "    name=\"load_pkcs7_data\",", "TypeError: deprecated() got an unexpected keyword argument 'name'"

**Comment by reaperhulk** [comment]
Thank you for the stack trace, but you still haven't provided a mechanism to reproduce this error. The stack you've provided strongly suggests that your code is not importing the version of cryptography you think you're importing as `deprecated` has the `name` kwarg in 37+, but not earlier versions.
