### ISSUE TITLE
NetscapeSPKI doesn't take an argument

### ISSUE THREAD

**Issue by lvh** [pyca/pyopenssl#124]
This is a discrepancy I found while trying to improve the documentation.

Docs state:

``` rst
.. py:class:: NetscapeSPKI([enc])

    A class representing Netscape SPKI objects.

    If the *enc* argument is present, it should be a base64-encoded string
    representing a NetscapeSPKI object, as returned by the :py:meth:`b64_encode`
    method.
```

But! No: https://github.com/pyca/pyopenssl/blob/master/OpenSSL/crypto.py#L1998

I don't know if this was introduced with the FFI change or if the documentation was never accurate...

**Comment by alex** [comment]
Was fixed at some point.
