### ISSUE TITLE
Implement PyOpenSSL deprecated functions as calls into Cryptography library

### ISSUE THREAD

**Issue by justineakehurst** [pyca/pyopenssl#1270]
Given that the first thing I see when I come to this Github project is this note:

> Note: The Python Cryptographic Authority strongly suggests the use of [pyca/cryptography](https://github.com/pyca/cryptography) where possible. If you are using pyOpenSSL for anything other than making a TLS connection, you should move to cryptography and drop your pyOpenSSL dependency.

Would it make sense to implement PyOpenSSL function calls to internally use Cryptography library function calls, and ideally avoid the use of the `hazmat` low-level function calls?

This could be a way to provide a supported migration path to move folks off of using PyOpenSSL and towards a pure use of the public API calls in the Cryptography library, which would then lead to a clean deprecation roadmap of this library and its eventual removal from use.

**Comment by alex** [comment]
Unfortunately, the pyOpenSSL APIs tend to be very badly designed, and therefore don't lend themselves to being implemented on top of pyca/cryptography's better APIs.

**Comment by justineakehurst** [comment]
> Unfortunately, the pyOpenSSL APIs tend to be very badly designed, and therefore don't lend themselves to being implemented on top of pyca/cryptography's better APIs.

Given this information, what guidance can you give folks on a method-by-method basis to migrate themselves over to the Cryptography library?

**Comment by alex** [comment]
I would suggest folks identify what features of pyOpenSSL they are using, and particularly the "edges" of their usage (e.g., loading keys from disk), and then identify the equivilant functionality in pyca/cryptography and migrate to it.

In some cases, pyOpenSSL also offers `to_cryptography()` methods on various types (e.g., X509 certificates) that can be used for partial migrations.
