### ISSUE TITLE
RemoveError: 'pyopenssl' is a dependency of conda and cannot be removed from conda's operating environment.

### ISSUE THREAD

**Issue by karami-omid** [pyca/pyopenssl#1277]
I have error when trying to update conda.

RemoveError: 'pyopenssl' is a dependency of conda and cannot be removed from
conda's operating environment.

Thanks for your support!

**Comment by alex** [comment]
This is a question for the conda developers, we cannot provide support for conda.

**Comment by karami-omid** [comment]
Thanks for your response.
