### ISSUE TITLE
[docs] Use Furo?

### ISSUE THREAD

**Issue by webknjaz** [pyca/pyopenssl#1286]
Some update to the RTD setup switched the theme from RTD to Alabaster (in between v23.2.0 and 23.3.0). See https://www.pyopenssl.org/en/23.3.0/ vs. https://www.pyopenssl.org/en/23.2.0/.

Maybe, it's time to take this chance to pin the deps and start using Furo?

**Comment by alex** [comment]
We're back to using the RTD theme. For now, I don't think we want to make changes here.
