### ISSUE TITLE
pip install  leads to buggy installation

### ISSUE THREAD

**Issue by sbose78** [pyca/pyopenssl#130]
1 ) 

When I do a pip install pyopenssl==0.14 
I get a buggy installation causing this error on module import

"AttributeError: 'FFILibrary' object has no attribute 'SSL_OP_NO_TICKET'"

I checked  https://pypi.python.org/pypi/pyOpenSSL/0.14, 
This shows me the source code link same as the one here on github.

I checked the installed SSL.py file on my environment , the exception handling block for  SSL_OP_NO_TICKET was missing ( I can see it's there on github )

2) 

I install using the tar from github by doing a setup.py install
Things work good !

Issue:
Is the version build 0.14 published to the repo different than that found here on github ? 
( I see there are no commits post the 0.14 release )

**Comment by amorphic** [comment]
Any chance of a new release (0.14.1?) any time soon? This bug is biting me and it'd be nice to be able to include a dependency on a prod version of pyOpenSSL in my project rather than requiring users to clone master and install that instead.

**Comment by exarkun** [comment]
I'm going to try really hard to have a 0.15 release early next week.

**Comment by amorphic** [comment]
:+1: Awesome, thanks :)
