### ISSUE TITLE
How to decrypt openSSL PKCS#7

### ISSUE THREAD

**Issue by Diogoku** [pyca/pyopenssl#1312]
Hello, 

Is there a way in pyopenssl to decrypt a file encrypted by openSSL with PKCS7? If so can you point me to the method I should use on pyopenssl?

Thank you in advance

**Comment by alex** [comment]
No, we don't currently have support for decrypting PKCS7 blobs.

**Comment by Diogoku** [comment]
Thank you! Do you know any python library that supports it?
