### ISSUE TITLE
How to add Certificate Policies extension using pyopenssl

### ISSUE THREAD

**Issue by dulanshuangqiao** [pyca/pyopenssl#1365]
I try like this：
def add_certificate_policies_extension(cert):
    # 使用标准策略 OID anyPolicy (2.5.29.32.0)
    policy_oid = '2.5.29.32.0'

    # 创建证书策略扩展，确保传递值为字节类型
    cert_policies_extension = crypto.X509Extension(
        b"certificatePolicies",
        critical=False,
        value=policy_oid.encode('ascii')
    )

    # 将扩展项添加到证书
    cert.add_extensions([cert_policies_extension])
But, error like this:
[('X509 V3 routines', '', 'no config database'), ('X509 V3 routines', '', 'error in extension')]

**Comment by alex** [comment]
The X.509 API in pyopenssl is deprecated. Users are encouraged to use cryptography's X.509 API instead https://cryptography.io/en/latest/x509/
