### ISSUE TITLE
"import OpenSSL" is 150x slower in 0.14

### ISSUE THREAD

**Issue by kmike** [pyca/pyopenssl#137]
Hi,

With latest released pyopenssl, cryptography and cffi "import OpenSSL" takes about 0.5s on a modern i7 CPU with SSD (OS X):

```
In [1]: %time import OpenSSL
CPU times: user 496 ms, sys: 19.7 ms, total: 516 ms
Wall time: 511 ms
```

It used to be *much* faster in pyOpenSSL 0.13.1:
```
In [1]: %time import OpenSSL
CPU times: user 1.45 ms, sys: 1.81 ms, total: 3.26 ms
```

Twisted uses OpenSSL, so 0.5s is a startup delay that every Twisted-based software started to pay. It is quite noticable for command-line tools (e.g. Scrapy command line script).

The main contributor to this is cryptography's build_ffi function which uses cffi. I'm not sure how to fix that.

**Comment by rabbbit** [comment]
cffi is currently at 1.1.1 and the import overhead is still present. I guess upgrading to 2.7.10 is the way :)

**Comment by hynek** [comment]
The overhead won't go magically away.  We need a cryptography release with pyca/cryptography#1986 first.

**Comment by reaperhulk** [comment]
@rabbbit if you build cryptography against current master you should see the import overhead disappear. We don't currently have a timeline for our next release, but history suggests it will be within the next 4 weeks.

**Comment by rabbbit** [comment]
Thank you :)

**Comment by dhermes** [comment]
@reaperhulk Do you guys have a release announce list?

**Comment by reaperhulk** [comment]
We have a generic [cryptography-dev](https://mail.python.org/mailman/listinfo/cryptography-dev) list that we do announcements on, but we also CC release announcements to [python-announce](https://mail.python.org/mailman/listinfo/python-announce-list)

**Comment by dhermes** [comment]
Thanks

**Comment by dhermes** [comment]
w00t, `cryptography` 1.9.2 was [released][1] July 3

[1]: https://pypi.python.org/pypi/cryptography/0.9.2

**Comment by reaperhulk** [comment]
@dhermes 0.9.2 won't fix this issue unfortunately. You'll have to wait for 1.0 for that. That will hopefully be in the next 2 weeks

**Comment by dhermes** [comment]
Thanks for the update

**Comment by reaperhulk** [comment]
1.0 has resolved this issue :) (but created that pypy issue for you, sorry @dhermes!)

**Comment by kmike** [comment]
\o/
