### ISSUE TITLE
X509Name memberfunction get_components() returns shortName UNDEF

### ISSUE THREAD

**Issue by crc32a** [pyca/pyopenssl#138]
And X509Name such as below will yield inconsistent results when the shortName of a Name entry is unknown between calls to member functions **str**() and get_components()

As an example:
str(x509)==
"<X509Name object '/businessCategory=Private Organization/1.3.6.1.4.1.311.60.2.1.3=US/1.3.6.1.4.1.311.60.2.1.2=Utah/serialNumber=5299537-0142/street=Suite 500/street=2600 West Executive Parkway/postalCode=84043/C=US/ST=Utah/L=Lehi/O=DigiCert, Inc./CN=www.digicert.com'>" 

Which shows the OID numbers when no shortName is found.

yet the call to 
x509.get_components() yeilds the list
[('businessCategory', 'Private Organization'), ('UNDEF', 'US'), ('UNDEF', 'Utah'), ('serialNumber', '5299537-0142'), ('street', 'Suite 500'), ('street', '2600 West Executive Parkway'), ('postalCode', '84043'), ('C', 'US'), ('ST', 'Utah'), ('L', 'Lehi'), ('O', 'DigiCert, Inc.'), ('CN', 'www.digicert.com')]

the oids are now replaced with UNDEF which is inconsistent with the repr and str methods.

proposed solution is code of the form
https://github.com/rackerlabs/pyopenssl/commit/fe138b4cc01d05b9d0320ab3c0e571daab553f12

on the show_oids_in_x509_name branch.

**Comment by alex** [comment]
We're not making any improvements to the X.509 layer of pyOpenSSL. You're encouraged to use the pyca/cryptography x509 at this point: https://cryptography.io/en/latest/x509/
