### ISSUE TITLE
X509Extension has a memory leak in its private member function _subjectAltNameString() which is publicly exposed via the member function __str__()

### ISSUE THREAD

**Issue by crc32a** [pyca/pyopenssl#139]
just calling the member method __str__() on an X509Extention instance object will trigger a memory leak when the extension is a SubjectAltName. IE when __str__() is called and the condition  if _lib.NID_subject_alt_name == self._nid triggers return self._subjectAltNameString()

proposed solution. Not sure I suspect GENERAL_NAMES_free may need to be registered as a garbage collection function at some point. I also noticed the GENERAL_NAMES_free is has no bindings in cryptography hazmat. :( Investigating.

**Comment by hynek** [comment]
Fixed via #252
