### ISSUE TITLE
Fix regressions in support for bytes / unicode in certain APIs

### ISSUE THREAD

**Issue by adiroiban** [pyca/pyopenssl#15]
In previous pyopenssl versions the API was fine with accepting strings as Unicode.

For example this was a valid code, which no longer works in latest version. Context.set_cipher_list(u'ALL')

The migration should not be a big deal, but I think that this needs to be documented.

---

Also, handling unicode paths in a cross-platform code is a bit messy since Python API on Linux sometimes accepts Unicode, sometimes byte string (depending on environment), and on Windows you always have to pass the path a Unicode.

Maybe OpenSSL.test.util.TestCase.mktemp should be changed to always return a unicode path, example via mktemp(dir='.', suffix=UNICODE_TEST_MARKER)

Thanks!

**Comment by abrahammartin** [comment]
Is 0.15 going to be release any time soon? 0.14 was released a year ago and there are a lot of bugfixes and new features added since then.

**Comment by dbrent-amazon** [comment]
I am having the same issue. http://stackoverflow.com/questions/28749543/pyopenssl-signature-verification-using-python-3

**Comment by exarkun** [comment]
> Is 0.15 going to be release any time soon?

It's on my todo list.  I had planned to do one over the holidays but got tied up with other (even less fun, I assure you) things.  I have some airport time coming up during which I intend to give this another shot.  Sorry about not getting to this more quickly.

**Comment by sgallagher** [comment]
I was just about to file this as a new bug when I stumbled upon this ticket. I'm working on a script to generate self-signed certificates and it's broken on Python 3. One thing I couldn't discern from the comments above: is there a workaround? Can I convert the strings to something else that would be accepted?

The following code works in Python 2
```python
crypto.X509Extension("subjectKeyIdentifier",
                                 False,
                                 "hash",
                                 subject=ca_cert,
                                 issuer=ca_cert)
```

However, on Python 3, it results in the error:
```
File "/usr/lib/python3.4/site-packages/OpenSSL/crypto.py", line 493, in __init__
    extension = _lib.X509V3_EXT_nconf(_ffi.NULL, ctx, type_name, value)
TypeError: initializer for ctype 'char *' must be a bytes or list or tuple, not str
```

**Comment by adiroiban** [comment]
you can try using `b"subjectKeyIdentifier"` to force bytes... similar for `b"hash"`

**Comment by exarkun** [comment]
> I was just about to file this as a new bug when I stumbled upon this ticket. I'm working on a script to generate self-signed certificates and it's broken on Python 3.

Also please note this is not a pyOpenSSL bug.  This is a Python 2 / Python 3 incompatibility.  Your program passes byte strings to the pyOpenSSL API on Python 2.  However, your program passes **unicode** strings to the pyOpenSSL API on Python 3.  The API supports byte strings.  My inclination at this point is not to change pyOpenSSL to support this usage.  Instead, if you want to port an application to Python 3, you have to fix your string usage.

**Comment by adiroiban** [comment]
At least `set_cihpher_list` was working when passed Unicode strings in Python2. In python2 I am explicitly using u'ALL' to make it an unicode string.

**Comment by exarkun** [comment]
> At least set_cihpher_list was working when passed Unicode strings in Python2.

Of course.  Python 2 will implicitly encode unicode to str for any number of reasons.  This was never intended behavior.

This isn't quite the same thing that sgallagher's comment is about.  His program passes bytes to a pyOpenSSL API on Python 2.  He can reasonably expect that passing bytes to that API on Python 3 should work.  It does not seem to me that he can reasonably expect that passing unicode to that API on Python 3 API should work.

**Comment by adiroiban** [comment]
I am +1 for updating the documentation to inform that only bytes are supported.
Later we can update separate API method to support Unicode and to write unit tests for that.

To fix this ticket I think that is ok to just add a bit warning in pyopenssl introduction that Unicode is not supported... and that Unicode which worked in py2.7 will break in py3.

**Comment by adiroiban** [comment]
I am only testing on Py 2.7

I have found another Unicode issue in crypto.X509Req() subject which ask for Unicode

Extensions are accepted with UTF-8

I have this code

```
csr = crypto.X509Req()
subject = csr.get_subject()
name = u\u20acuro-zone.com'
subject.organizationName = name.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position X: ordinal not in range(128)
```

but  will accept only accept Unicode ... not UTF-8 bytes.

Same story for commonName organizationalUnitName localityName stateOrProvinceName

countryName only accepts the hardcoded codes  so we should not care about unicode here.

`subject.emailAddress` only accepts ascii chars and fail if I sent it Unicode with non-ascii characters... but also fails if I encode them with utf-8

I am working at a python script to generate a CSR . The code and test is here https://github.com/chevah/chevah-keycert/pull/10

**Comment by exarkun** [comment]
What version of pyOpenSSL did you test this against?  master@HEAD runs this code without error.

**Comment by adiroiban** [comment]
I was testing against released version 0.13 and 0.14.

I will give it a try with master. Looking forward for 0.15 release. Thanks!

**Comment by digz6666** [comment]
Is it fixed in version 12.6.0? https://pypi.python.org/pypi/pyOpenSSL

**Comment by hynek** [comment]
This seems to have been fixed years ago.  @adiroiban can you confirm and close please?

**Comment by adiroiban** [comment]
Looks good. Thanks!
both Unicode and UTF-8 bytes are accepted
```
$ py
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from OpenSSL import crypto
>>> csr = crypto.X509Req()
>>> subject = csr.get_subject()
>>> name = 'u\u20acuro-zone.com'
>>> subject.organizationName = name.encode('utf-8')
>>> subject
<X509Name object '/O=u\u20acuro-zone.com'>
>>> subject.organizationName = name
>>> import OpenSSL
>>> OpenSSL.__version__
'16.2.0'
```
