### ISSUE TITLE
Please add extension removal capability (X509_delete_ext)

### ISSUE THREAD

**Issue by ecbftw** [pyca/pyopenssl#152]
Currently there is no way to remove an extension from a certificate or similar objects.  (Yes, I have a good reason for doing this and re-signing certificates).  OpenSSL has this capability, but it doesn't appear to be exposed by pyca/cryptography, let alone pyopenssl.  Here's the VERY hacky snippet of code I used to work around this limitation.  Feel free to use/adapt as necessary.

```
def deleteExtension(certificate, index):
    import cffi
    from cffi import FFI
    ffi = FFI()
    ffi.cdef('''void* X509_delete_ext(void* x, int loc);''')
    libssl = ffi.dlopen('libssl.so')
    ext = libssl.X509_delete_ext(certificate._x509, index)
    #XXX: supposed to free ext here
```

I think in the long run it would be far better if pyopenssl wrapped up extensions to appear as true python objects.  That is, instead of referencing extensions by some confusing C-based index value, abstract the extensions list into a proper (im)mutable sequence that we can manipulate as if it were a python list or tuple.

**Comment by alex** [comment]
Going to say this is bad idea, if you want a new cert, create a new cert object, the fact that pyOpenSSL allows mutating certs is a mistake, and we shouldn't exacerbate it.

**Comment by ecbftw** [comment]
You wait 3 years with no response, then summarily close the bug without explaining your reasoning?

Why?

Do you not support security testing?

How else would you propose a pentester to take an existing certificate, make it look *exactly* like another certificate, but then sign it with an illegitimate one?  This is how you test for security flaws in other people's validation routines.  It is actually important.  Don't give me a "guns kill people" argument; please.

PS- I'm a tad drunk at the moment, so sorry if the tone is over the top.

**Comment by Lukasa** [comment]
> PS- I'm a tad drunk at the moment, so sorry if the tone is over the top.

It is.

> How else would you propose a pentester to take an existing certificate, make it look exactly like another certificate, but then sign it with an illegitimate key? This is how you test for security flaws in other people's validation routines. It is actually important. Don't give me a "guns kill people" argument; please.

I'd probably use cryptography to do it:

```python
from cryptography import x509
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import rsa

with open('/path/to/cert', 'rb') as f:
    cert = x509.load_pem_x509_certificate(f.read(), default_backend())

# This is your bogus key: I'm just hand-generating one for now, you can
# do better in your code.
private_key = rsa.generate_private_key(
    public_exponent=65537,
    key_size=2048,
    backend=default_backend()
)

builder = x509.CertificateBuilder()
builder = builder.subject_name(cert.subject)
builder = builder.issuer_name(cert.issuer)
builder = builder.not_valid_before(cert.not_valid_before)
builder = builder.not_valid_after(cert.not_valid_after)
builder = builder.serial_number(cert.serial_number)
builder = builder.public_key(cert.public_key())

for ext in cert.extensions:
    builder = builder.add_extension(
        ext.value, critical=ext.critical
    )

new_cert = builder.sign(
    private_key=private_key, algorithm=cert.signature_hash_algorithm,
    backend=default_backend()
)
```

This will work just fine, I suspect.

**Comment by ecbftw** [comment]
Hi @Lukasa.  I appreciate the code and you taking the time to consider the problem.  And once again, sorry for the belligerence.

For your reference, the tool I developed back when I posted this bug is here:
  https://code.blindspotsecurity.com/trac/bletchley/browser/trunk/bin/bletchley-clonecertchain
  https://code.blindspotsecurity.com/trac/bletchley/browser/trunk/lib/bletchley/ssltls.py#L242

The reason I didn't take an approach similar to what you have above is that many custom "enterprise" applications include nonstandard certificate properties to help track information about the user's role, or other identifying info that is specific to the application.  Often these properties are in extensions or in the subject field, but not always. I had no way to be sure that the accessor methods pyOpenSSL exposes actually give me access to everything.  So it seemed much safer to just copy all certificate properties as a black box and then change the ones I needed to.  When you're doing MitM testing to help a developer ensure their custom certificate validation routines are safe, having every certificate property match the real certificate's properties (as much as possible) is important.

At the time, I think the `cryptography` module was barely off the ground, so it wasn't a viable candidate for use on its own.  Now I would certainly consider switching to it.  However, it isn't clear to me if my approach of copying a whole certificate and tweaking it is possible with `cryptography`.  Do you think there's a way to do this?

Finally, I'm not quite sure what the concern is about adding extension deletion functionality.  The "bad idea" mentioned sounds like a moral argument.  I can totally understand if you guys don't have time to tackle this, but closing out the request without a better explanation, particularly when OpenSSL already has an API for this, seems a little preachy... :-(  If OpenSSL has it, surely there are legitimate, non-scary use cases.

**Comment by alex** [comment]
I don't have the time to respond in full, but no, OpenSSL has tons of leglacy APIs and other APIs that are bad ideas, "because OpenSSL has it" is not evidence an API is good idea.

**Comment by reaperhulk** [comment]
@ecbftw the copying approach will work with cryptography. cryptography will parse the cert and you can pass the things you want to copy to a CertificateBuilder (calling the `set_*` methods).

**Comment by ecbftw** [comment]
@reaperhulk Hmm, I'm not sure we're on the same page. I want to start with *all* of the properties of an existing cert, and then change just the ones that are problematic for cloning a forged chain. In other words, if `CertificateBuilder` had a `load_cert()` method that let me load up everything from an existing cert in bulk, and then it had additional methods to let me change what I needed to, then I'd be happy as a clam. I don't see how to do this, based on my reading of the API.  Instead, you have to pull in items one by one (as shown in the @Lukasa's code) and risk missing properties that `CertificateBuilder` doesn't have a method for.

@alex I'm pretty sure I've provided an argument as to why my use case is legitimate.
