### ISSUE TITLE
No support for decoding b64 NetscapeSPKI objects

### ISSUE THREAD

**Issue by delroth** [pyca/pyopenssl#177]
The documentation indicates that it's possible (by passing the base64-encoded DER to the NetscapeSPKI constructor), but the code does not support that.

AFAICT this would need to be done in two steps:
1. Add binding for NETSCAPE_SPKI_b64_decode in cryptography.
2. Implement that one argument variant of crypto.NetscapeSPKI.__init__

**Comment by joemiller** [comment]
Not sure if this is related but it might be. It seems like there is a regression from 0.13 to 0.14 that breaks this class.

Loading a SPKAC string returned by a browser `<keygen>` tag:

```
def spkac_to_pkey(spkac_str):
    """takes a SPKAC string sent by a browser using <keygen> and converts it into
    an OpenSSL.crypto.PKey object. Throws OpensSSL.Crypto.Error.
    """
    return crypto.NetscapeSPKI(spkac_str).get_pubkey()
```

- 0.14
```
  File "/data/home/joe/cert-maker/cert_maker.py", line 15, in spkac_to_pkey
    return crypto.NetscapeSPKI(spkac_str).get_pubkey()
TypeError: __init__() takes exactly 1 argument (2 given)
```

Code works OK in 0.13

**Comment by delroth** [comment]
Oh, I didn't know it used to work in 0.13. I thought it was just never implemented in PyOpenSSL.

Regardless, It looks like cryptography had new releases since I opened this issue. I don't have any time right now to increase PyOpenSSL requirements and implement that __init__(self, str) constructor, so feel free to take this over.

**Comment by futureimperfect** [comment]
@delroth @joemiller Any update on this? Is it just the constructor change that's needed now? Thanks!

**Comment by alex** [comment]
We're not going to be expanding the NetscapeSPKI interface.
