### ISSUE TITLE
CRL parameters missing from CRL objects

### ISSUE THREAD

**Issue by adulau** [pyca/pyopenssl#181]
pyopenssl doesn't provide the following parameters when parsing CRL objects (not the revoked objects)

```
    Issuer
    Last Update
    Next Update
    CRL extensions
        X509v3 CRL Number
```

Do you plan to add it?

Thank you very much.

PS: It seems to be a recurring issue cf http://stackoverflow.com/questions/13694984/pyopenssl-get-a-crls-last-update-and-next-update-fields

**Comment by schlenk** [comment]
You can get those things via pyasn1 (the pyasn1.util.rfc2459 module has the needed ASN.1 definitions...). But it is pretty ugly to do it that way and having access to the CRL data via pyopenssl (or Cryptography below it) would be useful.

**Comment by exarkun** [comment]
This would be a fine addition to pyOpenSSL.  If someone would like to submit a PR (with tests and documentation), I'd be happy to review it.

**Comment by eldoon** [comment]
Can we expect to see this in 16 Dev?

**Comment by reaperhulk** [comment]
When parsing CRLs use cryptography: https://cryptography.io/en/latest/x509/reference/#cryptography.x509.CertificateRevocationList
