### ISSUE TITLE
pyOpenSSL uses an order of magnitute more heap from 0.13 to 0.14

### ISSUE THREAD

**Issue by ianw** [pyca/pyopenssl#202]
Some CI jobs for OpenStack started running out of memory lately after some changes to install packages from pip v using distribution packages.  Investigation found that swift had just about doubled it's memory usage % wise and I tracked it down to pyOpenSSL [1]

But to show a self-contained example, on a fresh trusty cloud-image we can see that import of OpenSSL in an otherwise quiet system increases memory usage by about 2mb (6808 - 5404)

```
ubuntu@ubuntu:~$ ps -eo pid,rss,pmem,cmd  | grep [p]ython
7015  5404  1.0 python
ubuntu@ubuntu:~$ fg
import OpenSSL
>>> 
[1]+  Stopped                 python
ubuntu@ubuntu:~$ ps -eo pid,rss,pmem,cmd  | grep [p]ython
 7015  6808  1.3 python
```

But then if I remove that and install from pip we're looking at > 20mb (27864 - 5404)
```
ubuntu@ubuntu:~$ sudo apt-get --purge remove  python-openssl
 ... blah ...
Removing python-openssl (0.13-2ubuntu6) ...
ubuntu@ubuntu:~$ sudo pip install pyOpenSSL
Downloading/unpacking pyOpenSSL
  Downloading pyOpenSSL-0.14.tar.gz (128kB): 128kB downloaded
 ... blah ...
Successfully installed pyOpenSSL cryptography pyasn1 enum34 cffi pycparser
Cleaning up...

... python, import, ctrlz ...

ubuntu@ubuntu:~$ ps -eo pid,rss,pmem,cmd  | grep [p]ython
10637 27864  5.5 python
```

In the analysis of [1] the difference is basically all heap usage; I did run heapy on swift inside opensack and got the following two views

```
Partition of a set of 205366 objects. Total size = 30969040 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0  67041  33  5712560  18   5712560  18 str
     1  10260   5  2872800   9   8585360  28 dict of pycparser.plyparser.Coord
     2  27765  14  2367552   8  10952912  35 tuple
     3   1215   1  2246760   7  13199672  43 dict (no owner)
     4   1882   1  1972336   6  15172008  49 dict of pycparser.c_ast.Decl
     5  16085   8  1736232   6  16908240  55 list
     6    360   0  1135296   4  18043536  58 dict of module
     7   4041   2  1131480   4  19175016  62 dict of pycparser.c_ast.TypeDecl
     8   4021   2  1125880   4  20300896  66 dict of pycparser.c_ast.IdentifierType
     9   6984   3   893952   3  21194848  68 types.CodeType
<413 more rows. Type e.g. '_.more' to view.>

after install of packaged (0.13)

Partition of a set of 95591 objects. Total size = 12500080 bytes.
 Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
     0  45837  48  3971040  32   3971040  32 str
     1  22843  24  1943416  16   5914456  47 tuple
     2    298   0   978160   8   6892616  55 dict of module
     3   6065   6   776320   6   7668936  61 types.CodeType
     4    551   1   742184   6   8411120  67 dict (no owner)
     5    805   1   725520   6   9136640  73 type
     6   5876   6   705120   6   9841760  79 function
     7    805   1   666232   5  10507992  84 dict of type
     8    289   0   279832   2  10787824  86 dict of class
     9    152   0   159296   1  10947120  88 dict of pkg_resources.Distribution
<310 more rows. Type e.g. '_.more' to view.>
```

so I think that shows that pycparser is where the memory is mostly going.

[1] https://etherpad.openstack.org/p/oom-in-rax-centos7-CI-job

**Comment by exarkun** [comment]
pycparser is used via cffi which is used via cryptography which provides *all* of pyOpenSSL's access to OpenSSL.

Offhand I don't know what pyOpenSSL can do about this.  Perhaps it's worth raising the memory usage concerns with the pycparser maintainers to see if they know how memory usage can be reduced?

**Comment by ianw** [comment]
Yeah; as you say there's at least 4 rather complex layers (pycparser, cffi, cryptography & pyOpenSSL) and I'm no expert in how this all plugs together.  pyOpenSSL has a sort of 1:1 comparison between 0.13 & 0.14 ... whereas "cryptography" has probably just always used that much memory so nobody thinks its weird.

If anyone has suggestions on how I could construct a better bug report for lower layers such as "we do it this way and get X, do it this way and get Y" that would be helpful.

**Comment by ianw** [comment]
for reference, the versions of other packages installed

```
Downloading/unpacking cryptography>=0.2.1 (from pyOpenSSL)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in /usr/lib/python2.7/dist-packages (from pyOpenSSL)
Downloading/unpacking pyasn1 (from cryptography>=0.2.1->pyOpenSSL)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.7/dist-packages (from cryptography>=0.2.1->pyOpenSSL)
Downloading/unpacking enum34 (from cryptography>=0.2.1->pyOpenSSL)
Downloading/unpacking cffi>=0.8 (from cryptography>=0.2.1->pyOpenSSL)
Downloading/unpacking pycparser (from cffi>=0.8->cryptography>=0.2.1->pyOpenSSL)
```

see also https://github.com/eliben/pycparser/issues/72

**Comment by ianw** [comment]
An initial look at pycparser in https://github.com/eliben/pycparser/issues/72 suggests that the usage is about right.

might it be possible that something in the pyOpenSSL/cryptography/cffi layer is holding onto the parser output when it doesn't need to?

**Comment by hynek** [comment]
Is this still an issue?  I suspect it to be some cffi thing and cffi evolved quite a bit in the past year.

I think we can rule out pyOpenSSL since just use a few CFFI objects imported straight from cryptography.

**Comment by reaperhulk** [comment]
This issue was almost certainly resolved with the upgrade to cffi 1.x. I'm going to close it for now and it can be reopened if that's incorrect.
