### ISSUE TITLE
Can not specify engine

### ISSUE THREAD

**Issue by Badgerr** [pyca/pyopenssl#203]
Hi.
I need to verifiy signature by means of  "gost" engine and in console it works fine:
C:_OpenSSL-Win64\bin>openssl cms -engine gost -verify -in sign.cms -inform PEM -CAfile ca.crt -out data.file -certsout user.crt
engine "gost" set.
Verification successful

But in my code I get an error:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensio
ns\Microsoft\Python Tools for Visual Studio\2.1\visualstudio_py_util.py", line 1
06, in exec_file
    exec_code(code, file, global_variables)
  File "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensio
ns\Microsoft\Python Tools for Visual Studio\2.1\visualstudio_py_util.py", line 8
2, in exec_code
    exec(code_obj, global_variables)
  File "F:\Projects\pksc7_p\pksc7_p\pksc7_p.py", line 27, in <module>
    print cert.get_pubkey()
  File "C:\Python27\lib\site-packages\OpenSSL\crypto.py", line 788, in get_pubke
y
    _raise_current_error()
  File "C:\Python27\lib\site-packages\OpenSSL_util.py", line 22, in exception_f
rom_error_queue
    raise exceptionType(errors)
Error: [('digital envelope routines', 'PKEY_SET_TYPE', 'unsupported algorithm'),
 ('x509 certificate routines', 'X509_PUBKEY_get', 'unsupported algorithm')]

So, how can I specify "-engine gost" but in code? )

Thanks in advance for your reply.

**Comment by exarkun** [comment]
pyOpenSSL doesn't currently have any APIs for selecting an engine.  I'd welcome the addition of such APIs.  If you'd like to submit a PR (including tests and documentation) with them, I'd be happy to review it.

**Comment by s-sokolko** [comment]
I have the same issue! My task is to establish an HTTPS connection using non-standart crypto engine (GOST). Dear exarkun, could you please comment on the possibility of selectiong engine? I'm a python developer and I'd like to contribute to the project by adding some API for engine selection, but I'm not familiar with pyopenssl project and I need some information to start with. Maybe some developer guides or something like that. It would be very appreciated. Thanks!

**Comment by django-kz** [comment]
@exarkun , Hello, I need support of selecting an engine in my current working project either. Are there any changes with this issue in the library ? I'd like to develop and submit  this functionality if nobody is working on it. #203

**Comment by hynek** [comment]
AFAIK nobody is working on it at the moment.

**Comment by lacabra** [comment]
The following did it for me. You can add the following code snipped wherever you need `pyopenssl` to use an SSL engine of your choice, in this case for RSA:
```
import OpenSSL
from OpenSSL._util import (
    ffi as _ffi,
    lib as _lib)

def init_ssl_engine(engine):
    if not engine:
        raise ValueError('Environment variable SSL_ENGINE is not set')

    if isinstance(engine, str):
        engine = engine.encode('utf-8')

    engineId = _ffi.new("const char[]", engine)

    # Reference: https://www.openssl.org/docs/man1.0.2/crypto/engine.html
    _lib.ENGINE_load_builtin_engines()
    e = _lib.ENGINE_by_id(engineId)

    if e == _ffi.NULL:
        raise ValueError('Cannot find engine {}'.format(
            engine.decode('utf-8')))

    if not _lib.ENGINE_init(e):
        _lib.ENGINE_free(e)
        raise Exception('Cannot initialize engine {}'.format(
            engine.decode('utf-8')))

    if not _lib.ENGINE_set_default_RSA(e):
        _lib.ENGINE_free(e)
        raise ValueError('Cannot set engine {} as default RSA'.format(
            engine.decode('utf-8')))

    print('Engine {} is ready to use: {}'.format(engine.decode(), e))

init_ssl_engine('my_engine')
```

You can replace `_lib.ENGINE_set_default_RSA(e)` above for any of the following (or add as many as you need):
```
_lib.ENGINE_set_default_RSA(e)
_lib.ENGINE_set_default_DSA(e)
_lib.ENGINE_set_default_ECDH(e)
_lib.ENGINE_set_default_ECDSA(e)
_lib.ENGINE_set_default_DH(e)
_lib.ENGINE_set_default_RAND(e)
```
You also need to install the underlying [pyca/cryptography](https://github.com/pyca/cryptography) without the pre-built wheels as documented [here](https://cryptography.io/en/latest/installation/?highlight=no-binary#building) (be sure to install first the [required packages](https://cryptography.io/en/latest/installation/?highlight=no-binary#building-cryptography-on-linux)), since that's documented not to work with SSL engines specific to your system.

I am not submitting a PR request for this, because I cannot easily think of a way this can be unit tested. The above code worked in my system where a custom engine was installed, but it may be hard to generalize, and very hard to unit test; but maybe one of the project maintainers more familiar with the repo structure can easily incorporate the above into the repo :)

Thank you for the amazing work on this repo. `pyopenssl` rocks! 🥇

**Comment by hedin** [comment]
If previous answer did not work for you try this:

1)  Install cryptography as Victor said:
> You also need to install the underlying [pyca/cryptography](https://github.com/pyca/cryptography) without the pre-built wheels as documented [here](https://cryptography.io/en/latest/installation/?highlight=no-binary#building) (be sure to install first the [required packages](https://cryptography.io/en/latest/installation/?highlight=no-binary#building-cryptography-on-linux)), since that's documented not to work with SSL engines specific to your system.

2) Install ctypescrypto module
`pip install ctypescrypto`

3) Before reading or creating GOST (in my case) keys insert this code:
```python
from ctypescrypto.engine import Engine, set_default
set_default(Engine('gost'))
```

**Comment by shupp** [comment]
Thanks @lacabra and @hedin for posting.  I wonder if either of you know how to load a private key from the engine to use, rather than setting a default?  I have a situation where only one key (intermediate) should be in the HSM, so I can't set it as the default.  Thanks!

**Comment by lacabra** [comment]
Hi @shupp, I am not sure that I can help you, but I have to admit I don't fully understand what you are trying to do. Can you provide more details?

In trying to relate what you are posting, my setup involves only one key in the HSM, so when I set the HSM as the default engine, it is indeed using that one key I store in there.

**Comment by shupp** [comment]
Thanks @lacabra for the response.  That makes sense.  In my case, the CA key is in the AWS CloudHSM, but the app talking to the HSM (via PyOpenSSL) creates keys that are not intended to be in there.   So my understanding is that by setting it as the default, all keys would go in there.  (The app creates both keys and CSRs that are signed distributed to other apps, as opposed to just signing a CSR).  So in this case, I believe I would need to be explicit about when to use the engine.

**Comment by supreetd21** [comment]
Has the engine support been upstreamed in the repository?
I would like to programmatically sign a CSR from a USB Key through the PKCS#11 engine in OpenSSL.

**Comment by danielwangksu** [comment]
> The following did it for me. You can add the following code snipped wherever you need `pyopenssl` to use an SSL engine of your choice, in this case for RSA:
> 
> ```
> import OpenSSL
> from OpenSSL._util import (
>     ffi as _ffi,
>     lib as _lib)
> 
> def init_ssl_engine(engine):
>     if not engine:
>         raise ValueError('Environment variable SSL_ENGINE is not set')
> 
>     if isinstance(engine, str):
>         engine = engine.encode('utf-8')
> 
>     engineId = _ffi.new("const char[]", engine)
> 
>     # Reference: https://www.openssl.org/docs/man1.0.2/crypto/engine.html
>     _lib.ENGINE_load_builtin_engines()
>     e = _lib.ENGINE_by_id(engineId)
> 
>     if e == _ffi.NULL:
>         raise ValueError('Cannot find engine {}'.format(
>             engine.decode('utf-8')))
> 
>     if not _lib.ENGINE_init(e):
>         _lib.ENGINE_free(e)
>         raise Exception('Cannot initialize engine {}'.format(
>             engine.decode('utf-8')))
> 
>     if not _lib.ENGINE_set_default_RSA(e):
>         _lib.ENGINE_free(e)
>         raise ValueError('Cannot set engine {} as default RSA'.format(
>             engine.decode('utf-8')))
> 
>     print('Engine {} is ready to use: {}'.format(engine.decode(), e))
> 
> init_ssl_engine('my_engine')
> ```
> 
> You can replace `_lib.ENGINE_set_default_RSA(e)` above for any of the following (or add as many as you need):
> 
> ```
> _lib.ENGINE_set_default_RSA(e)
> _lib.ENGINE_set_default_DSA(e)
> _lib.ENGINE_set_default_ECDH(e)
> _lib.ENGINE_set_default_ECDSA(e)
> _lib.ENGINE_set_default_DH(e)
> _lib.ENGINE_set_default_RAND(e)
> ```
> 
> You also need to install the underlying [pyca/cryptography](https://github.com/pyca/cryptography) without the pre-built wheels as documented [here](https://cryptography.io/en/latest/installation/?highlight=no-binary#building) (be sure to install first the [required packages](https://cryptography.io/en/latest/installation/?highlight=no-binary#building-cryptography-on-linux)), since that's documented not to work with SSL engines specific to your system.
> 
> I am not submitting a PR request for this, because I cannot easily think of a way this can be unit tested. The above code worked in my system where a custom engine was installed, but it may be hard to generalize, and very hard to unit test; but maybe one of the project maintainers more familiar with the repo structure can easily incorporate the above into the repo :)
> 
> Thank you for the amazing work on this repo. `pyopenssl` rocks!

Hi @lacabra and @hedin, this is exactly what I need. But even after I build `cryptography`  my code still complains "AttributeError: module 'lib' has no attribute 'ENGINE_load_builtin_engines'". 

The version I'm using is Python 3.5.2,. cryptography 2.8 and pyopenssl 19.1.0

**Comment by asyd** [comment]
Same issue than @danielwangksu here, there is no function `ENGINE_load_builtin_engines` :/

**Comment by Emantor** [comment]
The reason this no longer works is that the cryptography library reduced its bindings used in pyopenssl in https://github.com/pyca/cryptography/commit/cc31c4f99e9ff1c2fa5acd0eabbf19a671b06b1d. You'll need to locally patch the bindings back in to use the engine functions.
