### ISSUE TITLE
0.15 raises a KeyError on calling shutdown twice

### ISSUE THREAD

**Issue by glyph** [pyca/pyopenssl#224]
Previously this raised an `OpenSSL.SSL.Error` with the empty list.

**Comment by glyph** [comment]
Perhaps this regressed in #91?

**Comment by hynek** [comment]
Yes, reverting 91 fixes this.  The problem is that `_raise_ssl_error` does not expect the case of an error with no errno which is exactly what happens if you call shutdown twice.

**Comment by hynek** [comment]
Fixed by #225, extended by #229
