### ISSUE TITLE
expose X509_verify_cert in some way

### ISSUE THREAD

**Issue by glyph** [pyca/pyopenssl#23]
I'd like to have some heuristics in Twisted for determining whether the system “probably” has some valid trust roots, so that the verification-failure error contains an explanation that a system administrator might be able to use to understand how to fetch some and actually have sensible certificate verification, rather than getting frustrated and falling back to plaintext.

One way to have such a heuristic (given that OpenSSL itself doesn't appear to expose any way to enumerate the certificates within an `X509_STORE*`) is to have some cached offline “known good” and “known bad” certificates and attempt to verify them and see what happens; the API to do this doesn't seem to be exposed by pyOpenSSL.

**Comment by exarkun** [comment]
Fixed by #155
