### ISSUE TITLE
Memory leak in pypy + pyopenssl

### ISSUE THREAD

**Issue by bbangert** [pyca/pyopenssl#242]
When using portable pypy + pyopenssl for SSL protected connections (in my case from autobahn+twisted), pyopenssl appears to leak substantial amounts of memory.

I have a relatively small app that can replicate this consistently (I will be making additional reduced versions over the next week to benchmark SSL connection overhead in general).

Replication instructions:
https://gist.github.com/bbangert/e04108b9bb53f99ec6d3

A portable version of pypy is needed to exhibit the leak.

**Comment by hynek** [comment]
Would it be possible for you check whether it’s a regression from 15.0 please?

**Comment by bbangert** [comment]
It's currently on pyopenssl 0.14. I'll test 0.15 now.

**Comment by bbangert** [comment]
It's on 0.15 as well.

**Comment by bbangert** [comment]
One thing in common the portable pypy, and a version we built on CentOS 7 have in common, is that they link to OpenSSL 1.0.1e. Using the debian pypy on my linux system (openssl 1.0.1f) does not exhibit this leak.

**Comment by hynek** [comment]
Thanks for investigating! Would you mind to give it a last spin with 13.2 so we can go for sure?

Is this the leak @fijal spoke of?

**Comment by hynek** [comment]
Paging @alex in the hopes for more PyPy smarts.

**Comment by bbangert** [comment]
0.13.1 will not compile again portable pypy's OpenSSL:

```
    cc -O2 -fPIC -Wimplicit -I/home/ubuntu/autopush/pypy/include -c OpenSSL/crypto/crypto.c -o build/temp.linux-x86_64-2.7/OpenSSL/crypto/crypto.o
    cc -O2 -fPIC -Wimplicit -I/home/ubuntu/autopush/pypy/include -c OpenSSL/crypto/x509.c -o build/temp.linux-x86_64-2.7/OpenSSL/crypto/x509.o
    cc -O2 -fPIC -Wimplicit -I/home/ubuntu/autopush/pypy/include -c OpenSSL/crypto/x509name.c -o build/temp.linux-x86_64-2.7/OpenSSL/crypto/x509name.o
    cc -O2 -fPIC -Wimplicit -I/home/ubuntu/autopush/pypy/include -c OpenSSL/crypto/pkey.c -o build/temp.linux-x86_64-2.7/OpenSSL/crypto/pkey.o
    cc -O2 -fPIC -Wimplicit -I/home/ubuntu/autopush/pypy/include -c OpenSSL/crypto/x509store.c -o build/temp.linux-x86_64-2.7/OpenSSL/crypto/x509store.o
    cc -O2 -fPIC -Wimplicit -I/home/ubuntu/autopush/pypy/include -c OpenSSL/crypto/x509req.c -o build/temp.linux-x86_64-2.7/OpenSSL/crypto/x509req.o
    cc -O2 -fPIC -Wimplicit -I/home/ubuntu/autopush/pypy/include -c OpenSSL/crypto/x509ext.c -o build/temp.linux-x86_64-2.7/OpenSSL/crypto/x509ext.o
    cc -O2 -fPIC -Wimplicit -I/home/ubuntu/autopush/pypy/include -c OpenSSL/crypto/pkcs7.c -o build/temp.linux-x86_64-2.7/OpenSSL/crypto/pkcs7.o
    cc -O2 -fPIC -Wimplicit -I/home/ubuntu/autopush/pypy/include -c OpenSSL/crypto/pkcs12.c -o build/temp.linux-x86_64-2.7/OpenSSL/crypto/pkcs12.o
    cc -O2 -fPIC -Wimplicit -I/home/ubuntu/autopush/pypy/include -c OpenSSL/crypto/netscape_spki.c -o build/temp.linux-x86_64-2.7/OpenSSL/crypto/netscape_spki.o
    cc -O2 -fPIC -Wimplicit -I/home/ubuntu/autopush/pypy/include -c OpenSSL/crypto/revoked.c -o build/temp.linux-x86_64-2.7/OpenSSL/crypto/revoked.o
    cc -O2 -fPIC -Wimplicit -I/home/ubuntu/autopush/pypy/include -c OpenSSL/crypto/crl.c -o build/temp.linux-x86_64-2.7/OpenSSL/crypto/crl.o
    OpenSSL/crypto/crl.c:6:23: error: static declaration of ‘X509_REVOKED_dup’ follows non-static declaration
     static X509_REVOKED * X509_REVOKED_dup(X509_REVOKED *orig) {
                           ^
    In file included from /home/ubuntu/autopush/pypy/include/openssl/ssl.h:156:0,
                     from OpenSSL/crypto/x509.h:17,
                     from OpenSSL/crypto/crypto.h:30,
                     from OpenSSL/crypto/crl.c:3:
    /home/ubuntu/autopush/pypy/include/openssl/x509.h:751:15: note: previous declaration of ‘X509_REVOKED_dup’ was here
     X509_REVOKED *X509_REVOKED_dup(X509_REVOKED *rev);
                   ^
    error: command 'cc' failed with exit status 1
    
    ----------------------------------------
    Rolling back uninstall of pyOpenSSL
    Command "/home/ubuntu/autopush/pypy/bin/pypy -c "import setuptools, tokenize;__file__='/tmp/pip-build-oNd28X/pyopenssl/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-4wYbGQ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-oNd28X/pyopenssl
```

**Comment by hynek** [comment]
To be absolutely clear and avoid any delays due to miscommunication: I’m not even close to be in the possession of the necessary skills to debug this.

It would be great if someone of the PyPy folks took a heart and looked at it but from my side there won’t be any more than a merge of a possible fix.

Sorry for my inaptitude.

**Comment by arigo** [comment]
Cannot run the test: at the end, nosetests complains that all 12 tests failed with ``gaierror: [Errno -2] Name or service not known``...

**Comment by bbangert** [comment]
@arigo Can you show more of the output? The Travis testing and our tests all seem to pass fine.

**Comment by arigo** [comment]
Fijal helped me and I realize now that I commented on the "replication instructions" link instead of here.

**Comment by fijal** [comment]
There have been fixes in cffi that might be related to that, can someone recheck with a recent build of pypy?

**Comment by hynek** [comment]
Any feedback whether this has been fixed?

**Comment by bbangert** [comment]
We're not running with SSL enabled since ELB now has SSL, the latest PyPy doesn't seem to leak like it did, so I'm fine closing this.

**Comment by hynek** [comment]
Great, thanks!
