### ISSUE TITLE
pyopenssl uses 10kb more RAM per connection than Py3's SSL

### ISSUE THREAD

**Issue by bbangert** [pyca/pyopenssl#249]
I've been putting together a test suite for SSL overhead with websocket servers, and with a basic echo websocket server under autobahn, using twisted vs. py3 asyncio, the py3 SSL seems to use 10kb less per connection than twisted (which uses pyopenssl).

```
$ ./tester/run_test Python/autobahn-asyncio                                      
No SSL
Program started.
Tester started.
Tester finished connecting.
Program memory stopped increasing.
Started with: 14131200
Ended with: 32559104
kB per connection: 18.00


SSL
Program started.
Tester started.
Tester finished connecting.
Program memory stopped increasing.
Started with: 14671872
Ended with: 62812160
kB per connection: 47.01

SSL Overhead per Conn: 29.02


$ ./tester/run_test Python/autobahn-twisted                                      
No SSL
Program started.
Tester started.
Tester finished connecting.
Program memory stopped increasing.
Started with: 27406336
Ended with: 52568064
kB per connection: 24.57


SSL
Program started.
Tester started.
Tester finished connecting.
Program memory stopped increasing.
Started with: 27611136
Ended with: 92684288
kB per connection: 63.55

SSL Overhead per Conn: 38.98

```

I'm not sure where this additional overhead is coming from or why.

A full repo with all the code to run this, and both examples is here:
https://github.com/bbangert/ssl-ram-testing/

**Comment by elitest** [comment]
Just some additional context from Ilya Grigorik's [Is TLS Fast yet?](https://www.youtube.com/watch?v=0EB7zh_7UE4) talk from a while back.  His [slides](https://docs.google.com/presentation/d/1OGulyC9grEXw-wW2VdZdZ99YNO3l3H2l_wgwxEG4GOM/present?slide=id.gebc26cd7_8_36) claim normal connections being ~100 kb per connection while Google's implementation is around ~10 kb per connection total.

I've always wondered why they haven't made that stuff open and public, as I can't imagine what competitive edge it gives them.  It would make for some awesome reading too.

**Comment by bbangert** [comment]
@elitest Yea, I've seen multiple posts focusing on whether its fast. In my specific use-case, speed isn't a problem, only memory use. This is for a Push system, so lots and lots of idle connections. It's part of my hope with this testing project (and an upcoming blog post) that some focus can be spent on optimizing memory use.

There's an option for OpenSSL, SSL_MODE_RELEASE_BUFFERS, which supposedly can drop 32kb per connection. It seemed to have almost no effect in my twisted code (which uses pyopenssl), and Py3.4's ssl context doesn't even let me set it (maybe they set it by default?).

Standard OpenSSL has a 16kb send and receive buffer, the RELEASE_BUFFERS supposedly lets it drop that for idle connections. There's another setting I've heard of 'max free list len', that I can't see how to set, which indicates how many of these 'freed' buffers OpenSSL should be kept around.

Course, still no idea how/why Py3's SSL only added 29kb vs. twisted+pyopenssl's 38kb.

**Comment by hynek** [comment]
I seem to remember a ticket that complained that pyOpenSSL'S mem usage went up since switching to cryptography/cffi. 

Would you mind verifying what happens with 0.13.1?

**Comment by bbangert** [comment]
No difference for the most part, just slightly marginally lower but that's within margin of error on repeat runs.

```
No SSL
Program started.
Tester started.
Tester finished connecting.
Program memory stopped increasing.
Started with: 16338944
Ended with: 41545728
kB per connection: 24.62


SSL
Program started.
Tester started.
Tester finished connecting.
Program memory stopped increasing.
Started with: 16560128
Ended with: 80928768
kB per connection: 62.86

SSL Overhead per Conn: 38.24
```

**Comment by bbangert** [comment]
Ok, I should rephrase, there is a difference in initial memory use. The starting memory is ~ 10 MB less. The per connection overhead hasn't changed though.

**Comment by hynek** [comment]
Thanks, I’m glad we don’t have another CFFI regression.

It *might* be Twisted-related too though, right?

As a side-note: DefaultOpenSSLContextFactory shouldn’t be used anymore (and should be deprecated :-/).  Please use t.i.s.CertificateOptions like demonstrated in http://twistedmatrix.com/documents/current/core/howto/ssl.html

**Comment by bbangert** [comment]
Changing the SSL context family around didn't seem to make any difference in RAM usage.

**Comment by hynek** [comment]
Yeah hence “side-note”.  I just get sad when people use the unsafe version. :)

**Comment by alex** [comment]
Wasn't the conclusion here that the problem was putting `MODE_RELEASE_BUFFERS` in the wrong place?
