### ISSUE TITLE
Add set_verify method on Connection

### ISSUE THREAD

**Issue by mithrandi** [pyca/pyopenssl#255]
When changing the context with set_context, the verify mode/callback is not updated from the new context, you need to call SSL_set_verify on the connection to update it.

This function is not currently exposed by Cryptography, so it will need to be added there too.

**Comment by mithrandi** [comment]
`set_verify_depth` should probably be added at the same time.

**Comment by elitest** [comment]
Sorry, what exactly does [this](https://github.com/pyca/pyopenssl/blob/master/OpenSSL/SSL.py#L734-766) do?

**Comment by mithrandi** [comment]
That method is on `Context`, not `Connection`; as previously mentioned, the context settings are used to initialize the connection, but if the context is changed with `set_context` later, the verification settings from the new context are not transferred to the connection.

**Comment by mithrandi** [comment]
To elaborate on this a bit further: `set_context` is commonly used in a callback set with `set_tlsext_servername_callback` in order to change the context based on which hostname the client requests using SNI; if you want to do client verification on some hostnames but not on others, you need to be able to call `SSL_set_verify` to change the verification settings on that connection.

**Comment by elitest** [comment]
Ah gotcha.

**Comment by mhils** [comment]
We have some renewed interest in this from some folks in https://github.com/mitmproxy/mitmproxy/issues/5019, it also looks like we wouldn't be the only ones for whom this would be useful. I'd be happy to re-add the bindings to cryptography and then update #844. 

@alex, @reaperhulk et al: Is this something you would be willing to merge, or too much extra complexity for too little value? I don't have strong feelings, we can work around this on our end if necessary.

**Comment by reaperhulk** [comment]
Adding this to Connection + a single additional binding in cryptography seems reasonable to me given that you have people interested in actually using it.
