### ISSUE TITLE
Remove API duplication in pyca/pyopenssl and pyca/cryptography

### ISSUE THREAD

**Issue by schlenk** [pyca/pyopenssl#267]
With the new 0.9 release of cryptography there is a quite complete set of X509 support classes available in pyca/cryptography. The 0.10/1.0 release will probably add even more X509 support, maybe including CRLs.

Probably pyopenssl should move to reuse the already available pyca/cryptography APIs in the future, instead of providing duplicate wrappers for the same objects, especially in the X509/CRL area.

**Comment by hynek** [comment]
That’s indeed the case!  I completely forgot about this issue and felt smart when proposing it in https://mail.python.org/pipermail/cryptography-dev/2015-December/000539.html .

Long story short, this is our plan for 16.1.

**Comment by hynek** [comment]
We’ll use this as an umbrella for the porting effort.

The following objects should be ported to the new way:

- [x] Keys done in  #439
- [ ] [OpenSSL.crypto.X509 (Certificates)](https://pyopenssl.readthedocs.io/en/stable/api/crypto.html#OpenSSL.crypto.X509) → [cryptography.x509.Certificate](https://cryptography.io/en/latest/x509/reference/#x-509-certificate-object)
- [ ] [OpenSSL.crypto.X509Req](https://pyopenssl.readthedocs.io/en/stable/api/crypto.html#OpenSSL.crypto.X509Req) → [cryptography.x509.CertificateSigningRequest](https://cryptography.io/en/latest/x509/reference/#x-509-csr-certificate-signing-request-object)
- [ ] [OpenSSL.crypto.CRL](https://pyopenssl.readthedocs.io/en/stable/api/crypto.html#crl-objects) → [cryptography.x509.CertificateRevocationList](https://cryptography.io/en/latest/x509/reference/#x-509-crl-certificate-revocation-list-object)

Related: #479
