### ISSUE TITLE
CONTRIBUTING.rst refers to pyopenssl-committers team

### ISSUE THREAD

**Issue by lvh** [pyca/pyopenssl#269]
https://github.com/pyca/pyopenssl/blob/master/CONTRIBUTING.rst
https://github.com/orgs/pyca/teams/pyopenssl-committers

Right now this is just me and JP so maybe we should fix that either by changing the guidelines or adding at least @hynek to that group.

**Comment by elitest** [comment]
#205 related

**Comment by hynek** [comment]
I think I’ll write a doc page summarizing the current development/governance model.

I had that in mind for a while.

**Comment by lvh** [comment]
Looks like this is a duplicate of #205 (thanks @elitest) so we should close one of them (probably this one since it's older).

**Comment by hynek** [comment]
fixed
