### ISSUE TITLE
Enhance extensions on x509/x509req

### ISSUE THREAD

**Issue by sholsapp** [pyca/pyopenssl#280]
One thing that I find myself doing quite frequently with a certificate's extensions is this:

``` python
for idx in range(x509cert.get_extension_count()):                                                                                                                                                         
    ext = x509cert.get_extension(idx)                                                                                                                                                                          
    if ext.get_short_name() == 'authorityInfoAccess':                                                                                                    
        # ...
    elif ext.get_short_name() == 'subjectAltName':
        # ....
```

It would be pretty nice if I could access the certificates extensions in a more Pythonic way. There's lots of ways to do this, I suppose, but I think a easy implementation would involve dictionaries. I'm not sure about the details yet, e.g., what you would do on `KeyError`, if you'd want this to be case insensitive, n-many extensions with the same name, etc., but I'm sure it can't be _that_ tricky to get right. :sweat_smile: 

Then, ideally, I could do something like this:

``` python
x509cert.extensions['authorityInfoAccess']
x509cert.extensions['subjectAltName']
```

What do people think about this enhancement? If it would be merged, I would implement it.

**Comment by hynek** [comment]
Yeah that it sounds much nicer to have a kind-of-dict object.  I wonder though whether the current API mirrors something from OpenSSL?

How would everyone feel about something like a function `extensions_to_dict(x509)` which would return an actual dictionary?

**Comment by zblach** [comment]
+1
It might be more complicated than a dictionary, as some extensions are allowed multiple times. Also, the current way of iterating over extensions could also be more pythonic. I've had to write things like
    for extension in (x509.get_extension(i) for i in xrange(x509.get_extension_count())):

**Comment by reaperhulk** [comment]
What extensions are allowed more than once? RFC 5280 is pretty clear that extensions must appear at most once. Is there an RFC that supersedes that proscription?

**Comment by zblach** [comment]
It's entirely possible that I'm wrong. Let me pull a few of the keys I'm working with and have a look.

**Comment by sholsapp** [comment]
@hynek I think it would make more sense to expose a dictionary-like thing as an attribute on the `X509` and `X509Req` objects themselves. This feels more natural to me and makes client code a little easier to follow. E.g., it's very clear that in `x509cert.extensions['subjectAltName']` which certificate's extensions are being accessed, whereas if we write a utility function that returns a dictionary it could become convoluted.

My suggested approach is a little more complicated though and would require some extra bits. At a minimum we need some dictionary like thing. Then we'd need to decide things like:

1. Do we want the `OpenSSL.crypto.X509.extensions` to be a read only attribute or would we be able to add extensions to a certificate by assigning to `OpenSSL.crypto.X509.extensions`?
2. Do we want to get into the business of parsing ASN.1 data or should we leave that to another library? If the latter, should we expose some way of registering callback decoders to further process the extension's data?
   
In one of my pet projects, I hacked up a *partial* implementation (I said *partial*!) like the following. We could pretty easily work something like this into both `OpenSSL.crypto.X509` or `OpenSSL.crypto.X509Req`.                                                                                                                                                                                    

```python
class X509ExtensionDict(dict):

  # Maybe expose some way to register this, as we don't want to get 
  # into the business of ASN.1 parsing, right?
  decoders = {                                                                                                                                                                                                 
    'subjectAltName': decode_subject_alt_name,                                                                                                                                                                 
    'authorityInfoAccess': decode_authority_information_access,                                                                                                                                                
  }
                                                                                                                                                                                                               
  def __init__(self, x509cert, *args, **kwargs):                                                                                                                                                                                  
    super(X509ExtensionDict, self).__init__(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                              
    for idx in range(0, x509cert.get_extension_count()):                                                                                                                                                       
      ext = x509cert.get_extension(idx)                                                                                                                                                                        
      self[ext.get_short_name()] = ext                                                                                                                                                                         
                                                                                                                                                                                                               
  def __getitem__(self, key):     
    # Get and (possibly?) decode the ASN.1 data if we have a parser/callback for it
    # keyed on the extension's short name                                                                                                                                                                             
    return super(X509ExtensionDict, self).__getitem__(key)                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                               
  def __setitem__(self, key, value):     
    # Set the extension, and (possibly?) add the extension to the
    # OpenSSL.crypto.X509|X509Req object itself                                                                                                                                                                      
    return super(X509ExtensionDict, self).__setitem__(key, value)                                                                                                                                              
                                                                                                                                                                                                               
  def iteritems(self):                                                                                                                                                                                         
    # Force __getitem__ to be called on iteration                                                                                                                                                              
    for ext in self:                                                                                                                                                                                           
      yield (ext, self[ext])
```

IMO, this approach makes my pyOpenSSL client code much nicer to work with.

Thoughts welcomed! :smile:

**Comment by cardonator** [comment]
This is definitely something that makes working with extension data in pyOpenSSL a much bigger pain than it needs to be. I am very much in support of sholsapp's suggestion as far as access goes.

**Comment by alex** [comment]
At this point we won't be expanding the X509 API, you should use cryptography's x509 API instead.
