### ISSUE TITLE
cryptography 1.0 broke pypy builders

### ISSUE THREAD

**Issue by hynek** [pyca/pyopenssl#297]
Since the pypy on Travis’ infrastructure is 2.5 and bundles an old cffi, our pypy builders are failing now.

I’m not sure what to do but I’m tending to make pypy unsupported.  cryptography itself does a huge dance with pyenv which I’m not willing to adapt.  If others have the time, patches welcome. :-/  Until then we’re kind of stuck now.

@alex @reaperhulk

**Comment by or** [comment]
I can confirm this. A workaround is to pin `cryptography==0.8.2` and to rebuild your virtualenv.
pyopenssl simply requires `cryptography>0.7` and it probably needs to constrain it further to `<=0.9` or something.

**Comment by reaperhulk** [comment]
@or I'm not sure I understand. cryptography 1.0 should work fine with pyopenssl on environments that aren't pypy < 2.6. Do you have a reproducer?

**Comment by or** [comment]
@reaperhulk You're right, I think my way to look at this was off. I guess pyopenssl isn't to blame at all, if it can work with those versions.

But in my case and in @hynek's case there's a dependency on an older cffi around and that breaks things. So since pyopenssl doesn't *need* a newer cryptography, pinning it to 0.8.2 works.

**Comment by reaperhulk** [comment]
Ah, yeah that will do it. You can pin to 0.9.3 until the older cffi dependency goes away (1.0 is the first release requiring cffi 1.1+). If you control the library that has the older cffi dep you can (likely) unpin it as well, as cffi 1.x supports the cffi 0.x APIs.

**Comment by reaperhulk** [comment]
(Just for reference, the benefit of using cryptography 1.0 with pyopenssl is over 50x faster import times and ~20MB decrease in heap usage on import).
