### ISSUE TITLE
Issue Finding Symbol ? 

### ISSUE THREAD

**Issue by ArEnSc** [pyca/pyopenssl#309]
ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so, 2): Symbol not found: _CRYPTO_malloc_debug_init

**Comment by reaperhulk** [comment]
@ArEnSc Could you give us the output of `otool -L /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so`?

**Comment by ArEnSc** [comment]
otool -L /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so:
	/opt/local/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/opt/local/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)

**Comment by reaperhulk** [comment]
Is this macports? What happens if you reinstall cryptography as follows?

```python
pip uninstall cryptography
CFLAGS="-I/opt/local/include/" pip install cryptography --no-use-wheel
```

(I am assuming this will error, but not sure if it will provide a different error or not)

**Comment by ArEnSc** [comment]
Collecting cryptography
  Downloading cryptography-1.0.1.tar.gz (332kB)
    100% |████████████████████████████████| 335kB 936kB/s 
setuptools must be installed to install from a source distribution

? 

This is the new problem :S

**Comment by reaperhulk** [comment]
We've always required setuptools as part of our install process so I'm not sure why you'd get that now. Now that cryptography 1.0.1 is out do you get the same error if you just `pip install cryptography`?

**Comment by ArEnSc** [comment]
Hey it works right now, not sure why but it does thanks!

**Comment by reaperhulk** [comment]
As of 1.0.1 we started shipping static wheels for OS X 10.10+ users. That's probably why it works :) I'll go ahead and close this, but if you run into the same problem feel free to comment/reopen.
