### ISSUE TITLE
pyOpenSSL only supports GeneralizedTime for validity but UTCTime is required for RFC compliance

### ISSUE THREAD

**Issue by rudolphfroger** [pyca/pyopenssl#311]
It seems that pyOpenSSL uses GeneralizedTime unconditionally which is not RFC compliant:

```
CAs conforming to this profile MUST always encode certificate
validity dates through the year 2049 as UTCTime; certificate validity
dates in 2050 or later MUST be encoded as GeneralizedTime.
```

Also see:
https://www.v13.gr/blog/?p=342
and:
https://bugs.launchpad.net/pyopenssl/+bug/1203407

**Comment by rudolphfroger** [comment]
gmtime_adj_notBefore and gmtime_adj_notAfter seem to be correct with regards to when to use UTCTIME or GENERALIZEDTIME.

**Comment by reaperhulk** [comment]
Thanks for the report! Do you happen to have some test certificates that can demonstrate this bug? (It doesn't look difficult to generate them, but if you already have some that would be helpful)

**Comment by rudolphfroger** [comment]
Example certificate:

	-----BEGIN CERTIFICATE-----
	MIIDQDCCAigCEQDz/Qif+KVFNI6d+xyqxfeTMA0GCSqGSIb3DQEBCwUAMFwxCzAJ
	BgNVBAYTAk5MMRUwEwYDVQQIDAxadWlkLUhvbGxhbmQxDjAMBgNVBAcMBURlbGZ0
	MQswCQYDVQQKDAJEUzEZMBcGA1UEAwwQZHJlYW1zb2x1dGlvbi5ubDAiGA8yMDE1
	MDEwMTAwMDAwMFoYDzIwMTcwMTAxMDAwMDAwWjBcMQswCQYDVQQGEwJOTDEVMBMG
	A1UECAwMWnVpZC1Ib2xsYW5kMQ4wDAYDVQQHDAVEZWxmdDELMAkGA1UECgwCRFMx
	GTAXBgNVBAMMEGRyZWFtc29sdXRpb24ubmwwggEiMA0GCSqGSIb3DQEBAQUAA4IB
	DwAwggEKAoIBAQDFDIIhLOAGu7iUAaR5PdCirzM1bDAWmOvj6HpmgsGAcFXd4J+c
	+E/oFF4LBiiXybSgSsaPQAvsLmRsQVNYT5TUizj4j6fW51J5syS1d5R05tq/zTki
	bHu+lDESmLGZpd5bXv5k5k8g+9YaNp+vQ/CylnlyeV9692hlltrAAqYSwaVfSbeK
	QV8I2+AAt6Py1zyt1IkLgFZScFCKHcetFK9yCGgl/T5doP/1DqGsmdsNGMI5eRaH
	NCDdg5u0aYNjrvDbSUwtlEgSlxYholAGhJF2gcKIin4/0gkcGP0boctIG9SBCm9Z
	cASQ0aDZOM6182Hx7pvu5/W6vc3XzK+CG5y/AgMBAAEwDQYJKoZIhvcNAQELBQAD
	ggEBAKKMwoORe8U773lzjeLO1xZUKSZ/TD9gw0gkC2ZxAQ9/emepFXmw1F4t6XEJ
	jr0FrkmNb8YL6xvHUrurPK5OT47U7KMNQcTB9iDS0phLYHZ8RtvtBW002M3sEYJ+
	/N4WvEqVNnrkWxPtyLe+NDUSFd3WzAy7CFPPL/YA0vElzasnxwIymHlel0hVh1qg
	T8IJEgo02RBgHyN/Pob3K1rA0vnP0PGqejCSSC74Zju4AYeQMMKarzJbFVpq9C+g
	VEVUkVwJDM+HPPfRavTMoQvcxBNH5c4nUcke/XJjHRVcfrgiYBLNCECqZ77Q9xqy
	ugnMgTFJchhBqJaCsFjfUrEdpOM=
	-----END CERTIFICATE-----

Example script:

	import OpenSSL
	import uuid

	k = OpenSSL.crypto.PKey()
	k.generate_key(OpenSSL.crypto.TYPE_RSA, 2048)

	cert = OpenSSL.crypto.X509()
	cert.get_subject().C = "NL"
	cert.get_subject().ST = "Zuid-Holland"
	cert.get_subject().L = "Delft"
	cert.get_subject().O = "DS"
	cert.get_subject().CN = 'dreamsolution.nl'
	cert.set_serial_number(uuid.uuid4().int)
	cert.set_notBefore('20150101000000Z')
	cert.set_notAfter('20170101000000Z')
	cert.set_issuer(cert.get_subject())
	cert.set_pubkey(k)
	cert.sign(k, 'sha256')

	with open('test_cert.crt', 'wb') as f:
		f.write(
			OpenSSL.crypto.dump_certificate(
					OpenSSL.crypto.FILETYPE_PEM, cert))

**Comment by rudolphfroger** [comment]
`openssl asn1parse` output below which clearly demonstrates that `GENERALIZEDTIME` has been used:

		0:d=0  hl=4 l= 832 cons: SEQUENCE          
		4:d=1  hl=4 l= 552 cons: SEQUENCE          
		8:d=2  hl=2 l=  17 prim: INTEGER           :F3FD089FF8A545348E9DFB1CAAC5F793
	   27:d=2  hl=2 l=  13 cons: SEQUENCE          
	   29:d=3  hl=2 l=   9 prim: OBJECT            :sha256WithRSAEncryption
	   40:d=3  hl=2 l=   0 prim: NULL              
	   42:d=2  hl=2 l=  92 cons: SEQUENCE          
	   44:d=3  hl=2 l=  11 cons: SET               
	   46:d=4  hl=2 l=   9 cons: SEQUENCE          
	   48:d=5  hl=2 l=   3 prim: OBJECT            :countryName
	   53:d=5  hl=2 l=   2 prim: PRINTABLESTRING   :NL
	   57:d=3  hl=2 l=  21 cons: SET               
	   59:d=4  hl=2 l=  19 cons: SEQUENCE          
	   61:d=5  hl=2 l=   3 prim: OBJECT            :stateOrProvinceName
	   66:d=5  hl=2 l=  12 prim: UTF8STRING        :Zuid-Holland
	   80:d=3  hl=2 l=  14 cons: SET               
	   82:d=4  hl=2 l=  12 cons: SEQUENCE          
	   84:d=5  hl=2 l=   3 prim: OBJECT            :localityName
	   89:d=5  hl=2 l=   5 prim: UTF8STRING        :Delft
	   96:d=3  hl=2 l=  11 cons: SET               
	   98:d=4  hl=2 l=   9 cons: SEQUENCE          
	  100:d=5  hl=2 l=   3 prim: OBJECT            :organizationName
	  105:d=5  hl=2 l=   2 prim: UTF8STRING        :DS
	  109:d=3  hl=2 l=  25 cons: SET               
	  111:d=4  hl=2 l=  23 cons: SEQUENCE          
	  113:d=5  hl=2 l=   3 prim: OBJECT            :commonName
	  118:d=5  hl=2 l=  16 prim: UTF8STRING        :dreamsolution.nl
	  136:d=2  hl=2 l=  34 cons: SEQUENCE          
	  138:d=3  hl=2 l=  15 prim: GENERALIZEDTIME   :20150101000000Z
	  155:d=3  hl=2 l=  15 prim: GENERALIZEDTIME   :20170101000000Z
	  172:d=2  hl=2 l=  92 cons: SEQUENCE          
	  174:d=3  hl=2 l=  11 cons: SET               
	  176:d=4  hl=2 l=   9 cons: SEQUENCE          
	  178:d=5  hl=2 l=   3 prim: OBJECT            :countryName
	  183:d=5  hl=2 l=   2 prim: PRINTABLESTRING   :NL
	  187:d=3  hl=2 l=  21 cons: SET               
	  189:d=4  hl=2 l=  19 cons: SEQUENCE          
	  191:d=5  hl=2 l=   3 prim: OBJECT            :stateOrProvinceName
	  196:d=5  hl=2 l=  12 prim: UTF8STRING        :Zuid-Holland
	  210:d=3  hl=2 l=  14 cons: SET               
	  212:d=4  hl=2 l=  12 cons: SEQUENCE          
	  214:d=5  hl=2 l=   3 prim: OBJECT            :localityName
	  219:d=5  hl=2 l=   5 prim: UTF8STRING        :Delft
	  226:d=3  hl=2 l=  11 cons: SET               
	  228:d=4  hl=2 l=   9 cons: SEQUENCE          
	  230:d=5  hl=2 l=   3 prim: OBJECT            :organizationName
	  235:d=5  hl=2 l=   2 prim: UTF8STRING        :DS
	  239:d=3  hl=2 l=  25 cons: SET               
	  241:d=4  hl=2 l=  23 cons: SEQUENCE          
	  243:d=5  hl=2 l=   3 prim: OBJECT            :commonName
	  248:d=5  hl=2 l=  16 prim: UTF8STRING        :dreamsolution.nl
	  266:d=2  hl=4 l= 290 cons: SEQUENCE          
	  270:d=3  hl=2 l=  13 cons: SEQUENCE          
	  272:d=4  hl=2 l=   9 prim: OBJECT            :rsaEncryption
	  283:d=4  hl=2 l=   0 prim: NULL              
	  285:d=3  hl=4 l= 271 prim: BIT STRING        
	  560:d=1  hl=2 l=  13 cons: SEQUENCE          
	  562:d=2  hl=2 l=   9 prim: OBJECT            :sha256WithRSAEncryption
	  573:d=2  hl=2 l=   0 prim: NULL              
	  575:d=1  hl=4 l= 257 prim: BIT STRING

**Comment by reaperhulk** [comment]
The easiest way to fix this is to use `ASN1_TIME_set` instead of the current pyOpenSSL code as it Does The Right Thing™. If anybody is interested in writing up a PR an example of its use can be found here: https://github.com/pyca/cryptography/blob/master/src/cryptography/hazmat/backends/openssl/backend.py#L1264

**Comment by alex** [comment]
https://cryptography.io/ is preferred for any new x.509 work, the pyOpenSSL x.509 APIs are bad.
