### ISSUE TITLE
Error loading a certificate

### ISSUE THREAD

**Issue by ibrabeicker** [pyca/pyopenssl#312]
The following code throws an error 

    >>> key = OpenSSL.crypto.PKey()
    >>> key.generate_key(OpenSSL.crypto.TYPE_RSA, 1024)
    >>> cert = OpenSSL.crypto.X509()
    >>> cert.set_pubkey(key)
    >>> cert.sign(key, 'sha1')
    >>> public_key =  OpenSSL.crypto.dump_certificate(OpenSSL.crypto.FILETYPE_PEM, cert)
    >>> cert2 = OpenSSL.crypto.load_certificate(OpenSSL.crypto.FILETYPE_PEM, public_key)
    OpenSSL.crypto.Error: [('asn1 encoding routines', 'ASN1_get_object', 'too long'), ('asn1 encoding routines', 'ASN1_CHECK_TLEN', 'bad object header'), ('asn1 encoding routines', 'ASN1_ITEM_EX_D2I', 'nested asn1 error'), ('asn1 encoding routines', 'ASN1_TEMPLATE_NOEXP_D2I', 'nested asn1 error'), ('asn1 encoding routines', 'ASN1_TEMPLATE_NOEXP_D2I', 'nested asn1 error'), ('asn1 encoding routines', 'ASN1_TEMPLATE_NOEXP_D2I', 'nested asn1 error'), ('PEM routines', 'PEM_ASN1_read_bio', 'ASN1 lib')]

**Comment by reaperhulk** [comment]
A public key alone is insufficient to generate a certificate structure that OpenSSL is willing to parse (but as you've discovered, it is perfectly happy to sign it). Given pyOpenSSL's positioning as a relatively thin wrapper over OpenSSL I'm not sure if we should make any changes to prevent this. [cryptography](https://github.com/pyca/cryptography), the project pyOpenSSL depends on, has a certificate signing layer that does not allow this behavior.

**Comment by wafflespeanut** [comment]
For anyone who's getting this, OpenSSL demands `notBefore` and `notAfter` constraints on certificates. Setting those before signing worked for me.
