### ISSUE TITLE
Loads default openssl certificates even with context.load_verify_locations(path)

### ISSUE THREAD

**Issue by bkreider** [pyca/pyopenssl#360]
I'm trying to test a bad CA Root store, but when i use: `context.load_verify_locations(path)` to specify my cacert.pem, pyopenssl is still able to validate certs that shouldn't be validating anymore.  

I think pyopenssl is pulling in the openssl default CA Roots.  How do I force it to use only my supplied CA Root?

**Comment by hynek** [comment]
Is this OS X and the OpenSSL Apple ships with it?

**Comment by bkreider** [comment]
Sorry, I should have specified.  I realized now that it is working as it should.  I wasn't re-raising the exception when validation failed.  Sorry for the noise.
