### ISSUE TITLE
Add support for extracting contents of PKCS7

### ISSUE THREAD

**Issue by ddcc** [pyca/pyopenssl#365]
Currently, PKCS#7 support in pyOpenSSL appears to be limited to retrieving metadata for a subset of fields, e.g whether it is signed, enveloped, or etc. However, there is no support for extracting certificates and/or CRL's from PKCS#7 objects.

**Comment by ddcc** [comment]
Mostly resolved in #367, at least for my purposes

**Comment by sbose78** [comment]
Could you please tell me, in brief the capabilities you added? I would want to extend this.

**Comment by ddcc** [comment]
That commit added support for extracting certificates, CRL's, and data from certain PKCS#7 objects. But, it was never merged into the main codebase.

**Comment by woodruffw** [comment]
Triaging: for certificate extraction, the correct APIs here are `load_pem_pkcs7_certificates` and `load_der_pkcs7_certificates` on `cryptography`.

**Comment by alex** [comment]
PKCS#7 support has been removed from pyOpenSSL, in favor of pyca/cryptography's PKCS#7 APIs.
