### ISSUE TITLE
How to get Certificate chain like openssl command:  [understand code]

### ISSUE THREAD

**Issue by jiamo** [pyca/pyopenssl#366]
#### openssl s_client -connect google.com:443 |tee logfile

    depth=2 /C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
    verify error:num=20:unable to get local issuer certificate
    verify return:0
    CONNECTED(00000003)
    ---
    Certificate chain
     0 s:/C=US/ST=California/L=Mountain View/O=Google Inc/CN=*.google.com
       i:/C=US/O=Google Inc/CN=Google Internet Authority G2
     1 s:/C=US/O=Google Inc/CN=Google Internet Authority G2
       i:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
     2 s:/C=US/O=GeoTrust Inc./CN=GeoTrust Global CA
       i:/C=US/O=Equifax/OU=Equifax Secure Certificate Authority
    ---

Here is I using pyopenssl:  my repo : https://github.com/jiamo/get_server_certinfo
#### python get_cert_info.py google.com:443

    Server certinfo is <X509Name object '/C=US/ST=California/L=Mountain View/O=Google Inc/CN=*.google.com'>

I can't find api to extact the chain information like openssl client.

**Comment by alex** [comment]
`get_peer_cert_chain` is the method you want.
