### ISSUE TITLE
can't install pyOpenSSL

### ISSUE THREAD

**Issue by a568953256** [pyca/pyopenssl#379]
when I do:
$pip install pyopenssl

I meet the error:
Command "/home/rd/.jumbo/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-TlmpNv/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-wy28vF-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-TlmpNv/cryptography

**Comment by hynek** [comment]
That’s a [cryptography](https://cryptography.io/) error, not pyOpenSSL.  Check out their [install instructions](https://cryptography.io/en/latest/installation/) and feel free to ask them for help.
