### ISSUE TITLE
X509Name Unicode support

### ISSUE THREAD

**Issue by laurivosandi** [pyca/pyopenssl#386]
Hi, I've been playing around with pyOpenSSL for a while on Python3. There seems to be an issue with Unicode handling in X509Name wrapper on Python2 as well. Internally it seems to store values as ISO8859 strings and whenever for instance umlauts are placed in CN field it ends up encoded as ISO8859 in the certificate. I checked some other certificates under /etc/ssl/certs and they seem to use UTF-8 to encode foreign characters, so I guess latter should be the proper behaviour.

Code snippet that demonstrates the issue:

```
#!/usr/bin/env python3
# encoding: utf-8
s = "üks õlu päevas"

from OpenSSL import crypto
key = crypto.PKey()
key.generate_key(crypto.TYPE_RSA, 512)
csr = crypto.X509Req()
csr.set_pubkey(key)
csr.get_subject().CN= s

key, value = csr.get_subject().get_components()[0]

with open("blah.csr", "wb") as fh:
    fh.write(crypto.dump_certificate_request(crypto.FILETYPE_PEM, csr))

assert value == s.encode("utf-8"), "Sanity check failed"
```
This results assertion error on both Python 2 and 3:

```
Traceback (most recent call last):
  File "umlauts.py", line 18, in <module>
    assert value == s.encode("utf-8"), "Sanity check failed"
AssertionError: Sanity check failed
```

Dumping the certificate with openssl req -in blah.csr -text -noout:
```
Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: CN=\xFCks \xF5lu p\xE4evas
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (512 bit)
                Modulus:
                    00:d0:26:94:5d:f0:de:80:a7:9c:f9:5a:32:47:f0:
                    9a:4e:73:ce:8a:c1:24:54:23:8e:e8:e6:67:66:9d:
                    b4:31:39:a4:d4:99:e5:6f:60:38:5f:50:f9:43:50:
                    48:e6:13:d3:60:8c:01:1e:20:06:ee:0e:7f:a4:79:
                    d3:73:7d:75:d9
                Exponent: 65537 (0x10001)
        Attributes:
            a0:00
    Signature Algorithm: itu-t
```

Now attempting to decode bytestring from certificate:

```
localhost ~ $ python3
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> b"CN=\xFCks \xF5lu p\xE4evas".decode("iso8859")
'CN=üks õlu päevas'
```

**Comment by hynek** [comment]
Your example script works fine for me on both Python 3 and Python 2.

Could you double-check it hasn’t been fixed in master please?

**Comment by laurivosandi** [comment]
Hi, it's indeed fixed in the master. When can we expect it to be released on PyPI?

**Comment by hynek** [comment]
#383 and #384 are the main blockers ATM sadly I have not timeline for how long it’ll  take to fix them.
