### ISSUE TITLE
Access X509 fingerprint 

### ISSUE THREAD

**Issue by dobesv** [pyca/pyopenssl#389]
Currently you can fetch the X509 signature algorithm, but not the signature itself.

Note that you can probably recalculate the signature, which isn't super expensive, but doesn't seem as nice as just fetching it.

Possible workaround:

```
x509.digest(x509.get_signature_algorithm())
```

**Comment by alex** [comment]
We're not going to be expanding the x.509 API, if you want a more complete API you should use cryptography.
