### ISSUE TITLE
3 tests fail with MD5 in recent python/Fedora 23/OpenSSL

### ISSUE THREAD

**Issue by aalba6675** [pyca/pyopenssl#393]
Environment:
Fedora 23
openssl 1.0.2d
python 2.7.10

Test failures:
Clean git checkout of master 3 test failures with the same error. Is this expected? Location of failures:

X509ReqTests.test_sign
X509ReqTests.test_verify_success
NetscapeSPKITests.test_sign
E       Error: [('asn1 encoding routines', 'ASN1_item_verify', 'unknown message digest algorithm')]

Update: 
if I replace GOOD_DIGEST with SHA1, SHA256 455 passes
if I replace GOOD_DIGEST with SHA384: 3 errors
E       Error: [('rsa routines', 'RSA_sign', 'digest too big for rsa key'), ('asn1 encoding routines', 'ASN1_item_sign_ctx', 'EVP lib')]

Can we change tests/ to using SHA1 or SHA256?

**Comment by reaperhulk** [comment]
I believe MD5 may be disabled in Fedora 23's OpenSSL. The tests probably don't need to be run against an old and insecure algorithm like that, so we can look at updating it.

For SHA384 you're generating a 48 byte digest. Coupled with the necessary PKCS#1 v1.5 padding and the small key sizes in the tests that would explain the error you're seeing.

**Comment by aalba6675** [comment]
I submitted a pull request changing GOOD_DIGEST="SHA1", locally I have 455 tests passing.

Two CI jobs failed, unfortunately I couldn't decipher the error message, didn't seem to have anything to do with the commit.

**Comment by aalba6675** [comment]
Updated branch with coding convention fix.

**Comment by hynek** [comment]
I believe this is fixed.
