### ISSUE TITLE
Incorrect documentation for X509Req.get_subject

### ISSUE THREAD

**Issue by Hawk777** [pyca/pyopenssl#395]
The documentation for X509Req’s function get_subject has the following paragraph:

> This creates a new :py:class:`X509Name`: modifying it does not affect this request.

This appears to be false. I created a fresh X509Req, called get_subject(), assigned to the CN member of the returned object, signed the request, and dumped the request to a file. The `openssl req` command showed the subject field filled in accordingly. This makes sense, given that there otherwise is no other way to actually set the subject in the first place!

**Comment by Lukasa** [comment]
Yup, I can verify this too:

```python
>>> from OpenSSL import crypto
>>> r = crypto.X509Req()
>>> s = r.get_subject()
>>> s.C = b"GB"
>>> s.ST = b"London"
>>> s.L = b"London"
>>> s.O = b"hyper.org"
>>> s.OU = b"hyper.org"
>>> s.CN = b"hyper.org"
>>> print(s)
<X509Name object '/C=GB/ST=London/L=London/O=hyper.org/OU=hyper.org/CN=hyper.org'>
>>> s2 = r.get_subject()
>>> print(s2)
<X509Name object '/C=GB/ST=London/L=London/O=hyper.org/OU=hyper.org/CN=hyper.org'>
```

Looks like this part of the docstring is just entirely untrue.

**Comment by Lukasa** [comment]
This also affects `get_subject()` for the `X509` class.

**Comment by Lukasa** [comment]
And to `get_issuer()` for the `X509` class.
