### ISSUE TITLE
X509Name.get_components() should decode attribute's value

### ISSUE THREAD

**Issue by daa** [pyca/pyopenssl#399]
Currently `OpenSSL.crypto.X509Name.get_components()` makes string from raw attribute's value without performing any conversion, however `X509Name.__getattr__` converts asn1 string to utf8 representation and then decodes it in Python and returns unicode object. I think that for consistency both method should return the same values. But this inconsistency is not the worst - `_ffi.string()` stops on the first null byte which may be present if original value is encoded in utf-16 and it can lead to incomplete returned value. For example if certificate subject contains O="SomeOrg Орг" encoded in utf-16be, `get_components()` for this attribute will return `('O', '')` because value's byte representation will be `'\00S...'`.

If you don't have any objections, i'll prepare pull request changing this behaviour.

Just noticed that some projects - twisted for example - depend on `get_components()` value element being byte string, so I suggest not decoding to unicode object there but just translation to utf-8 encoded binary string.

**Comment by daa** [comment]
I've created example certificate which shows this issue:
```
>>> import OpenSSL.crypto
>>> with open('example-mbstring-cert.crt', 'rb') as f:
...     s = f.read()
... 
>>> c = OpenSSL.crypto.load_certificate(OpenSSL.crypto.FILETYPE_PEM, s)
>>> c.get_subject()
<X509Name object '/C=RU/CN=some-common-name/L=Any/O=\x00O\x00r\x00g\x00 \x04\x1E\x04@\x043/ST=Some/OU=some-ou'>
>>> c.get_subject().O
u'Org \u041e\u0440\u0433'
>>> c.get_subject().get_components()
[('C', 'RU'), ('CN', 'some-common-name'), ('L', 'Any'), ('O', ''), ('ST', 'Some'), ('OU', 'some-ou')]
```

[example-mbstring-cert.zip](https://github.com/pyca/pyopenssl/files/65236/example-mbstring-cert.zip)

As you can see `O` attribute is properly decoded to unicode but in `get_components()` it's not and is empty.

**Comment by hynek** [comment]
I’m afraid we can’t change the behavior of `OpenSSL.crypto.X509Name.get_components()` since that would break backward-compatibility (as you’ve noted yourself).

But the NUL byte thing ought to be fixed.

**Comment by daa** [comment]
NUL byte thing comes from bmpstring attribute type because binary representation of example is `\x00O\x00r\x00g\x00 \x04\x1E\x04@\x043` - as you can see there is 2 bytes per char and ascii letters start with zero byte. I hope that just translating strings to utf-8 encoding with the help of `_lib.ASN1_STRING_to_UTF8()` and leaving them as binary will not break anything, at least tests pass. Do you expect any compatibility issues with it?

**Comment by reaperhulk** [comment]
Our general policy at this point is to recommend the use of cryptography, which has far better X509 APIs and is a dependency pyOpenSSL needs anyway, to do everything related to X509: https://cryptography.io/en/latest/x509/reference/#
