### ISSUE TITLE
X509Extension("basicConstraints", True, "CA:TRUE, pathlen:0") raise TypeError: can't concat bytes to str

### ISSUE THREAD

**Issue by AlexandreRoba** [pyca/pyopenssl#403]
Dear all,

I'm having trouble using the X509Extension.

The following code
test = X509Extension("basicConstraints", True, "CA:TRUE, pathlen:0")
Raise the excpetion:
  File "/Users/alexandreroba/.virtualenvs/firstproxy/lib/python3.5/site-packages/OpenSSL/crypto.py", line 649, in __init__
    value = b"critical," + value

I tried to convert the "value" input string to a unicode string using:
test = X509Extension("basicConstraints", True, b"CA:TRUE, pathlen:0")
but this raise the following exception:
File "/Users/alexandreroba/.virtualenvs/firstproxy/lib/python3.5/site-packages/OpenSSL/crypto.py", line 651, in __init__
    extension = _lib.X509V3_EXT_nconf(_ffi.NULL, ctx, type_name, value)
TypeError: initializer for ctype 'char *' must be a bytes or list or tuple, not str

I'm using Python 3.5.  on a mac OS.

**Comment by reaperhulk** [comment]
You need to pass bytes for both the first arg and 3rd arg. `crypto.X509Extension(b"basicConstraints", True, b"CA:TRUE, pathlen:0")`

**Comment by AlexandreRoba** [comment]
Indeed. Thanks for this.
