### ISSUE TITLE
'X509certStore' object has no attribute '_store'

### ISSUE THREAD

**Issue by rhoerbe** [pyca/pyopenssl#405]
When validating a certificate against a custom list of trusted certificates X509certStore did not work:  

~~~~~
  x509storeContext = crypto.X509StoreContext(IDP_trustStore, cert.cert)
  File "/Users/admin/virtualenvs/pvzd34/lib/python3.4/site-packages/pyOpenSSL-15.2.0.dev0+rh0-py3.4.egg/OpenSSL/crypto.py", line 1499, in __init__
    self._init()
  File "/Users/admin/virtualenvs/pvzd34/lib/python3.4/site-packages/pyOpenSSL-15.2.0.dev0+rh0-py3.4.egg/OpenSSL/crypto.py", line 1507, in _init
    self._store_ctx, self._store._store, self._cert._x509, _ffi.NULL  # r2h2
AttributeError: 'X509certStore' object has no attribute '_store'
~~~~~

This occurs with 15.2.0.dev0 (line number above) and with 15.1.0.

I patched X509StoreContext._init() by referencing  self._store.store._store instead of  self._store._store. (See https://github.com/rhoerbe/pyopenssl)

I am not creating a pull request, because I could not get the unit tests running.

**Comment by sholsapp** [comment]
Is `X509certStore` something that you wrote? It doesn't appear in the pyOpenSSL codebase. This code is tested with `OpenSSL.crypto.X509Store` object, which makes me think that there might be something odd with your input trust store.

**Comment by rhoerbe** [comment]
Yes, [X509certStore](https://github.com/rhoerbe/PVZD/blob/master/PolicyManager/src/x509certStore.py) is my own class to import CA certs from a policy directory. Yes, I am a bit unsure whether this is a problem in pyOpenSSL, because I saw the unittest. But OTOH my code is doing nicely with the patch.

**Comment by rhoerbe** [comment]
I could try to isolate the behavior ..

**Comment by sholsapp** [comment]
Great. It sounds like this isn't a problem with pyOpenSSl at all (albeit, the `X509StoreContext` could be a bit more defensive and enforce some basic duck typing). If I were you I would ditch the X509certStore abstraction all together and just use the vanilla X509Store object. :smile: If that doesn't work, add a method that returns the X509Store object directly, and pass that to the X509StoreContext.

**Comment by rhoerbe** [comment]
thanks, I will try this

**Comment by rhoerbe** [comment]
You are right, I was loosing overview. Passing the X509certSore.store resolved the problem. 

Yes, the class could be more defensive, but you would have to write many asserts - this would hide the real code. Borrowing a bit of mixed static/dynamic typing from groovy would be nice in Python, that would allow type enforcement with little code.

Anyway, thank you for your support!
