### ISSUE TITLE
Cryptography 1.2 and Ubuntu 12.04.5 LTS (Travis)

### ISSUE THREAD

**Issue by bmw** [pyca/pyopenssl#407]
I believe this to be an issue with cryptography 1.2, but since I haven't had the time to verify this, I'm positing the issue here. With PyOpenSSL 0.15.1, cryptography 1.2 and OpenSSL 1.0.1, I get the following error:
```
crypto.load_privatekey(crypto.FILETYPE_PEM, open('rsa512_key.pem').read()).check()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-a086bb9f731b> in <module>()
----> 1 crypto.load_privatekey(crypto.FILETYPE_PEM, open('rsa512_key.pem').read()).check()

/letsencrypt/venv/local/lib/python2.7/site-packages/OpenSSL/crypto.pyc in check(self)
    241             raise TypeError("public key only")
    242 
--> 243         if _lib.EVP_PKEY_type(self._pkey.type) != _lib.EVP_PKEY_RSA:
    244             raise TypeError("key type unsupported")
    245 

AttributeError: '_cffi_backend.CDataGCP' object has no attribute 'type'
```

If I downgrade to cryptography 1.1.2, I do not have this problem.

**Comment by alex** [comment]
Yup, this was introduced in the cryptography release today, #406 resolve this, we're working on getting a release out now.

**Comment by bmw** [comment]
Great! Thanks for the quick response.

**Comment by bmw** [comment]
I can confirm the issue is resolved. Thanks again for such a quick fix guys.
