### ISSUE TITLE
CSR is missing the empty SET OF structure

### ISSUE THREAD

**Issue by rolandshoemaker** [pyca/pyopenssl#426]
CSRs created using the `dump_certificate_request` method and no CSR attributes do not contain the empty SET OF structure in the attributes field (in DER 0xa0 0x00) making the encoding is invalid.

With PyOpenSSL
```
[roland:~]$ cat pyca-csr.py
import OpenSSL

key_str = """..."""
domains = ["example.com"]

pkey = OpenSSL.crypto.load_privatekey(OpenSSL.crypto.FILETYPE_PEM, key_str)
req = OpenSSL.crypto.X509Req()
req.get_subject().CN = domains[0]
req.add_extensions([
    OpenSSL.crypto.X509Extension(
    "subjectAltName",
    critical=False,
    value=", ".join("DNS:%s" % d for d in domains)
  ),
])
req.set_pubkey(pkey)
req.sign(pkey, "sha256")

csr =  OpenSSL.crypto.dump_certificate_request(OpenSSL.crypto.FILETYPE_ASN1, req)
with open("pyca-csr.der", "w") as f:
	f.write(csr)
[roland:~]$ python pyca-csr.py
[roland:~]$ openssl req -in pyca-csr.der -inform der -noout -text
Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: CN=example.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    ...
                Exponent: 65537 (0x10001)
        Attributes: <-- missing empty SET OF
        Requested Extensions:
            X509v3 Subject Alternative Name: 
                DNS:example.com
    Signature Algorithm: sha256WithRSAEncryption
         ...
```

With OpenSSL
```
[roland:~]$ openssl req -new -nodes -subj '/CN=roland' -out openssl-csr.der -keyout test-key -newkey rsa:2048 -outform DER
Generating a 2048 bit RSA private key
....................................+++
.................................................+++
writing new private key to 'test-key'
-----
[roland:~]$ openssl req -in openssl-csr.der -inform der -noout -text                                      
Certificate Request:
    Data:
        Version: 0 (0x0)
        Subject: CN=roland
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    ...
                Exponent: 65537 (0x10001)
        Attributes:
            a0:00 <-- empty SET OF
    Signature Algorithm: sha256WithRSAEncryption
         ...
```

**Comment by rolandshoemaker** [comment]
Derp nevermind, I need to sleep more, Attributes == Extensions so this is right :)

**Comment by dreynolds** [comment]
@rolandshoemaker I am experiencing this, how did you solve it so that CSRs generated with pyopenssl have the empty SET OF attribute?

**Comment by renard** [comment]
@rolandshoemaker @dreynolds I am experiencing the same issue here:

Attributes *MUST* be:
```
                Exponent: 65537 (0x10001)
        Attributes:
            a0:00
    Signature Algorithm: sha256WithRSAEncryption
```
but pyOpenSSL generate a CSR with NO attribute at all:

```
                Exponent: 65537 (0x10001)
        Attributes:
        Requested Extensions:
```

If I understand correctly https://wiki.openssl.org/index.php/Manual:Req(1) the `SET OF Attribute` is required an must be `a0:00` if empty:

> by default the req command outputs certificate requests containing no attributes in the correct PKCS#10 format. However certain CAs will only accept requests containing no attributes in an invalid form: this option produces this invalid format. More precisely the Attributes in a PKCS#10 certificate request are defined as a SET OF Attribute. They are not OPTIONAL so if no attributes are present then they should be encoded as an empty SET OF. The invalid form does not include the empty SET OF whereas the correct form does. It should be noted that very few CAs still require the use of this option.

And from https://www.openssl.org/docs/man1.0.2/apps/req.html:

> [...] the SET OF is missing and the encoding is technically invalid (but it is tolerated). See the description of the command line option -asn1-kludge for more information.



Is there a way to correctly set the `SET OF Attributes`?



BTW I never had any issue with those generted certificates

**Comment by renard** [comment]
Nevermind I found my bug (PEBKAC): I added an empty list as extensions:

```
req.add_extensions(extensions)
```

`extensions` was `[]`.


Thus pyOpenSSL is OK.
