### ISSUE TITLE
SSL.Connection.state_string was removed without any warning

### ISSUE THREAD

**Issue by adiroiban** [pyca/pyopenssl#457]
0.13 used the have SSL.Connection.state_string

http://bazaar.launchpad.net/~exarkun/pyopenssl/master/view/156.1.1/OpenSSL/ssl/connection.c#L1090

It looks like it was converted to get_state_string, but without any warning.

Thanks for 16.0.0 release which fix the implementation!

**Comment by adiroiban** [comment]
Here is the code in https://github.com/pyca/pyopenssl/blob/v0.14a1/OpenSSL/SSL.py#L1244

I see that in master it was fixed https://github.com/pyca/pyopenssl/blob/master/src/OpenSSL/SSL.py#L1617

**Comment by adiroiban** [comment]
the changes of the API are here https://github.com/pyca/pyopenssl/commit/ea94f2bfd5d2a81e110f863793bdae967a1288f9 :)

**Comment by hynek** [comment]
Ugh so the API existed but was useless and nobody noticed?

I could imagine to add an alias but doesn't seem to warrant a release.

**Comment by adiroiban** [comment]
The API was working in 0.13 :)

I assume that nobody requiring this API was using 0.14 or 0.15 ... for example me :)

I searched this repo for state_string and I did not found any info so I thought that it should be good to report it.

Free free to close this... and maybe just update the notes in 16.1.0

Thanks!

**Comment by hynek** [comment]
Ha no it’s still a bug just not one that would deserve a regression release.  I think I’ll add an alias and deprecate it at the same time.

**Comment by alex** [comment]
This has been gone for so long, at this point adding it back would be more headache, Closing.
