### ISSUE TITLE
SSL_set_tlsext_host_name may not be present

### ISSUE THREAD

**Issue by reaperhulk** [pyca/pyopenssl#458]
https://github.com/pyca/pyopenssl/blob/master/src/OpenSSL/SSL.py#L1239 assumes the binding is available, but < 1.0.0 that is not true. We're dropping support for 0.9.8 in cryptography shortly, but we should probably fix this for pyOpenSSL 16.1 anyway.

This manifests as an AttributeError when using requests + pyOpenSSL in CentOS 5. /cc @Lukasa

**Comment by hynek** [comment]
I guess part of the solution should be Twisted + urllib3 builders.  Or for all I care, just append it to the existing 0.9.8 job.

**Comment by Lukasa** [comment]
Oh gross. Well, that's suitably terrible.

I'll provide a patch and test for this I guess.

**Comment by hynek** [comment]
*uses his new pointy poke stick on Cory*

**Comment by Lukasa** [comment]
So I've written some code that would treat this a bit like NPN/ALPN are treated: raise `NotImplementedError` when SNI isn't available.

However, I'm now a little bit confused. We have some tests that nominally use OpenSSL 0.9.8 (where cryptography should be not providing the extension) and that use the SNI APIs. However, that test passes suite passes on Travis CI. So...what's going on there?

**Comment by Lukasa** [comment]
Oh god, I see: it was actually introduced in 0.9.8f (version numbers, how do they work?). That means that we actually don't have a Travis run old enough to validate any tests I'd write for this function. @hynek, want me to add an *even older* OpenSSL to our test matrix?
