### ISSUE TITLE
FILETYPE_TEXT not permitted in dump_publickey

### ISSUE THREAD

**Issue by nikmon2** [pyca/pyopenssl#465]
It is however allowed for dump_certificate and dump_private_key.
- Only reporting this as the difference may not be intended.

Cheers,
niklas

  File "./my_ssl_key.py", line 101, in <module>
    print dump_publickey(FILETYPE_TEXT, my_pub)
  File "/opt/nimoCA/env/lib/python2.7/site-packages/OpenSSL/crypto.py", line 1657, in dump_publickey
    raise ValueError("type argument must be FILETYPE_PEM or FILETYPE_ASN1")

I just installed 16.0.0 on Ubuntu 14.04 and python 2.7.11 (venv):
Successfully installed cffi-1.6.0 cryptography-1.3.1 enum34-1.1.3 idna-2.1 ipaddress-1.0.16 pyasn1-0.1.9 pycparser-2.14 pyopenssl-16.0.0 six-1.10.0

**Comment by alex** [comment]
This is intended.
