### ISSUE TITLE
Deprecate backwards compatible type names

### ISSUE THREAD

**Issue by hynek** [pyca/pyopenssl#486]
Time to clean up: https://pyopenssl.readthedocs.io/en/stable/api/crypto.html#backwards-compatible-type-names

**Comment by alexwlchan** [comment]
I wouldn’t mind having a crack at this (apparently this was on the 16.1.0 milestone, which has long since passed?).

Start by raising a `DeprecationWarning` whenever you use one of the old type names?

**Comment by hynek** [comment]
yeah well…milestones are rather suggestions if nobody executes them ;)  i use it mostly as my wishlist what should be done.
