### ISSUE TITLE
Add support for DTLS

### ISSUE THREAD

**Issue by Paul-E** [pyca/pyopenssl#495]
It looks like an attempt to add DTLSv1 was added before in #29, but nothing ever came of it. There is currently not Python 3 supported implementation of DTLS that I am aware of.

**Comment by jarednm** [comment]
Has there been any work on this since?  I would like to use pyopenssl for DTLSv1.2

**Comment by CountablyInfinite** [comment]
Has there been any progress on this topic? Is there going to be support for DTLS 1.2 in pyopenssl? Are there any recommendations for other wirde spread python3 wrappers/libraries i could use? I am trying to build a simple DTLS 1.2 Client / Server utilizing PSKs, certificates  or raw public keys.

**Comment by kckeiks** [comment]
+1

**Comment by reaperhulk** [comment]
This was done in https://github.com/pyca/pyopenssl/pull/1026 and released in 22.0
