### ISSUE TITLE
Provide AES encryption & decription

### ISSUE THREAD

**Issue by johnlinp** [pyca/pyopenssl#513]
For example:

```
echo -n foo | openssl enc -aes-256-ctr -pass pass:q -base64
```

Is this functionality available in `pyopenssl`? Thanks!

**Comment by hynek** [comment]
No, pyOpenSSL aims to be a *thin* layer on top of OpenSSL.  It could be used for implementing what you want but if you just want to encrypt something safely, I’d suggest Fernet: https://cryptography.io/en/latest/fernet/

**Comment by johnlinp** [comment]
I see. I will check out Fernet later. Thank you.
