### ISSUE TITLE
Add quickstart section to documentation

### ISSUE THREAD

**Issue by Michael-F-Bryan** [pyca/pyopenssl#514]
As it stands, the documentation at https://pyopenssl.readthedocs.io/en/stable/ has a lot of details about how pyOpenSSL works under the hood, but there isn't much documenting _how_ to use the library. 

Would it be possible to write up a page that shows users how to make a basic client/server connection and using pyOpenSSL? I know there's a link to example code in the GitHub repo, but I feel like the official documentation should really have a "hello world" equivalent to using the library then defer to examples in the repo for more complex/real-world scenarios.

**Comment by hynek** [comment]
Yes I agree.  I believe the examples are simply from pre-Sphinx times.

**Comment by dholth** [comment]
No more examples in the repo.
