### ISSUE TITLE
OpenSSL 1.1.0 support

### ISSUE THREAD

**Issue by kislyuk** [pyca/pyopenssl#522]
OpenSSL 1.1.0 [is out](https://github.com/openssl/openssl/releases/tag/OpenSSL_1_1_0) with [lots of changes](https://github.com/openssl/openssl/blob/OpenSSL_1_1_0-stable/CHANGES#L9-L1066). This is to track support for it.

**Comment by alex** [comment]
@kislyuk The latest pyOpenSSL release + the latest cryptography release support OpenSSL 1.1.0 already :-)

**Comment by kislyuk** [comment]
Sweet, didn't realize that, thanks!
