### ISSUE TITLE
readthedocs and pypi changelogs for 16.1.0 are out of sync

### ISSUE THREAD

**Issue by larsbutler** [pyca/pyopenssl#527]
With the release of 16.1.0, it looks like the [note about the deprecation of OpenSSL 0.9.8](https://github.com/pyca/pyopenssl/pull/521) was not included with the original release. As a result, the  changelogs on readthedocs and pypi are out of sync. See:
- https://pyopenssl.readthedocs.io/en/stable/changelog.html#id1
- https://pypi.python.org/pypi/pyOpenSSL/16.1.0

The mention of the deprecation of OpenSSL 0.9.8 hasn't been propagated to these. This could lead to a lot of confusion.

**Comment by hynek** [comment]
yeah that’s because is has been added after the release.

**Comment by larsbutler** [comment]
I understand that. That's why I raised the issue.

**Comment by alex** [comment]
This is no longer an issue.
