### ISSUE TITLE
Session reuse does not work with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by tiran** [pyca/pyopenssl#528]
For some unknown reason, SSL session resumption does not work with OpenSSL 1.1.0. Wireshark confirms that OpenSSL 1.1.0 does not send a session id in its ClientHello. I have attached a demo script.

```
$ python sess.py 
('OpenSSL', '0x1000207f')
New session
Session reused
Session reused
$ venv/bin/python sess.py 
('OpenSSL', '0x1010000f')
New session
New session
New session
```

[sess.py.txt](https://github.com/pyca/pyopenssl/files/460127/sess.py.txt)

**Comment by tiran** [comment]
Wireshark session dump (first OpenSSL 1.0.2)
[session_pcap.zip](https://github.com/pyca/pyopenssl/files/460137/session_pcap.zip)

**Comment by tiran** [comment]
I'm pretty sure it's a bug in ```SSL_free()```. When I don't close the SSL connection and keep it around, session resumption works. I get the same result when I remove the call to ```SSL_free()``` in my own session branch for CPython's ssl module or when I use a BIO file to dump/restore the session. Something in ```SSL_free()``` renders a client session useless.

**Comment by tiran** [comment]
Python 3.6 has a workaround for OpenSSL 1.1.0. I'm using i2d/d2i to dump the session to DER and re-create it again.

**Comment by reaperhulk** [comment]
@tiran is there something we need to do in pyOpenSSL or is it a caller issue?
