### ISSUE TITLE
warning exposed by cffi-1.8.3

### ISSUE THREAD

**Issue by warner** [pyca/pyopenssl#544]
cffi-1.8.3 (released three days ago, on 17-Sep-2016) emits a new warning when casting 'char *' to a different type. pyOpenSSL-16.1.0 appears to trigger this warning:

```
.../lib/python2.7/site-packages/OpenSSL/crypto.py:1108:
UserWarning: implicit cast from 'char *' to a different pointer type: will be
forbidden in the future (check that the types are as you expect; use an
explicit ffi.cast() if they are correct)
```

I don't think pyOpenSSL made any recent changes: instead I think this problem has been around for a while, and cffi is only just now noticing it.

The `crypto.py` code in question looks like:

```python
        result_buffer = _ffi.new("char[]", _lib.EVP_MAX_MD_SIZE)
        result_length = _ffi.new("unsigned int[]", 1)
        result_length[0] = len(result_buffer)

        digest_result = _lib.X509_digest(
            self._x509, digest, result_buffer, result_length)
```

**Comment by reaperhulk** [comment]
We've fixed these issues in cryptography and bcrypt, makes sense we'd have them here (and probably pynacl as well).

**Comment by reaperhulk** [comment]
Do you have the warning you can add to this issue?

**Comment by warner** [comment]
Ugh, I hit the wrong button, and submitted the issue without the rest of my comment. Thought I could get away with it too, editing it before anyone noticed, but you're too fast, man!

**Comment by reaperhulk** [comment]
👍 cool, we'll get this fixed for the next release.
