### ISSUE TITLE
Version 0.14 is still tagged as 'latest release' on Github

### ISSUE THREAD

**Issue by eli-b** [pyca/pyopenssl#549]
Version 0.14 is still tagged as 'latest release' on Github.
Is this intentional? Are the newer versions not stable?

**Comment by alex** [comment]
No, they are. Unfortunately github only shows something under releases if you use that feature. If you just perform a normal `git tag` it doesn't get the fancy treatment. Not sure how to resolve this.

**Comment by hynek** [comment]
Sadly it only accepts markdown and our changelog is in reST.  I guess we could just add a link to the changelog for each release?

**Comment by reaperhulk** [comment]
Deleted the releases and now just the tags are showing: https://github.com/pyca/pyopenssl/releases

Closing as fixed
