### ISSUE TITLE
pyOpenSSL uses UCS2, not UCS4. Can I force it to use UCS4?

### ISSUE THREAD

**Issue by Geremia** [pyca/pyopenssl#554]
I am using pyOpenSSL 16.1.0, and I get this error:
```
>>> import OpenSSL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
ImportError: /usr/lib64/python2.7/site-packages/OpenSSL/crypto.so: undefined symbol: PyUnicodeUCS2_Decode
```
My `python` is built using UCS4:
```
>>> import sys
>>> print sys.maxunicode
1114111
```
whereas `pyOpenSSL` appears to be expecting UCS2. Is there a way to force `pyOpenSSL` to use UCS4?

Also:
```
>>> import ssl
>>> print ssl.OPENSSL_VERSION
OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by reaperhulk** [comment]
This looks like a very out of date version of pyOpenSSL and not version 16.1 (which does not have a `crypto.so`). Can you confirm your version?

**Comment by Geremia** [comment]
@reaperhulk Ah, I think I had a packaging issue.
```
ls -l /usr/lib64/python2.7/site-packages/OpenSSL/crypto.so
```
says Oct 14  2013!

thanks

**Comment by Geremia** [comment]
@reaperhulk Ah, I think I had a packaging issue.
```
ls -l /usr/lib64/python2.7/site-packages/OpenSSL/crypto.so
```
says Oct 14  2013!

thanks

**Comment by alex** [comment]
Closing as it's not a pyOpenSSL bug.
