### ISSUE TITLE
TypeError("Last argument must be string or callable")

### ISSUE THREAD

**Issue by nvasion** [pyca/pyopenssl#572]
I am getting an error when trying to pass a passphrase to dump_privatekey the password is a string so I have no idea what this is or how to fix it.

    File "/usr/local/lib/python3.4/site-packages/OpenSSL/crypto.py", line 1752, in dump_privatekey
       helper.callback, helper.callback_args)
    File "/usr/local/lib/python3.4/site-packages/OpenSSL/crypto.py", line 2477, in callback
       raise TypeError("Last argument must be string or callable")
    TypeError: Last argument must be string or callable

My code below. And the password is 'test', which is a string.

            with open('CA/ca.{0}.key'.format(env), 'w') as capkey:
                    capkey.write(
                        crypto.dump_privatekey(crypto.FILETYPE_PEM, ca_key_pair, passphrase=password).decode('utf-8')
                    )

If anyone has fixed this issue please let me know. I am using 16.2.0.

**Comment by Lukasa** [comment]
Sorry, this error message is a bit unclear: it should read "Last argument must be a *bytestring* or callable". If you do `password.encode('ascii')` that should resolve your issue.

**Comment by nvasion** [comment]
Yup that fixed it. Thank awesome! Just an FYI if anyone comes across this in the future you must have the .decode('utf-8') at the end of dump otherwise it will throw out an, **TypeError: must be str, not bytes**
