### ISSUE TITLE
pyopenssl is missing the possibility to read CSR Attributes ?

### ISSUE THREAD

**Issue by AnthonyDeroche** [pyca/pyopenssl#604]
Hello,

I'm trying to read custom attributes embedded in CSR with the lib and I'm not able to do so. 

Attributes are display by openssl -req [...] -text just before the "requested extensions" section and after the "subject public key info" section.

There is a getter named "X509_REQ_get_attr" in the C code of openssl, so I assume it is possible to get them easily using appropriate binding.

Any help would be great! 

Thanks

**Comment by horazont** [comment]
You should take a look at the [pyasn1 module](https://pypi.python.org/pypi/pyasn1). It can be used to read the data format in which CSRs are stored and you should be able to do what you want with that.

**Comment by AnthonyDeroche** [comment]
Thanks for the advice. I will take a look at pyasn1. This issue can be closed unless you want to keep track of proposals.
