### ISSUE TITLE
Broken Extensions Link in Docs

### ISSUE THREAD

**Issue by brettf** [pyca/pyopenssl#610]
On this page in the docs:
http://www.pyopenssl.org/en/stable/api/crypto.html?highlight=extensions#x509extension-objects
...the description:
>  **type_name (bytes)** – The name of the type of *extension* to create.

...has a broken link on the word "extension". 
> Broken: https://www.openssl.org/docs/manmaster/apps/x509v3_config.html#STANDARD-EXTENSIONS

I believe the new correct one should be:
> Correct: https://www.openssl.org/docs/manmaster/man5/x509v3_config.html#STANDARD-EXTENSIONS

**Comment by alexwlchan** [comment]
Thanks for reporting this! I’ll put up a patch shortly.
