### ISSUE TITLE
Question: howto implement TLS over TLS tunnel?

### ISSUE THREAD

**Issue by phuslu** [pyca/pyopenssl#613]
**Background**
TLS over TLS tunnel is a real scene when user visit https website through a https proxy. [1] [2]
And I'm manage to implement https proxy support for python libs.

**Known Issues**
Python stdlib has trouble to implement the https proxy support, see [3] [4]

**State**
I switch to tlslite-ng [5] and added https proxy support to requests, see [6]

**Question**
I also try to implement it by pyopenssl, but failed. Here is my code
```
>>> import OpenSSL
>>> import socket
>>> sock = socket.create_connection(('bwg.phus.lu',443))
>>> conn = OpenSSL.SSL.Connection(OpenSSL.SSL.Context(OpenSSL.SSL.TLSv1_2_METHOD), sock)
>>> conn.set_connect_state()
>>> conn.do_handshake()
>>> conn.sendall('CONNECT httpbin.org:443 HTTP/1.1\r\nHost: httpbin.org\r\n\r\n')
>>> conn.recv(1024)
'HTTP/1.1 200 OK\r\n\r\n'
>>> conn2 = OpenSSL.SSL.Connection(OpenSSL.SSL.Context(OpenSSL.SSL.TLSv1_2_METHOD), conn)
>>> conn2.set_connect_state()
>>> conn2.do_handshake()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    conn2.do_handshake()
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1426, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 1174, in _raise_ssl_error
    _raise_current_error()
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('SSL routines', 'ssl3_read_bytes', 'unknown alert type')]
```
How can I make above code work as expected? Thank you!

[1] https://www.chromium.org/developers/design-documents/secure-web-proxy
[2] https://daniel.haxx.se/blog/2016/11/26/https-proxy-with-curl/
[3] http://bugs.python.org/issue29610
[4] http://bugs.python.org/issue29394
[5] https://github.com/tomato42/tlslite-ng
[6] https://pypi.python.org/pypi/requests-httpsproxy

**Comment by Lukasa** [comment]
Almost certainly you'd have to do TLS-over-TLS tunnelling by using memory BIOs for the inner connection, not wrapping sockets. You do that by [creating a `Connection` object with a `None` socket](https://pyopenssl.readthedocs.io/en/stable/api/ssl.html#OpenSSL.SSL.Connection) and then using the `bio_read`, `bio_write`, `bio_shutdown` methods.

**Comment by phuslu** [comment]
Thank you!

I still not sure when to `creating a Connection object with a None socket`

1. first layer, connect to https proxy
2. sencond layer, do ssl handshake against target server

Which layer connection should I use memory BIOs ?

**Comment by alex** [comment]
Use memory bios everywhere.
