### ISSUE TITLE
ETA for the next release.

### ISSUE THREAD

**Issue by genxstylez** [pyca/pyopenssl#614]
As titled~

https://github.com/SilentCircle/iap-local-receipt/pull/2 is dependent on the next release

**Comment by hynek** [comment]
I wanted to add more stuff but everyone is busy so I think we can call it a day and push out what we have. 

Objections anyone?  @reaperhulk @alex @alexwlchan

**Comment by reaperhulk** [comment]
I'm fine with a release. There's quite a bit in there.

**Comment by alexwlchan** [comment]
> I think we can call it a day and push out what we have.

No objections from me.

I’m working on #602 and #605 this morning, but I don’t know how long it will take to finish and get reviewed.

**Comment by hynek** [comment]
Neither is a blocker, so no rush.

**Comment by genxstylez** [comment]
@hynek sounds good! looking forward!

**Comment by hynek** [comment]
17.0.0 is on PyPI now
