### ISSUE TITLE
pyOpenSSL 17.0.0 can't init for context

### ISSUE THREAD

**Issue by xux1217** [pyca/pyopenssl#619]
hi,

  I meet a error in scrapy when I upgrade pyOpenSSL to 17.0.0. I find this statement in SSL.py:614
res = _lib.SSL_CTX_set_ecdh_auto(context, 1)  is return 0, and raise a none error. This error detail is below.

  I tried to degrade pyOpenSSL to 16.2.0 is ok.

  My Python is 3.4, and I find the test of pyOpenSSL 17.0.0 is faild in python3.4 but succ in python 3.6, so I tried to upgrade python to 3.6, and it still error.

-------------error detail ----------------------

```
  File "/home/xuxiao/.virtualenvs/bishe/lib/python3.4/site-packages/twisted/internet/_newtls.py", line 21, in <module>
    **from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol**

  File "/home/xuxiao/.virtualenvs/bishe/lib/python3.4/site-packages/twisted/protocols/tls.py", line 45, in <module>
    **Connection(Context(TLSv1_METHOD), None)**

  File "/home/xuxiao/.virtualenvs/bishe/lib/python3.4/site-packages/OpenSSL/SSL.py", line 614, in __init__
    **_openssl_assert(res == 1)**

  File "/home/xuxiao/.virtualenvs/bishe/lib/python3.4/site-packages/OpenSSL/_util.py", line 67, in openssl_assert
    **exception_from_error_queue(error)**

  File "/home/xuxiao/.virtualenvs/bishe/lib/python3.4/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    **raise exception_type(errors)**
OpenSSL.SSL.Error: []
```

**Comment by hynek** [comment]
- what OS are you running?
- what OpenSSL version?
- what cryptography version?
- does upgrading cryptography help?

**Comment by xux1217** [comment]
I use Gentoo.
the Openssl version is "OpenSSL 1.0.2k  26 Jan 2017".
And cryptography version is 1.8.1.

My installation step is:
1. mkproject test -p python3.4
2. pip install pyOpenSSL

**Comment by hynek** [comment]
@reaperhulk any idea? :|

**Comment by reaperhulk** [comment]
Were we calling this method during startup in 16.2?

**Comment by hynek** [comment]
No, it’s new: https://github.com/pyca/pyopenssl/pull/575  And I’m only pestering you because it’s your PR. :)

I wonder if there’s some weirdness about return codes or something?  The  empty Error is weird (especially because IIRC we fixed something in that regard).

**Comment by reaperhulk** [comment]
Could you provide your `opensslconf.h`? The only way I can see this failing is if some strange compile flag (like NO_ECDH) is set.

**Comment by xux1217** [comment]
[opensslconf.h.txt](https://github.com/pyca/pyopenssl/files/1206702/opensslconf.h.txt)
this is the opensslconf.h that I use.
sorry for just to provide this file.

**Comment by reaperhulk** [comment]
And indeed:

```
#ifndef OPENSSL_NO_ECDH
# define OPENSSL_NO_ECDH
#endif
```

Did you compile this OpenSSL yourself? What OS/distribution are you on?

**Comment by xux1217** [comment]
I use gentoo. The USE of emerge is below. 
`
dev-libs/openssl-1.0.2k::gentoo  USE="asm bindist sslv3 tls-heartbeat zlib -gmp -kerberos -rfc3779 -sctp -sslv2 -static-libs {-test} -vanilla" ABI_X86="(64) -32 (-x32)" CPU_FLAGS_X86="(sse2)" 5,185 KiB
`
I think if I open the ECDH, it would fix? Sometimes I will try.

**Comment by reaperhulk** [comment]
Yeah we don't support OpenSSL built without ECDH, so you'll want to rebuild for that. I'm going to go ahead and close this, but if you still have an issue after recompile please comment/reopen.
