### ISSUE TITLE
Verify CRL against Issuer CA

### ISSUE THREAD

**Issue by hdan1** [pyca/pyopenssl#627]
Hi,
Can you implement a feature to verify the CRL signature against the CA that signed the CRL ?

Like the openssl command:
openssl crl -in file.crl -inform der -CAfile file.cer

**Comment by adiroiban** [comment]
I don't know if this should be done in pyopenssl as pyopenssl should not touch the network... or assume any network transport or disk access

I am using this code for CDP/CRL validations based on twisted  and using the `pem` module
https://gist.github.com/adiroiban/d4af3aa243924609cd54e504b9fa2895 

It would help if pyopenssl could provide the primitives required to implement this.
There is some ugly code in x509.py which would be nice to be replaced by direct pyopenssl calls.

I think that the story is similar for OCSP (stapling)
