### ISSUE TITLE
PKCS12 documentation seems to be unclear/out of date

### ISSUE THREAD

**Issue by ilanponimansky** [pyca/pyopenssl#687]
I was looking to make a pfx to pem converter using this library. The official documentation [here](https://pyopenssl.org/en/stable/api/crypto.html#pkcs12-objects) does not properly convey how to use this library for that purpose. 

The documentation for the PKCS12 function does not work with Python3.
`OpenSSL.crypto.load_pkcs12(buffer[, passphrase])`

Python3 expects an empty string  before the passphrase i.e 

`OpenSSL.crypto.load_pkcs12(buffer['', passphrase])`

However this does not work either. 

The fastest and most pythonic way to accomplish this task is with the following example code

    with open(file, 'rb') as pfx:

        pem_converter = crypto.load_pkcs12(pfx.read(), password)

        pem_key = crypto.dump_privatekey(crypto.FILETYPE_PEM, pem_converter.get_privatekey())

        pem_cert = crypto.dump_certificate(crypto.FILETYPE_PEM, pem_converter.get_certificate())

What do you guys think? It seems some of the PKCS12 section will need to be rewritten which I am happy doing assuming this change makes sense.

**Comment by reaperhulk** [comment]
I think you may have misunderstood the documentation (or I'm misunderstanding your issue).

`OpenSSL.crypto.load_pkcs12(buffer[, passphrase])` is a syntax saying you must pass the buffer, but the second argument is entirely optional. So it is permissible to call it like `OpenSSL.crypto.load_pkcs12(buffer)` if there is no password and `OpenSSL.crypto.load_pkcs12(buffer, password)` if there is a password (although you can also pass `None`).

Your code is correct, but the pyopenssl docs appear to also be correct.

**Comment by ilanponimansky** [comment]
Thanks for the response. So is the syntax of [, passphrase] understood to mean "passphrase is optional, if it exists then separate it with a comma"?

**Comment by reaperhulk** [comment]
Exactly

**Comment by ilanponimansky** [comment]
Okay noted. Thanks for the help. Hopefully the next confused person will stumble on this post and will save some time.
