### ISSUE TITLE
Is it possible to generate private key with passphrase

### ISSUE THREAD

**Issue by wake69** [pyca/pyopenssl#688]
I have been looking at all the documentation, i am trying to add a passphrase to key generation similar to openssl. 

I have tried:
key = crypto.PKey()
key.generate_key(type, bits)
f = open(_keyfile, "w"
f.write(crypto.dump_privatekey(crypto.FILETYPE_PEM, key, passphrase='foo_bar'))
f.close()

When i try to access the key, there is no passphrase prompt and i can read the file. 

Is this functionality elsewhere?

**Comment by reaperhulk** [comment]
It appears you need to pass a cipher in addition to a passphrase. If cipher is None then it silently won't encrypt it. (This is a bad API, sorry)

If you don't need TLS I'd suggest just using https://github.com/pyca/cryptography (which pyOpenSSL depends on). It has a much better API for asymmetric cryptography (docs: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/).
