### ISSUE TITLE
ImportError: No module named OpenSSL however it's installed!!

### ISSUE THREAD

**Issue by x-cod3r** [pyca/pyopenssl#689]
## OS Information (Linux flavor, Python version)

Linux parrot 4.11.0-parrot6-amd64 #1 SMP Parrot 4.11.6-1parrot6 (2017-06-28) x86_64 GNU/Linux

```
python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
``` 

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

While running as root:

```
./empire
Traceback (most recent call last):
  File "./empire", line 7, in <module>
    from OpenSSL import SSL 
ImportError: No module named OpenSSL
```

## Screenshot of error, embedded text output, or Pastebin link to the error

![screenshot at 2017-09-04 23-04-22](https://user-images.githubusercontent.com/301220/30058177-ba2e907a-9231-11e7-8c4f-676b14efcc15.png)

## Any additional information
this problem keeps happening each time I try to import SSL from OpenSSL

![screenshot at 2017-09-04 23-14-45](https://user-images.githubusercontent.com/301220/30058266-2e5b9a9c-9232-11e7-891e-97400037081a.png)

**Comment by alexwlchan** [comment]
It looks like PyOpenSSL is installed globally, but perhaps `empire` is running a different Python? (Although that wouldn’t explain why OpenSSL is missing in the interactive console.)

What happens if you try `python empire`? Can you show us the first few lines of that file?

**Comment by x-cod3r** [comment]
@alexwlchan  
I tried, I got the same result.

#screen 
https://drive.google.com/open?id=0BxpOdHw25YM_dWNmdkpkZ211TDQ

**Comment by x-cod3r** [comment]
@alexwlchan
I tried, I got the same result.

![screenshot at 2017-09-05 13-15-54](https://user-images.githubusercontent.com/15794284/30059446-2b482b88-920d-11e7-9862-71b93942e02b.png)

**Comment by x-cod3r** [comment]
@alexwlchan  

Thank you sir for trying to help, I have just rescued myself before the issue get massy hehe and installed ubntu,got some probelms at first, but, finally, it works! this saves time hehe

![screenshot from 2017-09-05 22-53-00](https://user-images.githubusercontent.com/15794284/30083175-cc90164c-928d-11e7-933c-8a35778946c9.png)

**Comment by alexwlchan** [comment]
Glad to hear it’s working now. Hope things continue in the same fashion.

**Comment by milnomada** [comment]
Upgrading solved my issue:
`pip install pyOpenSSL --upgrade `

**Comment by scsmla** [comment]
I have the same issue, here is result of `env | grep PATH`

> XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
PATH=/home/duy/bin:/home/duy/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/usr/local/go/bin:/home/duy/.local/bin/:/usr/local/bin/python:/usr/local/lib/python3.5
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
PYTHONPATH=/usr/local/lib/python3.5
COMPIZ_BIN_PATH=/usr/bin/
GOPATH=/home/duy/go_projects

Currently, I still have no solution for it.

**Comment by tomas7470** [comment]
it could be that you have installed it for python3.#..
try this:
`sudo apt-get install python-openssl`

**Comment by Ichhakhemka** [comment]
I have the same issue, here is result of env | grep PATH 

PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Library/Android/sdk/emulator:/Users/Library/Android/sdk/tools:/Users/Library/Android/sdk/tools/bin/:/Users/Library/Android/sdk/platform-tools:/Library/Python/2.7/site-packages
PYTHONPATH=/Users/automation_framework:/Library/Python/2.7/site-packages/PIL:/Library/Python/2.7/site-packages

Also when doing : OpenSSL version
getting : OpenSSL version
