### ISSUE TITLE
major version updates of dependencies can break pyopenssl

### ISSUE THREAD

**Issue by jo-tham** [pyca/pyopenssl#697]
Hi,

I came across in issue and wonder if the maintainers would be interested in resolving it  (or contributions to resolve it) for future releases

The project requirements don't set a maximum version, which causes OpenSSL module to fail if the requirements have new major version releases

Minimal working example:

```
mkdir test
cd test
virtualenv venv
. venv/bin/activate
pip install pyopenss==0.15
python
```

```
>>> from OpenSSL import crypto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joth/projects/ad-hoc/test-pyopenssl-deps/venv/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/joth/projects/ad-hoc/test-pyopenssl-deps/venv/lib/python3.6/site-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: module 'lib' has no attribute 'SSL_ST_INIT'
```

Environment

```
(venv) joth@smtp:~/test$ dpkg -l openssl
||/ Name                      Version           Architecture      Description
+++-=========================-=================-=================-========================================================
ii  openssl                   1.0.1f-1ubuntu2.2 amd64             Secure Sockets Layer toolkit - cryptographic utility

(venv) joth@smtp:~/test$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

```

I can work around it by specifying in my projects requirements that `cryptography>=1,<2`

But I think it's conventional that such a specification happen in the package which directly requires the dependency

Kind of relates to #419, which bumped the minimum version; I think at the same time it should have limited it to <2

I'm guessing things are working at the current version of pyopenssl, but if cryptography went to 3.0 it could break as demonstrated above 

Thanks for your thoughts

**Comment by hynek** [comment]
I’m not comfortable to set a max version because just because cryptography considers something breaking, doesn’t mean necessarily that it breaks pyOpenSSL.  OTOH it might cut pyOpenSSL off of security updates that may land later since apart from the last 2.6 release, cryptography doesn't maintain multiple branches.

**Comment by jo-tham** [comment]
Thanks for reflecting. I'm not quite conivinced! But perhaps some more people will comment and I'll defer to the experience of the crowd.
