### ISSUE TITLE
OpenSSL/rand.py: implicit cast from char *: use ffi.cast()

### ISSUE THREAD

**Issue by RalphCorderoy** [pyca/pyopenssl#698]
Debian 8.9, Jessie, with python-openssl 16.0.0-1\~bpo8+1, and certbot 0.10.2-1\~bpo8+1.
The cron job to renew LetsEncrypt certificates is no longer silent the majority of the time.

    /usr/lib/python2.7/dist-packages/OpenSSL/rand.py:58: UserWarning: 
    implicit cast from 'char *' to a different pointer type: will be 
    forbidden in the future (check that the types are as you expect; use
    an explicit ffi.cast() if they are correct)
        result_code = _lib.RAND_bytes(result_buffer, num_bytes)

https://github.com/certbot/certbot/issues/4679 is related.

**Comment by alex** [comment]
This code does not exist in the most recent version of pyOpenSSL.

Just to complete debugging, can you edit that line of code on your system to add ` pdb.set_trace()` and see what the full backtrace is?

**Comment by RalphCorderoy** [comment]
This is the first time it stops there. It stops a few more times if I `c` to continue.

      /usr/bin/certbot(11)<module>()
    -> load_entry_point('certbot==0.10.2', 'console_scripts', 'certbot')()
      /usr/lib/python2.7/dist-packages/certbot/main.py(849)main()
    -> return config.func(config, plugins)
      /usr/lib/python2.7/dist-packages/certbot/main.py(655)renew()
    -> renewal.handle_renewal_request(config)
      /usr/lib/python2.7/dist-packages/certbot/renewal.py(413)handle_renewal_request()
    -> main.obtain_cert(lineage_config, plugins, renewal_candidate)
      /usr/lib/python2.7/dist-packages/certbot/main.py(626)obtain_cert()
    -> action, _ = _auth_from_available(le_client, config, domains, certname, lineage)
      /usr/lib/python2.7/dist-packages/certbot/main.py(103)_auth_from_available()
    -> renewal.renew_cert(config, domains, le_client, lineage)
      /usr/lib/python2.7/dist-packages/certbot/renewal.py(296)renew_cert()
    -> new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
      /usr/lib/python2.7/dist-packages/certbot/client.py(262)obtain_certificate()
    -> self.config.allow_subset_of_names)
      /usr/lib/python2.7/dist-packages/certbot/auth_handler.py(73)get_authorizations()
    -> resp = self._solve_challenges()
      /usr/lib/python2.7/dist-packages/certbot/auth_handler.py(111)_solve_challenges()
    -> resp = self.auth.perform(self.achalls)
      /usr/lib/python2.7/dist-packages/certbot_apache/configurator.py(1743)perform()
    -> sni_response = chall_doer.perform()
      /usr/lib/python2.7/dist-packages/certbot_apache/tls_sni_01.py(76)perform()
    -> responses.append(self._setup_challenge_cert(achall))
      /usr/lib/python2.7/dist-packages/certbot/plugins/common.py(250)_setup_challenge_cert()
    -> cert_key=cert_key)
      /usr/lib/python2.7/dist-packages/certbot/achallenges.py(55)response_and_validation()
    -> self.account_key, *args, **kwargs)
      /usr/lib/python2.7/dist-packages/acme/challenges.py(206)response_and_validation()
    -> self.validation(account_key, *args, **kwargs))
      /usr/lib/python2.7/dist-packages/acme/challenges.py(519)validation()
    -> return self.response(account_key).gen_cert(key=kwargs.get('cert_key'))
      /usr/lib/python2.7/dist-packages/acme/challenges.py(430)gen_cert()
    -> 'dummy', self.z_domain.decode()], force_san=True), key
      /usr/lib/python2.7/dist-packages/acme/crypto_util.py(211)gen_ss_cert()
    -> cert.set_serial_number(int(binascii.hexlify(OpenSSL.rand.bytes(16)), 16))
    > /usr/lib/python2.7/dist-packages/OpenSSL/rand.py(60)bytes()
    -> result_code = _lib.RAND_bytes(result_buffer, num_bytes)

**Comment by alex** [comment]
It looks like this line is removed in the latest version of ACME, which will hopefully be released soon: https://github.com/certbot/certbot/pull/5112

I'm going to close this as there's nothing more for us to do here, since the code is deleted. Thanks for the detailed report though!
