### ISSUE TITLE
Regression in X509Req dump function

### ISSUE THREAD

**Issue by geektophe** [pyca/pyopenssl#700]
Hello,

There seem to be a regression in `OpenSSL.crypto.dump_certificate_request` function.

Up to Ubuntu Xenial, a dumped CSR under the PEM format cannot be decoded/imported. It was working under Ubuntu Trusty.

Here's examples under both distributions:

**Under Trusty**

    >>> import OpenSSL
    >>> OpenSSL.__version__
    '0.13'
    >>> from OpenSSL import crypto
    >>> skey = crypto.PKey()
    >>> skey.generate_key(crypto.TYPE_RSA, 2048)
    >>> csr = crypto.X509Req()
    >>> csr.get_subject().CN = "test-01.example.com"
    >>> csr.get_subject().C = "US"
    >>> csr.get_subject().ST = "State"
    >>> csr.get_subject().L = "Dummy locality"
    >>> csr.get_subject().OU = "Dummy OU"
    >>> csr.get_subject().emailAddress = "test-01@example.com"
    >>> csr.set_pubkey(skey)
    >>> csrpem = crypto.dump_certificate_request(crypto.FILETYPE_PEM, csr)
    >>> crypto.load_certificate_request(crypto.FILETYPE_PEM, csrpem)
    <X509Req at 0x7f6b0a9c7070>

**Under Xenial**

    >>> import OpenSSL
    >>> OpenSSL.__version__
    '0.15.1'
    (same as above)
    >>> crypto.load_certificate_request(crypto.FILETYPE_PEM, csrpem)
        Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 2380, in load_certificate_request
        _raise_current_error()
      File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
        raise exception_type(errors)
    OpenSSL.crypto.Error: [('asn1 encoding routines', 'c2i_ASN1_OBJECT', 'invalid object encoding'), ('asn1 encoding routines', 'ASN1_TEMPLATE_NOEXP_D2I', 'nested asn1 error'), ('asn1 encoding routines', 'ASN1_TEMPLATE_NOEXP_D2I', 'nested asn1 error'), ('PEM routines', 'PEM_ASN1_read_bio', 'ASN1 lib')]

Loading a CSR generated by `openssl req` does not raise this error:

    $ openssl req -new -nodes -out csr.pem
    Generating a 2048 bit RSA private key
    ................+++
    ...........+++
    writing new private key to 'privkey.pem'
    -----
    You are about to be asked to enter information that will be incorporated
    into your certificate request.
    What you are about to enter is what is called a Distinguished Name or a DN.
    There are quite a few fields but you can leave some blank
    For some fields there will be a default value,
    If you enter '.', the field will be left blank.
    -----
    Country Name (2 letter code) [AU]:US
    State or Province Name (full name) [Some-State]:Dummy state
    Locality Name (eg, city) []:Dummy locality
    Organization Name (eg, company) [Internet Widgits Pty Ltd]:Dummy organization
    Organizational Unit Name (eg, section) []:Dummy OU
    Common Name (e.g. server FQDN or YOUR name) []:test-01.example.com
    Email Address []:test-01@example.com

    Please enter the following 'extra' attributes
    to be sent with your certificate request
    A challenge password []:
    An optional company name []

    >>> from OpenSSL import crypto
    >>> with open("csr.pem", "r") as f: csrpem = f.read()
    >>> crypto.load_certificate_request(crypto.FILETYPE_PEM, csrpem)
    <OpenSSL.crypto.X509Req object at 0x7ff92f828790>

The problem is still present with a fresh pyOpenSSL module installed via `pip` (version `17.3.0`)

Am I wrong anywhere, or is it really a regression introduced between the `0.13` and the `0.15` releases ?

From what I can see, `dump_certificate_request` uses `PEM_write_bio_X509_REQ` through cryptography. There's  chances something changed in it or if the libssl version installed up to xenial.

Many thanks !

**Comment by alex** [comment]
Can you include a copy of the CSR file that fails to load?

**Comment by geektophe** [comment]
Sure :)

Here's a `dump_certificate_request` result generated using the procedure described above:

    -----BEGIN CERTIFICATE REQUEST-----
    MIIBxDCCAbkCAQAwgYsxHDAaBgNVBAMME3Rlc3QtMDEuZXhhbXBsZS5jb20xCzAJ
    BgNVBAYTAlVTMQ4wDAYDVQQIDAVTdGF0ZTEXMBUGA1UEBwwORHVtbXkgbG9jYWxp
    dHkxETAPBgNVBAsMCER1bW15IE9VMSIwIAYJKoZIhvcNAQkBFhN0ZXN0LTAxQGV4
    YW1wbGUuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxQCYWWkL
    uyIB5dty5UnblzeH3wEvB+A5wrnGCBbQ1OW91rXmLUVOpRTAca9fdc1DqjDLHMbB
    mkPxq2Q8uw0xhYS1CskSsqu2HULq2POklXsbGqJv1LLeyuj8lxlJKSZiJ99KwZTg
    jIfQcKoUMgv70HIxfms8nMUCYq/Mm4LyhBqAu/FKSXy84G66dH3UaA1HAsNN01Ht
    MNoWsygFpH1mhojoezMtcPp9y/zZgzAabhSaSksPwzEzXTkn1qQIyNrVXiRHxJPY
    znbdT3pOgkLSvmt65Zv+Eu/uRCvFPf1k0OG18U1o20iBJqP5/41kf3fp/jjuMzEA
    kLrgDgYpYHM20wIDAQABoAAwAgYAAwEA
    -----END CERTIFICATE REQUEST-----

Here are the versions of the libraries involved:

    libc6:amd64            2.23-0ubuntu7
    libssl1.0.0:amd64      1.0.2g-1ubuntu4.6
    python                 2.7.11-1

**Comment by alex** [comment]
From looking at the raw ASN.1, it looks like the version of OpenSSL or pyOpenSSL which produced that encoded it badly -- it was a bug that it was encoded like that, and it was a bug that it accepted it before.

This is baed on looking at it with `openssl asn1parse -i`. The `ObjectIndeitifer` in the `AlgorithmIdentifier` for the `signatureAlgorithm` shows as `OBJECT            :BAD OBJECT:[]`.

**Comment by geektophe** [comment]
That's what I was thinking about.

On the same machine, generating a CSR from `openssl req` gives a loadable file (as shown in my third example), which in my point of view let think that the OpenSSL library works.

I had the same error on a Travis build where pyOpenSSL is installed via `pip`. The library versions installed were the following ones:

    OpenSSL/1.0.1f
    asn1crypto/0.23.0
    cryptography/2.0.3
    pyOpenSSL/17.3.0
    pyasn1/0.3.7
    pyasn1-modules/0.1.4
    pycparser/2.18
    pycrypto/2.6.1

Perhaps an interface changed in the OpenSSL library that breaks CSR generation.

**Comment by alex** [comment]
I don't think we're still generating invalid CSRs, so this can be considered complete.

**Comment by oliviermartin** [comment]
I have just tried test case on my machine and have a 'similar' issue (I only tried the latest version):

```
Python 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import OpenSSL
>>> OpenSSL.__version__
'20.0.1'
>>> from OpenSSL import crypto
>>> skey = crypto.PKey()
>>> skey.generate_key(crypto.TYPE_RSA, 2048)
>>> csr = crypto.X509Req()
>>> csr.get_subject().CN = "test-01.example.com"
>>> csr.get_subject().C = "US"
>>> csr.set_pubkey(skey)
>>> csrpem = crypto.dump_certificate_request(crypto.FILETYPE_PEM, csr)
>>> crypto.load_certificate_request(crypto.FILETYPE_PEM, csrpem)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/olivier/.local/lib/python3.7/site-packages/OpenSSL/crypto.py", line 2972, in load_certificate_request
    _openssl_assert(req != _ffi.NULL)
  File "/home/olivier/.local/lib/python3.7/site-packages/OpenSSL/_util.py", line 71, in openssl_assert
    exception_from_error_queue(error)
  File "/home/olivier/.local/lib/python3.7/site-packages/OpenSSL/_util.py", line 57, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.crypto.Error: [('asn1 encoding routines', 'asn1_item_embed_d2i', 'field missing'), ('asn1 encoding routines', 'asn1_template_noexp_d2i', 'nested asn1 error'), ('PEM routines', 'PEM_ASN1_read_bio', 'ASN1 lib')]
>>> 
```

**Comment by oliviermartin** [comment]
Ok, the issue occurs when trying to load an unsigned X509Req, this code works:

```
skey = crypto.PKey()
skey.generate_key(crypto.TYPE_RSA, 2048)
csr = crypto.X509Req()
csr.get_subject().CN = "test-01.example.com"
csr.get_subject().C = "US"
csr.set_pubkey(skey)
csr.sign(skey, "sha1")
csrpem = crypto.dump_certificate_request(crypto.FILETYPE_PEM, csr)
crypto.load_certificate_request(crypto.FILETYPE_PEM, csrpem)
```
