### ISSUE TITLE
'ValueError: String expected' when trying to call 'use_privatekey_file'

### ISSUE THREAD

**Issue by aiguofer** [pyca/pyopenssl#701]
Hi, I'm trying to use a private keyfile with a passphrase in requests and running into an issue in pyopenssl (version 17.3.0).

I changed `urllib3.contrib.pyopenssl.load_cert_chain` to:
```
    def load_cert_chain(self, certfile, keyfile=None, password=None):
        self._ctx.use_certificate_file(certfile)
        if password is not None:
            def meh(*x):
                print('returning ' + password)
                return password
            self._ctx.set_passwd_cb(meh)
        self._ctx.use_privatekey_file(keyfile or certfile)
```
to make sure the callback was working as expected, which it is.

Here's the relevant part of the stacktrace; it looks like there might be an issue when translating the python string and passing it to openssl?

Btw, it's passing filetype=1 when calling `_lib.SSL_CTX_use_PrivateKey_file`, which seems right.
```
/home/rdu/difernan/.pyenv/versions/custard/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.pyc in load_cert_chain(self, certfile, keyfile, password)
    425                 return password
    426             self._ctx.set_passwd_cb(meh)
--> 427         self._ctx.use_privatekey_file(keyfile or certfile)
    428 
    429     def wrap_socket(self, sock, server_side=False,

/home/rdu/difernan/.pyenv/versions/custard/lib/python2.7/site-packages/OpenSSL/SSL.py in use_privatekey_file(self, keyfile, filetype)
    874             self._context, keyfile, filetype)
    875         if not use_result:
--> 876             self._raise_passphrase_exception()
    877 
    878     def use_privatekey(self, pkey):

/home/rdu/difernan/.pyenv/versions/custard/lib/python2.7/site-packages/OpenSSL/SSL.py in _raise_passphrase_exception(self)
    850     def _raise_passphrase_exception(self):
    851         if self._passphrase_helper is not None:
--> 852             self._passphrase_helper.raise_if_problem(Error)
    853 
    854         _raise_current_error()

/home/rdu/difernan/.pyenv/versions/custard/lib/python2.7/site-packages/OpenSSL/crypto.pyc in raise_if_problem(self, exceptionType)
   2641                 pass
   2642 
-> 2643             raise self._problems.pop(0)
   2644 
   2645     def _read_passphrase(self, buf, size, rwflag, userdata):

ValueError: String expected
```

**Comment by alex** [comment]
This error message sucks, but I believe it means that you're passing a `unicode`, where it wants a `bytes`.

Can you verify what type you're passing for `passphrase`?

**Comment by aiguofer** [comment]
Sure enough that was it! I was passing in `unicode`. If I convert it to a `str` first (in python 2) it works. Might be a good idea to cast it in `pyopenssl`?

**Comment by alex** [comment]
it's intentional that we handle it this way; the error message just needs fixing.

**Comment by aiguofer** [comment]
Ahh gotcha... Should the documentation for `set_passwd_cb` at least specify that the return value should be a byte string?

With Python going to `unicode` as default, and it being a higher level language where you should generally not have to care about these types of things, it's a little confusing to have to cast it yourself.

**Comment by alex** [comment]
Yes, the documentation should be improved as well. If you'd like to submit a PR for that, it'd be awesome.

pyOpenSSL is an old, and extremely low level API over OpenSSL.
