### ISSUE TITLE
cannot add subjectKeyIdentifier to Certificate Request

### ISSUE THREAD

**Issue by joerichter-stash** [pyca/pyopenssl#707]
With the current implementation i am not able to add a subjectKeyIdentifier extension to a certificate request.

I have a patched crypto.py by deriving X509Req from X509 and allowing X509 instances as extension subject as well. If this is the right direction to go, i would like to contribute my patch.

Example of Issue:
```
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import rsa, ec
from cryptography.hazmat.primitives.serialization import Encoding, PrivateFormat, NoEncryption

from OpenSSL import crypto
from OpenSSL.crypto import X509Extension

def gen_ecdsa_key(curve_name, length):
    ec_curve = crypto.get_elliptic_curve(curve_name)
    key = ec.generate_private_key(ec_curve, default_backend())
    key_pem = key.private_bytes(encoding=Encoding.PEM,
            format=PrivateFormat.TraditionalOpenSSL,
            encryption_algorithm=NoEncryption())

    return crypto.load_privatekey(crypto.FILETYPE_PEM, key_pem)


key = gen_ecdsa_key("secp256k1", 256)
req = crypto.X509Req()
extensions = [ X509Extension('subjectKeyIdentifier', False, 'hash', subject=req) ]

req.add_extensions(extensions)
```

The result is:
```
Traceback (most recent call last):
  File "req_issue.py", line 21, in <module>
    X509Extension('subjectKeyIdentifier', False, 'hash', subject=req)
  File "/home/jrichter/src/python/pyopenssl/src/OpenSSL/crypto.py", line 710, in __init__
    raise TypeError("subject must be an X509 instance")
TypeError: subject must be an X509 instance
```

**Comment by reaperhulk** [comment]
In general we're not expanding the pyOpenSSL X509 API. Instead we're pointing users at `cryptography`'s X509 layer (https://cryptography.io/en/latest/x509/) which is a much richer and more complete API for generating certificates and certificate requests. Additionally, you can use [from_cryptography](http://pyopenssl.readthedocs.io/en/stable/api/crypto.html#OpenSSL.crypto.X509.from_cryptography) to convert a `cryptography` x509 cert to a pyOpenSSL one if you need to use it in a TLS context.

**Comment by joerichter-stash** [comment]
Thanks for your reply and your patience. I have tried to generate my CSRs both ways, the one with `cryptography` and directly using `pyopenssl`. I found it easier to use `pyopenssl` for generating many CSRs based on templates. 
There is just a very little issue with pyopenssl preventing this usecase. Please allow me to give you a the details of the patch with a more extended usecase: https://github.com/pyca/pyopenssl/pull/713

**Comment by alex** [comment]
We're committed to deprecating and (some day, I hope) removing pyOpenSSL's X.509 layer, so as @reaperhulk said we are not going to make any large changes to it.
