### ISSUE TITLE
PKey not imported with `from […] import *`

### ISSUE THREAD

**Issue by nikaro** [pyca/pyopenssl#715]
Hello,

When doing `from OpenSSL.crypto import *` it does not import `PKey()`.

```
Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from OpenSSL.crypto import *
>>> key = PKey()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'PKey' is not defined
```

This is used in at least one project: https://github.com/ajenti/ajenti/issues/1091

Doing `from OpenSSL.crypto import Pkey` works fine.

Regards.

**Comment by reaperhulk** [comment]
We would be happy to review a PR fixing this behavior, but I should also note that it is definitely bad practice to `import *` like that.

**Comment by nikaro** [comment]
Yeah i know and i agree, i've said it in the issue of the project which do this. But since the possibility exists it is used by some, it would be nice to have it working.

PR #719 submitted :-)
