### ISSUE TITLE
How to use openssl rand with pyopenssl

### ISSUE THREAD

**Issue by rajegit** [pyca/pyopenssl#720]
I want make equivalent of openssl commandline 
`openssl rand -out randomdata.bin 32`

Can someone let me know how to do this ?

-Regards
Raje

**Comment by hynek** [comment]
Userspace CSPRNGs are not great and [you should use your OS’s kernel’s one](https://sockpuppet.org/blog/2014/02/25/safely-generate-random-numbers/).  You don’t need OpenSSL or pyOpenSSL for that in Python:

```python
import os

with open("randomdata.bin", "wb") as f:
    f.write(os.urandom(32))
```

Works both on Python 2 and 3, UNIX and Windows.
