### ISSUE TITLE
Broken type usage or comment mismatch

### ISSUE THREAD

**Issue by alexgurrola** [pyca/pyopenssl#741]
The following snippet does not work, although the library seems to request it in this format on [src/OpenSSL/crypto.py#L1025](https://github.com/pyca/pyopenssl/blob/master/src/OpenSSL/crypto.py#L1025).

```
req = crypto.X509Req()
...
req.sign(key, b'sha256')
```

Below is my traceback:

```
Traceback (most recent call last):
  ...
  File "main.py", line 218, in generate_csr
    req.sign(key, b'sha256')
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/crypto.py", line 1042, in sign
    digest_obj = _lib.EVP_get_digestbyname(_byte_string(digest))
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/_util.py", line 112, in byte_string
    return s.encode("charmap")
AttributeError: 'bytes' object has no attribute 'encode'

```

As you can see it really seems to really want a `str` type but shows `bytes` in the comments as well as looking like it's trying to handle both.

Now for the workaround:

```
req = crypto.X509Req()
...
req.sign(key, 'sha256')
```

This workaround is functional, but PyCharm does see the same comments and intentions as I do and complains about the library wanting `bytes` instead of `str`.  That said, I'm not sure if this means the functionality is incorrect or just the documentation.  Either way, this counter-intuitive workaround solves the issue for now.

Also, the credit for this find goes to a StackOverflow question from 19 months ago, so this is clearly a persistent issue, as you can see: [stackoverflow.com/questions/38780150](https://stackoverflow.com/questions/38780150/openssl-crypto-x509-sign-throws-bytes-object-has-no-attribute-encode).

**Comment by reaperhulk** [comment]
Thanks for the report, this is a bug that we should fix.

**Comment by celinemol** [comment]
Hello,

I am seeing it here too, though not sure if this is acceptable or not. I am trying to verify a public key I have received from a separate program. Here's my code:
```
pkey = crypto.load_publickey(crypto.FILETYPE_PEM, public_key)
certification = crypto.X509()
certification.set_pubkey(pkey)
crypto.verify(certification, signature, message, 'sha1')
```

I am getting this Traceback:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/celinemol/opt/anaconda3/envs/beni_api/lib/python3.9/site-packages/OpenSSL/crypto.py", line 3054, in verify
    verify_result = _lib.EVP_VerifyFinal(
TypeError: initializer for ctype 'unsigned char *' must be a bytes or list or tuple, not str
```

Even with the TypeError, is the message still validated, since I should be expecting an InvalidSignature exception if it's not?

Thank you!

**Comment by reaperhulk** [comment]
#1078 actually fixed the docs for this. @celinemol your issue is that you're passing a str instead of bytes for one of your arguments to verify. Verification did not occur because the type was entirely wrong.
