### ISSUE TITLE
please add ECC  ECDH  ECDHA

### ISSUE THREAD

**Issue by Yensan** [pyca/pyopenssl#748]
Python's OpenSSL pakage is very rare to find.  M2Crypto is too hard to install. This project is the best one, but I find it has not ship with ECC  ECDH 

I want to use it generate private-key/public-key, then use hand-shake genarate share-key

**Comment by alex** [comment]
If you want elliptic curve cryptography, we suggest cryptography.io: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/

**Comment by Yensan** [comment]
@alex 
hi, alex, thank you for your answer. 
The cryptography and it's doc is friendly, but I find it can't do what I want.  😭 
Can you (or some guys nearby) tell me what should I do?
https://github.com/pyca/cryptography/issues/4190
