### ISSUE TITLE
 super(X509Name, self).__getattr__(name) AttributeError: 'super' object has no attribute '__getattr__'    

### ISSUE THREAD

**Issue by mindstorms82** [pyca/pyopenssl#762]
This problem appears in python 3.6.2 and Pyopenssl 18.0.0  in Fedora.

File "admin.py", line 152, in add_cert_to_crl
    crl_obj.sign(root_CA_obj.get_issuer(), root_key_obj, bytes(message_digest, encoding='utf-8'))
  File "/usr/lib/python3.6/site-packages/OpenSSL/crypto.py", line 2202, in sign
    self._crl, _lib.X509_get_subject_name(issuer_cert._x509))
  File "/usr/lib/python3.6/site-packages/OpenSSL/crypto.py", line 551, in __getattr__
    return super(X509Name, self).__getattr__(name)
AttributeError: 'super' object has no attribute '__getattr__'    

`
def __getattr__(self, name):

        nid = _lib.OBJ_txt2nid(_byte_string(name))
        if nid == _lib.NID_undef:
            try:
                _raise_current_error()
            except Error:
                pass
            return super(X509Name, self).__getattr__(name)`

**Comment by reaperhulk** [comment]
If you create a new virtualenv and install pyOpenSSL into that do you see the same error?

**Comment by mindstorms82** [comment]
still facing the same error

**Comment by reaperhulk** [comment]
Okay, can you provide some sample code we can use to reproduce the error?

**Comment by reaperhulk** [comment]
This is a confusing error but the reason is because the [CRL.sign](http://pyopenssl.readthedocs.io/en/stable/api/crypto.html#OpenSSL.crypto.CRL.sign) method takes a certificate, not an X509 name, for issuer. Pass the cert itself (in your code `root_CA_obj`) and it will sign successfully.
