### ISSUE TITLE
Gevent and PyOpenSSL

### ISSUE THREAD

**Issue by Mradr** [pyca/pyopenssl#778]
Hello,

I am trying to get pyopenssl working with gevent and I keep running into an issue where it seems to be blocking greenlit threads. I was wonder if someone could take a look and see what I am doing wrong here.

Here is the original posting on this for more information on where I am so far:
https://github.com/gevent/gevent/issues/1265

So I follow the code that another project said they got working used there and converted the current SSL to use it - but I seem to be still having some blocking going on here. 

https://github.com/mjs/gevent_openssl/blob/master/gevent_openssl/SSL.py (their work)
https://www.diffchecker.com/lOqYqoPU (see the different - org | mod)

Hopefully I am not sounding stupid here and not miss understanding something.

**Comment by alex** [comment]
Apologies we didn't get to this for so long. Unfortunately this isn't really the tyep of support we can provide.
