### ISSUE TITLE
File BIO flushing

### ISSUE THREAD

**Issue by vihanb** [pyca/pyopenssl#779]
OpenSSL has `BIO_file_new` methods etc. for doing IO to/from files. There is the `crypto._new_mem_buf` for strings but no high-level bindings for files so I'm using the `lib` function. There is the `lib.BIO_new_file` which does seem to work however when I initialize a BIO* with `w` flag that is passed to `i2d_PKCS7_bio` the BIO appears to have content in it but the file is empty. My best guess is that it is not being flushed but there is no `lib.BIO_FLUSH` method.

**Comment by reaperhulk** [comment]
That might be a correct guess, but we don't currently bind `BIO_flush` in cryptography. You could submit a PR, but unless you have a specific reason for wanting to write directly to disk I'd suggest just using a mem BIO and then writing to disk via Python.
