### ISSUE TITLE
dump_certificate only dump one section

### ISSUE THREAD

**Issue by skeetwu** [pyca/pyopenssl#783]
Hi,

I want to verify some certifications contains multi-section, I mean these file contains several of "-----BEGIN CERTIFICATE-----" and "-----END CERTIFICATE-----"
 I load from string format, but after I dump through "dump_certificate", there is only one section,  follow is the code example, please help to finger a way to dump them all?

```Python
def certificate_decode(certificate):
    valid = False
    if not valid:
        try:
            cert = crypto.load_certificate(crypto.FILETYPE_PEM, certificate)
        except crypto.Error:
            pass
        else:
            valid = True
    if not valid:
        raise TypeError()
    text = crypto.dump_certificate(
            crypto.FILETYPE_PEM, cert)
    return text


if __name__ == "__main__":
    a, b = certificate_decode("-----BEGIN CERTIFICATE-----\nxxxxxxxxxxxxxxxxxxxxxxxxx=\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\nMxxxxxxxxxxxxxxxxxxxxxxxxx=\n-----END CERTIFICATE-----\n")
    print(a)
```

Thanks

**Comment by reaperhulk** [comment]
pyOpenSSL doesn't support this, but you can easily split it yourself in python and then pass it to pyOpenSSL to parse each one.

**Comment by hynek** [comment]
There’s also http://pem.readthedocs.io/ if you don’t want to split by hand.

**Comment by skeetwu** [comment]
@reaperhulk @hynek  Thanks for your reply.
