### ISSUE TITLE
ssl error while installing a package 

### ISSUE THREAD

**Issue by mkaja** [pyca/pyopenssl#788]
I am getting this error while installing a package from internal pypi repo

Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),)) - skipping

python -c "import ssl; print(ssl.OPENSSL_VERSION)"
OpenSSL 0.9.8zh 14 Jan 2016
pip --version
pip 10.0.1 from /Users/mkaja/Library/Python/2.7/lib/python/site-packages/pip (python 2.7)

pip list  
pyobjc-framework-OpenDirectory         2.5.1
pyOpenSSL                              17.2.0
asn1crypto                             0.22.0
cryptography                           2.2.2
pycrypto                               2.6.1

**Comment by tiran** [comment]
Your OpenSSL version is way too old. You need a version that supports TLS 1.2.

https://pyfound.blogspot.com/2017/01/time-to-upgrade-your-python-tls-v12.html
