### ISSUE TITLE
Generate CRL file

### ISSUE THREAD

**Issue by savenko-egor** [pyca/pyopenssl#800]
Hey!

I setup OpenVPN server, and I need create python script for generate .ovpn configs.
I try use this "pyopenssl" module, but have problem. I can't find any information about generate CRL file for my OpenVPN server.
I can use "subproccess" or other modules for this, but I think this not very correct.
You can help me with this?

Best regards!

**Comment by alex** [comment]
We recommend using the pyca/cryptography package for generating CRLs: https://cryptography.io/en/latest/x509/reference/#cryptography.x509.CertificateRevocationListBuilder
