### ISSUE TITLE
use a subtype of SSL.Error for the custom error raised by Context.set_cipher_list when OpenSSL 1.1.1 transforms an invalid cipher list into TLS 1.3 ciphers

### ISSUE THREAD

**Issue by glyph** [pyca/pyopenssl#819]
As raised in https://github.com/twisted/twisted/pull/1100#discussion_r256842720, the current behavior, which appears to be "raise an `SSL.Error([])`".  Despite the fact that the OpenSSL error queue is not, shall we say, robust to precise interrogation, it would still be nice to be able to distinguish this failure mode of cipher suite configuration from "real" failures more precisely.

**Comment by alex** [comment]
fixed in #818
