### ISSUE TITLE
PyPI Package pyOpenSSL 19.0.0 Lacks Version Limit For Package cryptography

### ISSUE THREAD

**Issue by Conrad-T-Pino** [pyca/pyopenssl#829]
System: Debian 9.8 default Python 2.7.13 pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

After "sudo pip install certbot certbot-dns-standalone" which includes pyOpenSSL:
1) certbot blows up: ContextualVersionConflict: (cryptography 1.7.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('cryptography>=2.3'), set(['PyOpenSSL', 'pyOpenSSL']))
2) pip blows up: Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 309, in wrapper _lib.X509_up_ref(x509) AttributeError: 'module' object has no attribute 'X509_up_ref'

Unfortunately pip accepts Debian cryptography 1.7.1, ignoring PyPI cryptography 2.6.1 and afterward SSL operations, both certbot and pip, blow up.

Fortunately recover is fairly easy:
sudo pip uninstall pyOpenSSL
sudo pip install --upgrade cryptography
sudo pip install pyOpenSSL

Best regards,
Conrad T. Pino

**Comment by reaperhulk** [comment]
As you noted in your resolution this isn’t a bug in pyopenssl but rather an issue with multiple versions being installed in different places and how Python loads modules, but thanks for providing a workaround for others to use when they encounter this problem.

**Comment by Conrad-T-Pino** [comment]
We agree this not a internal bug however it's definitely a distribution bug and it remains to be seen if that distribution path falls within or outside this Project's scope.

pyOpenSSL PyPI package page: https://pypi.org/project/pyOpenSSL/
1) Names this Project's developers as "Author" and as
2) "Maintainers": alexgaynor, exarkun, hynek, reaperhulk

If 1 or 2 above are members of this Project's then assigning this Issue to them seems appropriate.

**Comment by zoresvit** [comment]
@Conrad-T-Pino pyOpenSSL [does have a lower limit](https://github.com/pyca/pyopenssl/blob/master/setup.py#L98) on `cryptography` package. But the above problem is not even a distribution bug: it's the result of mixing Debian system packages with those installed by `sudo pip`. Specifically for this reason installing Python packages with `pip` into system-wide directory is not recommended. 

 If the versions provided by system packages are not fresh enough it's best to use [virtualenv](https://virtualenv.pypa.io/en/latest/) and install newer packages into an isolated environment which helps to avoid version conflicts.

**Comment by Conrad-T-Pino** [comment]
@zoresvit Thank you.

This suggests Debian pip ignores "install_requires" array. Debian stable lags; this could be already resolved upstream and in later Debian release.  Is opening a Debian issue worthwhile?

1) I need "certbot" as root so TCP/UDP port 53 listen, update root owned files, reload Nginx all work.
2) Debian pip updates "/usr/local/lib/python2.7" leaving "/usr/lib/python2.7" undisturbed.

Does "virtualenv" suggestion still apply in this "certbot" use case?
