### ISSUE TITLE
Programmatic decrypt of files

### ISSUE THREAD

**Issue by neliel123** [pyca/pyopenssl#853]
I have asked the issue in stackoverflow.. thought of asking it here also..

How do I programmatically execute the following script using PyOpenSSL?

I basically want to decrypt a file that was encrypted with a private key.

`openssl rsautl -decrypt -inkey privkey.pem -in my-file-to-be-decrypted -out result.out`
Is there a way to do this using PyOpenSSL?

**Comment by reaperhulk** [comment]
This is not in scope for pyOpenSSL.
