### ISSUE TITLE
add SSL_CTX_set_min_proto_version and SSL_CTX_set_max_proto_version

### ISSUE THREAD

**Issue by nocturne-mit** [pyca/pyopenssl#860]
I'd like to be able to create TLS connections using only TLS 1.3, and I'd like to be able to create TLS connections using only TLS 1.2 (or other older TLS versions).

In the C API provided by openssl 1.1.0 and later, there is no TLSv1_3_METHOD at all, and the SSL_OP_NO_TLSvN scheme is deprecated in favor of specifying min/max protocol versions, using the new APIs SSL_CTX_set_min_proto_version() and SSL_CTX_set_max_proto_version().

Can you provide wrappers for the SSL_CTX_set_min_proto_version() and SSL_CTX_set_max_proto_version() library functions, and import the family of constants such as TLS1_3_VERSION and TLS1_2_VERSION for use with the new min/max API?

For context on the upstream OpenSSL API changes, you might refer to https://github.com/openssl/openssl/pull/1804#issuecomment-257230640 and https://github.com/openssl/openssl/issues/6964

**Comment by nocturne-mit** [comment]
And as a more canonical reference on this change, the openssl changelog also mentions the new API: https://github.com/openssl/openssl/commit/7946ab33cecce60afcc00afc8fc18f31f9e66bff

**Comment by evilaliv3** [comment]
I agree that this would be an important addition mainly for two reasons:
- the more important: one could set a configuration that would then be automatically upgraded for example in case unattended-upgrade are enabled on the system.

- last but not least openssl 1.1.0 has deprecated the following options:
![screenshot-www openssl org-2019 09 25-21_32_55](https://user-images.githubusercontent.com/217034/65633336-2484e880-dfdc-11e9-8373-884a9c650713.png)
