### ISSUE TITLE
ValueError: invalid value for verify_mode when passing in specific SSL Protocol e.g. PROTOCOL_TLSv1_2

### ISSUE THREAD

**Issue by delrey1** [pyca/pyopenssl#864]
Python Version: 3.7.4
OS: Windows

Within debug mode, added a breakpoint on line 559 `super(SSLContext, SSLContext).verify_mode.__set__(self, value)`
If value is _SSLMethod.PROTOCOL_TLS, all is fine and able to call next line
` super(SSLContext, SSLContext).verify_mode.__set__(self, value)`

However if the value is `value = _SSLMethod.PROTOCOL_TLSv1_2` then I get:
```
super(SSLContext, SSLContext).verify_mode.__set__(self, value)
Traceback (most recent call last):
  File "<snipped>\PyCharm-P\ch-0\192.6262.63\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
ValueError: invalid value for verify_mode
```

Snippet of my code is:
```
ws = websocket.WebSocket(sslopt={"cert_reqs": ssl.PROTOCOL_TLSv1_2})
ws.connect(url)
```

Understand that it may be an issue with the websocket python library, but it seems to fall under the ssl library

Any suggestions?

This also occurs for
* `PROTOCOL_TLSv1_1`
* `PROTOCOL_TLS_CLIENT`
* `PROTOCOL_TLS_SERVER`

But completely fine for
* `PROTOCOL_TLS`

**Comment by delrey1** [comment]
Closed as error between keyboard and chair

Misread and "cert_reqs" is meant to be "ssl_version" (doh!)

**Comment by tiran** [comment]
You are also using stdlib ssl module, not PyOpenSSL :)
