### ISSUE TITLE
Key Type not Supported

### ISSUE THREAD

**Issue by iqbalhussain931** [pyca/pyopenssl#871]
I am generating private and public keys with the following code:
```
from OpenSSL import crypto
k = crypto.PKey()
k.generate_key(crypto.TYPE_RSA, 4096)

private_key = crypto.dump_privatekey(crypto.FILETYPE_PEM, k)
file_out = open("privatec_key.pem", "wb")
file_out.write(private_key)
public_key = crypto.dump_publickey(crypto.FILETYPE_PEM, k)
file_out = open("public_key.pem", "wb")
file_out.write(public_key)
```
The code is working properly but when I try to add the public key on Digital Ocean server. Its gives me an error.
**Key invalid type, we support 'ssh-rsa', 'ssh-dss', 'ecdsa-sha2-nistp256', 'ecdsa-sha2-nistp384', 'ecdsa-sha2-nistp521', or 'ssh-ed25519'.**

Although in my code i have selected **crypto.TYPE_RSA** so am I doing something wrong?

**Comment by alex** [comment]
SSH public keys have a different format -- you are better off using pyca/cryptography to generate these.  https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.PublicFormat.OpenSSH
