### ISSUE TITLE
How read PKCS#12 store with multiple entries.

### ISSUE THREAD

**Issue by fspider** [pyca/pyopenssl#895]
My .p12 file contains two entries.
I thought that my file as normal p12 file but the keytool shows it as PKCS#12 Keystore.

![image](https://user-images.githubusercontent.com/53686427/76095005-d977f400-5fc3-11ea-9556-7f9d9b932071.png)

How can i read all two entries?
I can not read in this way.
p12 = load_pkcs12(fh.read(), keypwd)

**Comment by facutuesca** [comment]
This is a limitation of the OpenSSL API used to implement this function, [`PKCS12_parse()`](https://www.openssl.org/docs/man3.0/man3/PKCS12_parse.html):
> BUGS
Only a single private key and corresponding certificate is returned by this function. More complex PKCS#12 files with multiple private keys will only return the first match.

Furthermore, `PKCS12` support is currently [deprecated](https://github.com/pyca/pyopenssl/blob/main/src/OpenSSL/crypto.py#L2797-L2806) in `PyOpenSSL`, and the function this issue refers to (`load_pkcs12()`) has been completely removed.

I suggest we close this one @mhils @alex
