### ISSUE TITLE
Test suite fails with OpenSSL 1.1.1e

### ISSUE THREAD

**Issue by xfix** [pyca/pyopenssl#899]
The OpenSSL 1.1.1e NOTES file lists the following change:

> Properly detect EOF while reading in libssl. Previously if we hit an EOF while reading in libssl then we would report an error back to the application (SSL_ERROR_SYSCALL) but errno would be 0. We now add an error to the stack (which means we instead return SSL_ERROR_SSL) and therefore give a hint as to what went wrong.

This change causes `test_unexpected_EOF` test to fail, as EOF no longer returns `SSL_ERROR_SYSCALL`.

**Comment by flokli** [comment]
Is this just a failure in the test suite, or is there actually code inside pyopenssl relying on this behaviour?

**Comment by flokli** [comment]
Note that some distros probably can't bump openssl because of that, or pyopenssl starts breaking there.

**Comment by tiran** [comment]
The incompatible change has been fixed in OpenSSL 1.1.1f. Please skip 1.1.1e.

**Comment by xfix** [comment]
Oh. Okay then.
