### ISSUE TITLE
how to load an existing pkcs12 keystore? 

### ISSUE THREAD

**Issue by AchrafLance** [pyca/pyopenssl#901]
l used java to create a pkcs12 keystore where l stored two keys, now l want to retrieve these keys using python. ln java l load the keystore and use keystore.getkey(keyalias). how can l do that with pyopenssl?

**Comment by reaperhulk** [comment]
Do this with cryptography via [pkcs12.load_key_and_certificates](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.pkcs12.load_key_and_certificates)
