### ISSUE TITLE
Assert usage

### ISSUE THREAD

**Issue by Gallaecio** [pyca/pyopenssl#902]
I’ve noticed 5 `assert` usages in the code base which would be ignored when running Python in optimized mode.

The 3 `assert length > 0` statements in `SSL.py` may be OK, I’m not sure if the function calls preceding them can return a `<= 0` value.

The 2 `assert` statement in `crypto.py`, on the other hand, look to me like maybe they should be using `_openssl_assert` instead. I’m not completely sure either, though.

**Comment by alex** [comment]
Probably all of these should be `_openssl_assert`. Are you interested in sending a PR?
