### ISSUE TITLE
where can I find code of _lib

### ISSUE THREAD

**Issue by fight-think** [pyca/pyopenssl#911]
def verify_certificate(self):

        """

        Verify a certificate in a context.

        .. versionadded:: 0.15

        :raises X509StoreContextError: If an error occurred when validating a

          certificate in the context. Sets ``certificate`` attribute to

          indicate which certificate caused the error.

        """

        # Always re-initialize the store context in case

        # :meth:`verify_certificate` is called multiple times.

        #

        # :meth:`_init` is called in :meth:`__init__` so _cleanup is called

        # before _init to ensure memory is not leaked.

        self._cleanup()

        self._init()

        ret = _lib.X509_verify_cert(self._store_ctx)

        self._cleanup()

        if ret <= 0:

            raise self._exception_from_context()

I want to know more about the function of _lib.X509_verify_cert, about the detail of verification return. Is it same with C-based version of OpenSSL or it exist _lib wrote with Python? Can someone tell me about this? Thank you very much.

**Comment by alex** [comment]
`_lib` directly exposes C functions from OpenSSL using CFFI. The code to do this is in the cryptography package.

**Comment by fight-think** [comment]
I get it, Thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alex Gaynor"<notifications@github.com&gt;; 
发送时间: 2020年5月13日(星期三) 上午9:00
收件人: "pyca/pyopenssl"<pyopenssl@noreply.github.com&gt;; 
抄送: "1297518605"<1297518605@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [pyca/pyopenssl] where can I find code of _lib (#911)





 
_lib directly exposes C functions from OpenSSL using CFFI. The code to do this is in the cryptography package.

**Comment by fight-think** [comment]
I get it, Thanks! Forgive my fool questions.------------------ 原始邮件 ------------------
发件人: "Alex Gaynor"<notifications@github.com>
发送时间: 2020年5月13日(星期三) 上午9:00
收件人: "pyca/pyopenssl"<pyopenssl@noreply.github.com>;
抄送: "fight-think"<1297518605@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [pyca/pyopenssl] where can I find code of _lib (#911)




 
_lib directly exposes C functions from OpenSSL using CFFI. The code to do this is in the cryptography package.
 
&mdash;
