### ISSUE TITLE
Keep getting "Segmentation Fault (Core Dumped) message at the end of installation

### ISSUE THREAD

**Issue by mutantmarine** [pyca/pyopenssl#915]
Trying to install pyOpenSSL for python version 2.7 but keep getting the "Segmentation Fault (Core Dumped)" message at the end. Any help?

Here is the log:

$ python2.7 -m pip install pyopenssl
Collecting pyopenssl
  Using cached https://files.pythonhosted.org/packages/9e/de/f8342b68fa9e981d348039954657bdf681b2ab93de27443be51865ffa310/pyOpenSSL-19.1.0-py2.py3-none-any.whl
Collecting six>=1.5.2 (from pyopenssl)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting cryptography>=2.8 (from pyopenssl)
  Using cached https://files.pythonhosted.org/packages/5f/fc/a92bad2460d349ee9eb868f9f9dcddb7c8f42a45677d53a5c663fa251e75/cryptography-2.9.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting enum34; python_version < "3" (from cryptography>=2.8->pyopenssl)
  Using cached https://files.pythonhosted.org/packages/6f/2c/a9386903ece2ea85e9807e0e062174dc26fdce8b05f216d00491be29fad5/enum34-1.1.10-py2-none-any.whl
Collecting ipaddress; python_version < "3" (from cryptography>=2.8->pyopenssl)
  Using cached https://files.pythonhosted.org/packages/c2/f8/49697181b1651d8347d24c095ce46c7346c37335ddc7d255833e7cde674d/ipaddress-1.0.23-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography>=2.8->pyopenssl)
  Using cached https://files.pythonhosted.org/packages/08/29/8001b940ef40e7a25ffe8f3188bc9b118934b513d64f769dbf461e46f4ed/cffi-1.14.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=2.8->pyopenssl)
  Using cached https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl
Installing collected packages: six, enum34, ipaddress, pycparser, cffi, cryptography, pyopenssl
Successfully installed cffi-1.14.0 cryptography-2.9.2 enum34-1.1.10 ipaddress-1.0.23 pycparser-2.20 pyopenssl-19.1.0 six-1.15.0
Segmentation fault (core dumped)

I've tried uninstalling pyOpenSSL and reinstalling it but just keep getting the same error. I also tried the command: python2.7 -m pip install pyopenssl --no-binary :all: but that doesn't work for me. Any help?

**Comment by reaperhulk** [comment]
Is your pip up to date?

**Comment by mutantmarine** [comment]
> Is your pip up to date?

How would I find out to update it?

**Comment by reaperhulk** [comment]
`pip` prior to version 10.something had a bug (https://github.com/pypa/pip/pull/5405) that resulted in this segfault with newer pyopenssl and cryptography. You can upgrade `pip` by `pip install -U pip`. **However**, mixing distribution packages and `pip` installed packages is not a good idea. You should use your distribution's package manager to control global Python packages and you should install your own Python packages in a `virtualenv` or via `--user`.
