### ISSUE TITLE
No equivalent of OpenSSL’s X509_NAME_hash_old

### ISSUE THREAD

**Issue by AutumnSun1996** [pyca/pyopenssl#940]
It seems there is no python equivalent of OpenSSL’s X509_NAME_hash_old(-subject_hash_old from command line).
Now I am using `os.popen(f'openssl x509 -in {source} -subject_hash_old  -noout')`, is there a better way to get the old styled hash?

**Comment by reaperhulk** [comment]
`X509_NAME_hash_old` is a really the big endian representation of the first 4 bytes of the MD5 of the serialized ASN.1 representation of the subject X509_NAME. Here's some code that creates it in pyca/cryptography.

```python
from cryptography.hazmat.backends.openssl.backend import backend
from cryptography import x509
import binascii
import struct

with open("somecert.pem", "rb") as f:
    data = f.read()
cert = x509.load_pem_x509_certificate(data, backend)
import hashlib
hash = hashlib.md5(cert.subject.public_bytes(backend)).digest()
binascii.hexlify(struct.pack(">I", struct.unpack("<I", hash[0:4])[0]) )
```

**Comment by AutumnSun1996** [comment]
@reaperhulk Thanks for your help.
Here is my final code if someone else want to use OpenSSL.crypto instead of cryptography(like me).

```python
from OpenSSL.crypto import load_certificate, FILETYPE_PEM
import binascii
import hashlib

with open("somecert.pem", "r") as f:
    cert = load_certificate(FILETYPE_PEM, f.read())

md5 = hashlib.md5(cert.get_subject().der()).digest()
hash_old = binascii.hexlify(bytes(reversed(md5[:4])))
```

**Comment by reaperhulk** [comment]
I strongly recommend using cryptography (which you already have because pyopenssl uses it). The X509 layer in pyopenssl is ancient and slowly being deprecated.
