### ISSUE TITLE
error when verifying DSS

### ISSUE THREAD

**Issue by ZM-J** [pyca/pyopenssl#944]
Hi! I got an error on verifying signatures from DSA algorithm using public keys. My code goes below:
```python
def openssl_verify():
    file_dir = '/usr/zm_j/dsa'
    with open(f'{file_dir}/dsa_public.pem', 'r') as f:
        pks = f.read()
        pk = crypto.load_publickey(crypto.FILETYPE_PEM, pks)
        cert = crypto.X509()
        cert.get_subject().C = 'US'
        cert.get_subject().ST = 'CA'
        cert.set_serial_number(9001)
        cert.set_notBefore(b'20000101000000Z')
        cert.set_notAfter(b'21000101000000Z')
        cert.set_issuer(cert.get_subject())
        cert.set_pubkey(pk)
    
    with open(f'{file_dir}/packet3/message3', 'rb') as f:
        m1_data = f.read()

    with open(f'{file_dir}/packet3/sign3.bin', 'rb') as f:
        sign_bs = f.read()
        der_seq = DerSequence().decode(sign_bs, strict=True)
        r_prime, s_prime = Integer(der_seq[0]), Integer(der_seq[1])

    sign_bs = r_prime.to_bytes() + s_prime.to_bytes()
    print(len(sign_bs)) # 40

    try:
        crypto.verify(cert, sign_bs, m1_data, 'sha1')
        print("The message is authentic.")
    except ValueError:
        print("The message is not authentic.")
```
In the code above, `m1_data` is the data to be verified, and signature is generated by private key, which is unavailable, and encoded by DER. I noticed that the first parameter of `crypto.verify` should be a cert, but when I set cert with public key and some other information, the error occurs:
> OpenSSL.crypto.Error: [('asn1 encoding routines', 'ASN1_get_object', 'header too long'), ('asn1 encoding routines', 'asn1_check_tlen', 'bad object header'), ('asn1 encoding routines', 'asn1_item_embed_d2i', 'nested asn1 error')]
What is the problem with my code?

**Comment by reaperhulk** [comment]
If you're verifying a DSA signature you shouldn't use pyOpenSSL at all. Use `cryptography` (which pyOpenSSL depends on). https://cryptography.io/en/latest/hazmat/primitives/asymmetric/dsa/
