### ISSUE TITLE
Retrieve the peer certificate without client certificate in mTLS connection

### ISSUE THREAD

**Issue by meow-watermelon** [pyca/pyopenssl#946]
Hi,

I'm not sure if this is the right place to ask the question but I didn't find out a solid solution or conclusion by Google so I'd give a try here.

The issue is I want to retrieve the server certificate in mTLS connection. The service running on server needs client to provide client certificate but this should not be a problem to retrieve the server certificate in early stage of TLS handshake. 

I'm pretty sure Python standard ```ssl``` module does not support it but I remember PyOpenSSL can do that. However, I just don't know how to make it happen.

```
#!/usr/bin/env python3

from OpenSSL import SSL
import socket

ctx = SSL.Context(SSL.TLSv1_METHOD)

sock = SSL.Connection(ctx, socket.socket(socket.AF_INET, socket.SOCK_STREAM))
sock.connect((host, port))
sock.do_handshake()
```

Above code will throw out the following exception which is quite similar to ```ssl``` module:

```
OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')]
```

So could anyone tell me how can I retrieve the server certificate without client certificate in mTLS connection?

Thanks.

**Comment by alex** [comment]
I don't think our API meaningfully allows extracting information about the server where a handshake is not completed.

You can try catching the exception from `sock.do_handshake()` and then calling `sock.get_peer_certificate()`.
