### ISSUE TITLE
signal in packaging metadata that heartbleed vuln has been removed

### ISSUE THREAD

**Issue by zooko** [pyca/pyopenssl#95]
For context (about how we are struggling to mitigate heartbleed's threat to our users), please see https://tahoe-lafs.org/trac/tahoe-lafs/ticket/2215 and https://tahoe-lafs.org/pipermail/tahoe-dev/2014-April/008988.html .

Could you please make new releases of pyOpenSSL, named "0.14.1" and (for people like us who can't upgrade to the cffi-based build system yet) "0.13.1". The ".1"'s in these version numbers would serve as a _signal_, visible within the Python packaging metadata, that this particular package was built by someone who is aware of heartbleed and they intended to remove the heartbleed vuln from this package. Then Tahoe-LAFS (and Foolscap, and Twisted, etc.) can depend on "pyOpenSSL == 0.13.1, >= 0.14.1", to indicate their desire to listen to this signal.

Then the pyOpenSSL setup.py can help the builder of the package send the correct signal, by checking the version number of OpenSSL and refusing to build if it is one of the version numbers that had (in the upstream OpenSSL release) the heartbleed vuln.

Now, Debian and Ubuntu ship OpenSSL libraries which have a patch to fix the vuln but which still report the original upstream OpenSSL version numbers. No problem! When they build pyOpenSSL v0.13.1 and v0.14.1 packages, they will patch out that check that pyOpenSSL's setup.py does (or perhaps pyOpenSSL will offer a "--affirm-heartbleed-fix-is-present" build-time option for this), in order for them to correctly send the signal that their Debian/Ubuntu "python-openssl 0.13.1" or "python-openssl 0.14.1" package does _not_ have the vuln.

**Comment by alex** [comment]
People upgraded their OpenSSLs in the end.
