### ISSUE TITLE
Next Release Date?

### ISSUE THREAD

**Issue by mhils** [pyca/pyopenssl#964]
Hi folks,

Are there are plans for a new pyOpenSSL release in the near/medium future? We'd like to ship a @mitmproxy release with a completely rewritten proxy core before the end of the year, which would highly benefit from `.set_keylog_callback` to debug issues.

I can definitely work around that using cryptography directly, but I figured I'd ask nicely if you have something planned anyway before I unnecessarily build hideous monkeypatches. :-)

refs https://github.com/mitmproxy/mitmproxy/issues/3994

**Comment by alex** [comment]
@reaperhulk and I had discussed doing one soon-ish.

**Comment by reaperhulk** [comment]
Done.

**Comment by mhils** [comment]
This is super awesome, thank you two so much! ♥️
