### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'Cryptography_HAS_TLSEXT_HOSTNAME'

### ISSUE THREAD

**Issue by mmicu** [pyca/pyopenssl#973]
I've used the `python:3.7.6-slim-stretch` docker image for almost one year. Just today I got this strange issue (with `pyOpenSSL==17.5.0`):

```
>>> from OpenSSL import *
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
from OpenSSL import crypto, SSL
File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 673, in <module>
_lib.Cryptography_HAS_TLSEXT_HOSTNAME, "SNI not available"
AttributeError: module 'lib' has no attribute 'Cryptography_HAS_TLSEXT_HOSTNAME'
```

The only versions that work correctly are `pyOpenSSL==19.1.0` and `pyOpenSSL==20.0.0`.

**Comment by mhaggag** [comment]
We had this error pop up on one of servers today, and after comparing the dependent packages for pyopenssl on working servers vs the non-working server, I found that reverting `cryptography` from 3.3 to 3.2 (using `pip3 install cryptography==3.2`) works around this error until we figure out what's going on.

**Comment by reaperhulk** [comment]
Upgrading pyopenssl will resolve this error. Cryptography removed the binding because pyopenssl 19.1 and above no longer depend on it.

**Comment by Exagone313** [comment]
I got the same error on Debian Stretch as well, with Python 2 only.

I got these versions installed, which are "up-to-date" to Debian repositories.

```
# dpkg -l | grep 'libssl1\.1\|python-cryptog\|python-opens'
ii  libssl1.1:amd64            1.1.0l-1~deb9u1       amd64        Secure Sockets Layer toolkit - shared libraries
ii  python-cryptography        1.7.1-3+deb9u2        amd64        Python library exposing cryptographic recipes and primitives (Python 2)
ii  python-openssl             16.2.0-1              all          Python 2 wrapper around the OpenSSL library
```

When importing OpenSSL package, it is failing with the error described above:

```
# python
Python 2.7.13 (default, Aug 22 2020, 10:03:02) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import OpenSSL
/usr/lib/python2.7/dist-packages/OpenSSL/_util.py:6: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python cor
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 431, in <module>
    _lib.Cryptography_HAS_TLSEXT_HOSTNAME, "SNI not available"
AttributeError: 'module' object has no attribute 'Cryptography_HAS_TLSEXT_HOSTNAME'
```

I know that Debian packages are supported by their maintainers, but I'm unable to debug the issue as running a Docker container with the same versions installed on my computer doesn't have the issue.

Is it possible to have some technical context on why might this issue happen?

Thanks.

**Comment by alex** [comment]
Don't mix debian provided python packages and pip installed ones. Either use exclusively debian packages, or create a virtualenv and use pip ones.

**Comment by Exagone313** [comment]
Thanks @alex, this is my actual problem, I somehow got a version of `cryptography` installed by pip (in `/usr/local/lib/python2.7/dist-packages`). I moved the two directories manually and it solved my issue. I'm now investigating what is pip installing this library and I consider using more virtualenvs.

**Comment by Aricg** [comment]
I too see these errors in our build log. 
Still don't understand why 
pyOpenSSL==17.5.0
no longer works.

**Comment by cemilycollins** [comment]
I just started getting these errors this morning too with pyOpenSSL==19.0.0
I'm gonna try upgrading to 20.0.0
