### ISSUE TITLE
[X509Req] Certificate request from based on existing one

### ISSUE THREAD

**Issue by WillianBR** [pyca/pyopenssl#983]
**I have a scenario where exists a group of certificate who must be renewed.**  The chosen approach is copy all attributes from the old one to a newer.  Except by notBefore and nofAfter. On the new certificate the nofAfter attribute will become the notBefore. So a new key pair will be generated, to ensuro who it is compliance with the internal standards.  That means who some attributes may be change or removed if violate the internal policies.  As a example, we don't use the "ST" or "L" components.

_I dived in the documentation, but  there no sample code or any reference about the best way to do that.   All the information I was able to gatery is about new from scratch and self signed._ 

But I have a internal PKI.  **I need to generate a cert request file (CSR) and a private key file (KEY)**.  _Just as if I was using the OpenSSL command line tool_.   But I wish to do all that with Python 3 (100%) if posssible (I really pray for that).

The new certificate will be submitted to PKI by a Python3 code who will consume the EST protocol endpoint.

- There is anybody with some skills about that?  

- May be someone who did it!

-  A sample code or some hints. 
 
- I really appreciate any help who come to solve the issue. 

**Sure any code resulting from this effort will became public and if the owner of the repository allow, it'll be publishied as a thrding part contrib.**

Anybody???   If necessary we can talk by [Skype](https://msngr.pro/sk/live:willianbr_2/) or [WhatsApp](https://api.whatsapp.com/send?phone=5561999881277&text=%20pyOpenSSL-X509Req%3A%20Issue)!

@alex ? @reaperhulk ?

**Comment by alex** [comment]
For X.509 tasks we generally recommend using the pyca/cryptography library, not pyOpenSSL. It has extensive documentation here: https://cryptography.io/en/latest/x509/tutorial.html

As for your other requests: This is not an appropriate way to use an open source issue tracker. We're not able to do your job for you. Please do not ping random project members for your request.

**Comment by WillianBR** [comment]
> 
> 
> For X.509 tasks we generally recommend using the pyca/cryptography library, not pyOpenSSL. It has extensive documentation here: https://cryptography.io/en/latest/x509/tutorial.html
> 
> As for your other requests: This is not an appropriate way to use an open source issue tracker. We're not able to do your job for you. Please do not ping random project members for your request.

I'm sorry if I used improperly the channel. That was not a intentional.  Please accept my deep apology!  


I never intended to get someone to do a job. Just hints about the package capabilities.  I just found out this package a couple weeks and I'm study it to use into my automations.
