### ISSUE TITLE
OpenSSL.crypto 'sign' and 'verify' an existing hash

### ISSUE THREAD

**Issue by trevormarvin** [pyca/pyopenssl#987]
Is there a way to use the `OpenSSL.crypto.sign` and `OpenSSL.crypto.verify` methods whereas I can pass them an already-processed hash of the content instead of the content itself (to be hashed by the function/method)?  I would presume to have to inform the function of the hash that was used so the padding and any magic values could be generated or checked.

**Comment by reaperhulk** [comment]
You can do this with cryptography via [Prehashed](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/utils.html#cryptography.hazmat.primitives.asymmetric.utils.Prehashed), but pyOpenSSL doesn't support this. In general if you don't need the TLS functions of pyOpenSSL we strongly recommend the use of cryptography over pyOpenSSL.

**Comment by trevormarvin** [comment]
Thank you, that was the pointer I needed to solve my problem.

I believe I actually am using the `cryptography` module instead of the `pyOpenSSL` module; I have a code using pyOpenSSL to retrieve the keys for this process at the top of my file and incorrectly stated it as the library I'm using.  I'll assume that I'm correct to use if for fetching and preparing the keys (unless you can state otherwise).
