### ISSUE TITLE
AttributeError :__Enter__ error is throwed when using pyopenssl lib 20.01 version

### ISSUE THREAD

**Issue by thiyaneshece** [pyca/pyopenssl#988]
When creating a secure websocket connection(wss) using websocket create_connection() api call in pyopenssl - openssl/ssl.py (20.0.1), AttributeError: enter error is thrown.

```
Complete error flow is given below :
line 514, in create_connection
websock.connect(url, **options)
line 226, in connect
self.handshake_response = handshake(self.sock, *addrs, **options)
line 76, in handshake
send(sock, header_str)
line 157, in send
return _send()
line 139, in _send
return sock.send(data)
line 1644, in send
with _from_buffer(buf) as data:
AttributeError: enter
```
Websocket call flow : websocket.create_connection() -> websock.connect->handshake() -> send(sock, header_str) -> sock.send(data)

Surprisingly, when using 19.1.0 of pyopenssl version, there was no such error observed.

Between these 2 versions, send() method in SSL.py file does not have any changes. surprised to see the error when i execute the test case after the update of library.

```
with _from_buffer(buf) as data:             
    if len(buf) > 2147483647:                 
        raise ValueError("Cannot send more than 2**31-1 bytes at once.")
    result = _lib.SSL_write(self._ssl, data, len(data))
    self._raise_ssl_error(self._ssl, result)
    return result
```

**Comment by alex** [comment]
what version of `cffi` do you have installed?

**Comment by thiyaneshece** [comment]
@alex  cffi version installed is 1.1

**Comment by tiran** [comment]
> @alex cffi version installed is 1.1

That's very old. cffi 1.1.0 was released in 2015.

**Comment by alex** [comment]
You'll need to update to `cffi >= 0.12`.

**Comment by thiyaneshece** [comment]
@alex @tiran : Thanks for your feedback.
The version  cffi -->1.1 is not an explicit version mentioned in requirement.txt file in my py project.
However, this version is getting installed due to dependent py module installation, i guess.
@alex  does cffi version 1.12 is handled to fix the AttributeError: __Enter__ ?
