### ISSUE TITLE
Not able add edipartyname extension in subjectAltnames

### ISSUE THREAD

**Issue by saranyav-pulsesecure** [pyca/pyopenssl#990]
To add extension say dns we can add like this..
cert.add_extensions([X509Extension(b'subjectAltName', False, b'otherName:222')])

but in the samy way is it possible to add edipartyname extension also?

**Comment by tiran** [comment]
EdiPartyName is not a GeneralName of type OtherName. It's an explicitly tagged general name. PyCA cryptography does not support EdiPartyName, which means you cannot get or set EdiPartyName entries with cryptography yet.

```

   id-ce-subjectAltName OBJECT IDENTIFIER ::=  { id-ce 17 }

   SubjectAltName ::= GeneralNames

   GeneralNames ::= SEQUENCE SIZE (1..MAX) OF GeneralName

   GeneralName ::= CHOICE {
        otherName                       [0]     OtherName,
        rfc822Name                      [1]     IA5String,
        dNSName                         [2]     IA5String,
        x400Address                     [3]     ORAddress,
        directoryName                   [4]     Name,
        ediPartyName                    [5]     EDIPartyName,
        uniformResourceIdentifier       [6]     IA5String,
        iPAddress                       [7]     OCTET STRING,
        registeredID                    [8]     OBJECT IDENTIFIER }

   OtherName ::= SEQUENCE {
        type-id    OBJECT IDENTIFIER,
        value      [0] EXPLICIT ANY DEFINED BY type-id }

   EDIPartyName ::= SEQUENCE {
        nameAssigner            [0]     DirectoryString OPTIONAL,
        partyName               [1]     DirectoryString }
```

**Comment by alex** [comment]
The X.509 layer in pyOpenSSL is not going to be growing any new features. While pyca/cryptography doesn't currently support EDIPartyName (because we're not aware of any actual users), if you'd like to request support, please file a ticket there.
