### ISSUE TITLE
TLS 1.3 support

### ISSUE THREAD

**Issue by bortzmeyer** [pyca/pyopenssl#996]
According to [the documentation](https://www.pyopenssl.org/en/stable/api/ssl.html) and the code (no `OpenSSL.SSL.TLSv1_3_METHOD`), PyOpenSSL does not support TLS 1.3, which is available in OpenSSL. Is it planned to add it?

On a related issue: how to create a context for "1.2 or better" or "1.2 and 1.3"? I don't find it documented.

**Comment by alex** [comment]
Because we mirror OpenSSL's APIs (and there older APIs at that) the way to do 1.2+ is to set `SSLv23_METHOD` and then set all of the `OP_NO` flags for everything below 1.2: https://www.pyopenssl.org/en/stable/api/ssl.html#OpenSSL.SSL.OP_NO_SSLv2

**Comment by bortzmeyer** [comment]
@alex It works fine, thanks.
